In [1]:
import requests
import pandas as pd
import sqlite3

In [2]:
server = "https://services-eu1.arcgis.com/kswen6BYexuc1SUk/arcgis/rest/services/BathingWatersDirectiveProtectedAreas/FeatureServer/0/query?where=1%3D1&outFields=Name,PA_CD,centroidX,centroidY&returnGeometry=false&outSR=4326&f=json"

In [3]:
data = requests.get(server, headers={"Accept": "application/json, text/javascript, */*; q=0.01"})

In [7]:
df = pd.json_normalize(data.json()['features'])
df = df.rename(columns={
    "attributes.PA_CD": "id",
    "attributes.Name": "name",
    "attributes.centroidX": "lon",
    "attributes.centroidY": "lat"
})\
# .drop(columns=[
#     'attributes.CLASS_DESCRIPTION', 'attributes.BW_URL',
#     'attributes.YEAR'
# ])
df['name'] = df['name'].str.title()
df['alternate_name'] = df['name']
locations = df[[
    'id', 'name', 'alternate_name', 'lat', 'lon'
]].copy()
locations

,id,name,alternate_name,lat,lon
0,UKGBNIPA3_20021,Portballintrae Salmon Rock,Portballintrae Salmon Rock,55.220361,-6.543778
1,UKGBNIPA3_20023,Portrush Whiterocks,Portrush Whiterocks,55.208049,-6.614868
2,UKGBNIPA3_20005,Waterfoot,Waterfoot,55.060553,-6.052456
3,NaN,Donaghadee,Donaghadee,54.643732,-5.535940
4,UKGBNIPA3_20018,Ballywalter,Ballywalter,54.538587,-5.481536
5,UKGBNIPA3_20002,Brown'S Bay,Brown'S Bay,54.853726,-5.766593
6,UKGBNIPA3_20030,Ballyhornan,Ballyhornan,54.302391,-5.551984
7,UKGBNIPA3_20001,Ballycastle,Ballycastle,55.206280,-6.229273
8,UKGBNIPA3_20015,Groomsport,Groomsport,54.676235,-5.609112
9,NaN,Drain'S Bay,Drain'S Bay,54.881730,-5.835054
10,UKGBNIPA3_20020,Tyrella,Tyrella,54.250781,-5.740138
11,UKGBNIPA3_20014,Helen'S Bay,Helen'S Bay,54.673821,-5.735448
12,UKGBNIPA3_20004,Ballygalley,Ballygalley,54.899936,-5.857012
13,UKGBNIPA3_20009,Castlerock,Castlerock,55.169385,-6.782202
14,UKGBNIPA3_20013,Crawfordsburn,Crawfordsburn,54.669594,-5.724275
15,UKGBNIPA3_20023,Magilligan,Magilligan,55.168572,-6.864425
16,UKGBNIPA3_20017,Millisle,Millisle,54.604650,-5.523072
17,UKGBNIPA3_20028,Cloughey,Cloughey,54.437283,-5.465052
18,NaN,Cushendall,Cushendall,55.083460,-6.053810
19,UKGBNIPA3_20006,Newcastle,Newcastle,54.211685,-5.883888
20,NaN,Warrenpoint,Warrenpoint,54.097945,-6.247434
21,UKGBNIPA3_20022,Downhill,Downhill,55.168068,-6.832230
22,NaN,Portmuck,Portmuck,54.848161,-5.729239
23,NaN,Brompton Bay,Brompton Bay,54.668158,-5.683921
24,UKGBNIPA3_20019,Portrush Mill,Portrush Mill,55.201847,-6.660269
25,UKGBNIPA3_20016,Ballyholme,Ballyholme,54.667461,-5.643894
26,UKGBNIPA3_20024,Murlough,Murlough,54.228560,-5.855003
27,UKGBNIPA3_20026,Portrush Curran Strand,Portrush Curran Strand,55.207390,-6.638027
28,UKGBNIPA3_20029,Kilclief,Kilclief,54.333358,-5.543051
29,UKGBNIPA3_20008,Cranfield,Cranfield,54.028437,-6.072754
30,NaN,Rea'S Wood,Rea'S Wood,54.713068,-6.238074
31,UKGBNIPA3_20003,Carnlough,Carnlough,54.984679,-5.987056
32,UKGBNIPA3_20025,Portstewart,Portstewart,55.170108,-6.747745

In [8]:
locations

,id,name,alternate_name,lat,lon
0,UKGBNIPA3_20021,Portballintrae Salmon Rock,Portballintrae Salmon Rock,55.220361,-6.543778
1,UKGBNIPA3_20023,Portrush Whiterocks,Portrush Whiterocks,55.208049,-6.614868
2,UKGBNIPA3_20005,Waterfoot,Waterfoot,55.060553,-6.052456
3,NaN,Donaghadee,Donaghadee,54.643732,-5.535940
4,UKGBNIPA3_20018,Ballywalter,Ballywalter,54.538587,-5.481536
5,UKGBNIPA3_20002,Brown'S Bay,Brown'S Bay,54.853726,-5.766593
6,UKGBNIPA3_20030,Ballyhornan,Ballyhornan,54.302391,-5.551984
7,UKGBNIPA3_20001,Ballycastle,Ballycastle,55.206280,-6.229273
8,UKGBNIPA3_20015,Groomsport,Groomsport,54.676235,-5.609112
9,NaN,Drain'S Bay,Drain'S Bay,54.881730,-5.835054
10,UKGBNIPA3_20020,Tyrella,Tyrella,54.250781,-5.740138
11,UKGBNIPA3_20014,Helen'S Bay,Helen'S Bay,54.673821,-5.735448
12,UKGBNIPA3_20004,Ballygalley,Ballygalley,54.899936,-5.857012
13,UKGBNIPA3_20009,Castlerock,Castlerock,55.169385,-6.782202
14,UKGBNIPA3_20013,Crawfordsburn,Crawfordsburn,54.669594,-5.724275
15,UKGBNIPA3_20023,Magilligan,Magilligan,55.168572,-6.864425
16,UKGBNIPA3_20017,Millisle,Millisle,54.604650,-5.523072
17,UKGBNIPA3_20028,Cloughey,Cloughey,54.437283,-5.465052
18,NaN,Cushendall,Cushendall,55.083460,-6.053810
19,UKGBNIPA3_20006,Newcastle,Newcastle,54.211685,-5.883888
20,NaN,Warrenpoint,Warrenpoint,54.097945,-6.247434
21,UKGBNIPA3_20022,Downhill,Downhill,55.168068,-6.832230
22,NaN,Portmuck,Portmuck,54.848161,-5.729239
23,NaN,Brompton Bay,Brompton Bay,54.668158,-5.683921
24,UKGBNIPA3_20019,Portrush Mill,Portrush Mill,55.201847,-6.660269
25,UKGBNIPA3_20016,Ballyholme,Ballyholme,54.667461,-5.643894
26,UKGBNIPA3_20024,Murlough,Murlough,54.228560,-5.855003
27,UKGBNIPA3_20026,Portrush Curran Strand,Portrush Curran Strand,55.207390,-6.638027
28,UKGBNIPA3_20029,Kilclief,Kilclief,54.333358,-5.543051
29,UKGBNIPA3_20008,Cranfield,Cranfield,54.028437,-6.072754
30,NaN,Rea'S Wood,Rea'S Wood,54.713068,-6.238074
31,UKGBNIPA3_20003,Carnlough,Carnlough,54.984679,-5.987056
32,UKGBNIPA3_20025,Portstewart,Portstewart,55.170108,-6.747745

In [9]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(locations):
    # Replace missing values with "" in column: 'id'
    locations = locations.fillna({'id': "UKGBNIPA_" + df['name'].apply(lambda x: x.replace("'", "").replace(" ", "").upper())})
    return locations

locations_clean = clean_data(locations.copy())
locations_clean.head()

,id,name,alternate_name,lat,lon
0,UKGBNIPA3_20021,Portballintrae Salmon Rock,Portballintrae Salmon Rock,55.220361,-6.543778
1,UKGBNIPA3_20023,Portrush Whiterocks,Portrush Whiterocks,55.208049,-6.614868
2,UKGBNIPA3_20005,Waterfoot,Waterfoot,55.060553,-6.052456
3,UKGBNIPA_DONAGHADEE,Donaghadee,Donaghadee,54.643732,-5.535940
4,UKGBNIPA3_20018,Ballywalter,Ballywalter,54.538587,-5.481536

In [6]:
# db = sqlite3.connect("../dataset.sqlite3")
# locations.to_sql("locations", db, if_exists="append")