In [2]:
import geopandas as gpd
from requests import Request
from owslib.wfs import WebFeatureService

In [3]:
url = "https://pubgeo.zwemwater.nl/geoserver/zwr_public/wfs"
wfs = WebFeatureService(url=url)

In [4]:
def load_wfs_layer(layer_name):
    params = dict(service='WFS', version="2.0.0", request='GetFeature',
      typeName=layer_name, outputFormat='json', srsName="EPSG:4326")
    wfs_request_url = Request('GET', url, params=params).prepare().url
    return gpd.read_file(wfs_request_url)

# Data

### Zwemplekken

In [5]:
zwemplekken = load_wfs_layer("zwr_public:zwemplekken")
zwemplekken = zwemplekken.drop(columns=['id', 'datum']).set_index('key_id')
zwemplekken.drop_duplicates(subset=['zwemwaterlocatie_id'], inplace=True)
zwemplekken

,korte_naam,naam,status,zwemwaterlocatie_id,geometry
key_id,,,,,
2316,'t Kleine Zeetje,Recreatiepark 't Kleine Zeetje,NEGATIEF_ZWEMADVIES,1595,POINT (5.3762 52.2602)
1954,Plas Vrijenburgbos,Plas Vrijenburgbos,NEGATIEF_ZWEMADVIES,1233,POINT (4.5003 51.868)
1962,Kralinger Esch,Kralinger Esch,NEGATIEF_ZWEMADVIES,1241,POINT (4.5253 51.9138)
303593,Het Blauwe Meer Dinxperlo,Het Blauwe Meer,NEGATIEF_ZWEMADVIES,302622,POINT (6.4807 51.8594)
304939,Rietschoof,Rietschoof,NEGATIEF_ZWEMADVIES,1623,POINT (5.1241 51.7771)
...,...,...,...,...,...
8429710,Den Bommel Badstrand,Den Bommel Badstrand,goed,8429640,POINT (4.2818 51.7212)
8435100,None,Noorderstrand,goed,8435070,POINT (5.3589 52.8795)
8439140,Hoorn-Zuid,Hoorn-Zuid,goed,8439110,POINT (5.043 52.6376)
8449920,Het Heijderbos,Center Parcs Het Heijderbos,goed,8449690,POINT (5.9952 51.6738)
8452761,Lagune Camperduin,Lagune Camperduin,goed,8452780,POINT (4.639 52.7236)

In [7]:
zwemplekken_details = load_wfs_layer("zwr_public:zwemplekken_details")
zwemplekken_details = zwemplekken_details.drop(columns=["id", "info_id", "geometry", "datum"])
zwemplekken_details['adr_huisnummer'] = zwemplekken_details['adr_huisnummer'].astype('Int64')
zwemplekken_details[['adr_huisletter', 'adr_huisnummertoevoeging', 'adr_straat']] = zwemplekken_details[['adr_huisletter', 'adr_huisnummertoevoeging', 'adr_straat']].fillna('')
zwemplekken_details[['adr_straat', 'adr_huisnummer', 'adr_huisletter', 'adr_huisnummertoevoeging']].astype(str)
zwemplekken_details['adr_huisnummer'] = zwemplekken_details['adr_huisnummer'].astype(str).replace('<NA>','')
zwemplekken_details['adr_postcode'] = zwemplekken_details['adr_postcode'].fillna('')
zwemplekken_details['adr_woonplaats'] = zwemplekken_details['adr_woonplaats'].fillna('')
zwemplekken_details['street'] = zwemplekken_details[['adr_straat', 'adr_huisnummer', 'adr_huisletter', 'adr_huisnummertoevoeging']].applymap(lambda x: str(x).strip()).agg(' '.join, axis=1)

# Function to concatenate values only if both columns have non-missing values
def concatenate_if_both_not_na(row):
    print(row)
    col1 = row['street'].strip()
    col2 = row['adr_woonplaats'].strip()
    if col1 and col2:
        return f"{col1}, {col2}"
    else:
        if len(col2.strip()) > 0:
            return col2
        return ""


zwemplekken_details['address'] = zwemplekken_details.apply(concatenate_if_both_not_na, axis=1)
zwemplekken_details.drop(columns=['adr_huisnummer', 'adr_huisletter', 'adr_huisnummertoevoeging', 'adr_straat', 'adr_postcode', 'street'], inplace=True)
zwemplekken_details.drop_duplicates(subset=['zwemwaterlocatie_id'], inplace=True)
zwemplekken_details

adr_huisletter
adr_huisnummer
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                           De Dreef
adr_woonplaats                                                     Heerenveen
info_filename                                         FR-043-001 De Heide.jpg
info_length                                                          356023.0
info_mime_type                                                     image/jpeg
key_id                                                                   1676
korte_naam                                                              Heide
naam                                                                 De Heide
objecttype                                                           zwemplek
org_bedrijfsnaam                                          Gemeente Heerenveen
org_email                                              gemeente@heerenveen.nl
org_fax
org_huisletter
org_huisnumeer                                                            NaN
org_huisnummertoevoeging
org_id                                                                5922365
org_postcode                                                             None
org_straat
org_telefoon                                                    0513-617 617
org_website                                          http://www.heerenveen.nl
org_woonplaats                                                     Heerenveen
status                                                                   goed
taal                                                                       nl
tekst                       Het recreatiegebied “De Heide”, ligt aan de zu...
toegang                                                    OPENBAAR ONBETAALD
website                                                                  None
zwemwaterlocatie_id                                                       955
street                                                            De Dreef
Name: 0, dtype: object
adr_huisletter
adr_huisnummer
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                           Spokedam
adr_woonplaats                                                     Noordwolde
info_filename                                       FR-046-001 Spoekeplas.jpg
info_length                                                          297473.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1677
korte_naam                                                         Spoekeplas
naam                                                               Spoekeplas
objecttype                                                           zwemplek
org_bedrijfsnaam                                  Staatsbosbeheer Regio Noord
org_email                                             info@staatsbosbeheer.nl
org_fax
org_huisletter
org_huisnumeer                                                            NaN
org_huisnummertoevoeging
org_id                                                                5922347
org_postcode                                                             None
org_straat
org_telefoon                                                    050 707 4444
org_website                                     http://www.staatsbosbeheer.nl
org_woonplaats                                                      Groningen
status                                                                   goed
taal                                                                       nl
tekst                       Het zwemwater Spoekeplas ligt ten zuidwesten v...
toegang                                                    OPENBAAR ONBETAALD
website                                                                  None
zwemwaterlocatie_id                                                       956
street                                                            Spokedam
Name: 1, dtype: object
adr_huisletter
adr_huisnummer
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                             Canada
adr_woonplaats                                                      Appelscha
info_filename                                        Canadameer Appelscha.png
info_length                                                          212248.0
info_mime_type                                                      image/png
key_id                                                                   1678
korte_naam                                                         Canadameer
naam                                                               Canadameer
objecttype                                                           zwemplek
org_bedrijfsnaam                                  Staatsbosbeheer Regio Noord
org_email                                             info@staatsbosbeheer.nl
org_fax
org_huisletter
org_huisnumeer                                                            NaN
org_huisnummertoevoeging
org_id                                                                5922347
org_postcode                                                             None
org_straat
org_telefoon                                                    050 707 4444
org_website                                     http://www.staatsbosbeheer.nl
org_woonplaats                                                      Groningen
status                                                                   goed
taal                                                                       nl
tekst                       Het Canadameer (ook wel Aekingermeer genoemd) ...
toegang                                                    OPENBAAR ONBETAALD
website                                                                  None
zwemwaterlocatie_id                                                       957
street                                                              Canada
Name: 2, dtype: object
adr_huisletter
adr_huisnummer
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                     Kleasterkampen
adr_woonplaats                                                      Smalle Ee
info_filename                                 FR-028-001 Smeliester SaÌ‚n.jpg
info_length                                                          210638.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1680
korte_naam                                                     Smeliester Sân
naam                                                           Smeliester Sân
objecttype                                                           zwemplek
org_bedrijfsnaam                                      Gemeente Smallingerland
org_email                                          gemeente@smallingerland.nl
org_fax
org_huisletter
org_huisnumeer                                                            NaN
org_huisnummertoevoeging
org_id                                                                5922348
org_postcode                                                             None
org_straat
org_telefoon                                                      0512-581234
org_website                                      http://www.smallingerland.nl
org_woonplaats                                                       Drachten
status                                                                   goed
taal                                                                       nl
tekst                       Het zwemwater ligt aan de zuidzijde van het ge...
toegang                                                    OPENBAAR ONBETAALD
website                                                                  None
zwemwaterlocatie_id                                                       959
street                                                      Kleasterkampen
Name: 3, dtype: object
adr_huisletter
adr_huisnummer
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                           Bildreed
adr_woonplaats                                                     Rottevalle
info_filename                                         FR-027-001 De Leien.jpg
info_length                                                          209646.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1681
korte_naam                                                           De Leien
naam                                                                 De Leien
objecttype                                                           zwemplek
org_bedrijfsnaam                                  Staatsbosbeheer Regio Noord
org_email                                             info@staatsbosbeheer.nl
org_fax
org_huisletter
org_huisnumeer                                                            NaN
org_huisnummertoevoeging
org_id                                                                5922347
org_postcode                                                             None
org_straat
org_telefoon                                                    050 707 4444
org_website                                     http://www.staatsbosbeheer.nl
org_woonplaats                                                      Groningen
status                                                                   goed
taal                                                                       nl
tekst                       Het zwemwater ligt enkele kilometers ten noord...
toegang                                                    OPENBAAR ONBETAALD
website                                                                  None
zwemwaterlocatie_id                                                       960
street                                                            Bildreed
Name: 4, dtype: object
adr_huisletter
adr_huisnummer
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                    Koaidyk/Walddyk
adr_woonplaats                                                      Earnewâld
info_filename                                      FR-026-001 EarnewaÌ‚ld.jpg
info_length                                                          217711.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1682
korte_naam                                               Zwemplaats Earnewâld
naam                                                     Zwemplaats Earnewâld
objecttype                                                           zwemplek
org_bedrijfsnaam            Stichting Behear Rekreative Foarsjennings Earn...
org_email                                             sbrfearnewald@gmail.com
org_fax
org_huisletter
org_huisnumeer                                                            NaN
org_huisnummertoevoeging
org_id                                                                5922346
org_postcode                                                             None
org_straat
org_telefoon                                                      06-12142631
org_website                                      http://www.havenearnewald.nl
org_woonplaats                                                      Earnewâld
status                                                                   goed
taal                                                                       nl
tekst                       Zwemplaats Earnewâld, ook bekend als It Wiid, ...
toegang                                                    OPENBAAR ONBETAALD
website                                                                  None
zwemwaterlocatie_id                                                       961
street                                                     Koaidyk/Walddyk
Name: 5, dtype: object
adr_huisletter
adr_huisnummer                                                             30
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                      Solcamastraat
adr_woonplaats                                                          Sumar
info_filename                          FR-024-001 Klein Zwitserland Sumar.jpg
info_length                                                          264948.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1683
korte_naam                                                  Klein Zwitserland
naam                                    Dagrecreatieterrein Klein Zwitserland
objecttype                                                           zwemplek
org_bedrijfsnaam                                    Vakantiepark Bergumermeer
org_email                                                info@bergumermeer.nl
org_fax                                                                  None
org_huisletter                                                           None
org_huisnumeer                                                            NaN
org_huisnummertoevoeging                                                 None
org_id                                                                5922344
org_postcode                                                             None
org_straat                                                               None
org_telefoon                                                      0511-461385
org_website                                        http://www.bergumermeer.nl
org_woonplaats                                                          Sumar
status                                                                   goed
taal                                                                       nl
tekst                       Het zwemwater ligt aan de westzijde van het Bu...
toegang                                                    OPENBAAR ONBETAALD
website                                                                  None
zwemwaterlocatie_id                                                       962
street                                                     Solcamastraat 30
Name: 6, dtype: object
adr_huisletter
adr_huisnummer
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                Prins Bernhardweg 1
adr_woonplaats                                                Schiermonnikoog
info_filename                                       FR-010-001 Berkenplas.jpg
info_length                                                          254584.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1684
korte_naam                                                         Berkenplas
naam                                                               Berkenplas
objecttype                                                           zwemplek
org_bedrijfsnaam            Vereniging Natuurmonumenten, Nationaal Park Sc...
org_email                                 schiermonnikoog@natuurmonumenten.nl
org_fax                                                                  None
org_huisletter                                                           None
org_huisnumeer                                                            NaN
org_huisnummertoevoeging                                                 None
org_id                                                                5922125
org_postcode                                                             None
org_straat                                                               None
org_telefoon                                                     0519 531 233
org_website                                                              None
org_woonplaats                                                Schiermonnikoog
status                                                           WAARSCHUWING
taal                                                                       nl
tekst                       De zwemlocatie ligt op Schiermonnikoog ten noo...
toegang                                                    OPENBAAR ONBETAALD
website                                                                  None
zwemwaterlocatie_id                                                       963
street                                                 Prins Bernhardweg 1
Name: 7, dtype: object
adr_huisletter
adr_huisnummer
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                    Bramerduinenpad
adr_woonplaats                                                            Nes
info_filename                                        FR-009-001 De Vleyen.jpg
info_length                                                          271129.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1685
korte_naam                                                             Vleyen
naam                                                                De Vleyen
objecttype                                                           zwemplek
org_bedrijfsnaam                                             Gemeente Ameland
org_email                                                     info@ameland.nl
org_fax                                                                  None
org_huisletter                                                           None
org_huisnumeer                                                            NaN
org_huisnummertoevoeging                                                 None
org_id                                                                 299378
org_postcode                                                             None
org_straat                                                               None
org_telefoon                                                      0519-555555
org_website                                             http://www.ameland.nl
org_woonplaats                                                        Ameland
status                                                           WAARSCHUWING
taal                                                                       nl
tekst                       De zwemwaterlocatie ligt op Ameland ten noordo...
toegang                                                    OPENBAAR ONBETAALD
website                                                                  None
zwemwaterlocatie_id                                                       964
street                                                     Bramerduinenpad
Name: 8, dtype: object
adr_huisletter
adr_huisnummer
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                        Mountsjewei
adr_woonplaats                                                     Leeuwarden
info_filename                                     FR-022-001 Lytse Wielen.jpg
info_length                                                          211342.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1686
korte_naam                                                       Lytse Wielen
naam                                                 Lytse Wielen/Groene Ster
objecttype                                                           zwemplek
org_bedrijfsnaam                                          Gemeente Leeuwarden
org_email                                              gemeente@leeuwarden.nl
org_fax
org_huisletter

/var/folders/c4/2j8ddht53cb4c_40b6_x0kq00000gn/T/ipykernel_40064/3865462705.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  zwemplekken_details['street'] = zwemplekken_details[['adr_straat', 'adr_huisnummer', 'adr_huisletter', 'adr_huisnummertoevoeging']].applymap(lambda x: str(x).strip()).agg(' '.join, axis=1)

,adr_woonplaats,info_filename,info_length,info_mime_type,key_id,korte_naam,naam,objecttype,org_bedrijfsnaam,org_email,...,org_telefoon,org_website,org_woonplaats,status,taal,tekst,toegang,website,zwemwaterlocatie_id,address
0,Heerenveen,FR-043-001 De Heide.jpg,356023.0,image/jpeg,1676,Heide,De Heide,zwemplek,Gemeente Heerenveen,gemeente@heerenveen.nl,...,0513-617 617,http://www.heerenveen.nl,Heerenveen,goed,nl,"Het recreatiegebied “De Heide”, ligt aan de zu...",OPENBAAR ONBETAALD,None,955,"De Dreef, Heerenveen"
1,Noordwolde,FR-046-001 Spoekeplas.jpg,297473.0,image/pjpeg,1677,Spoekeplas,Spoekeplas,zwemplek,Staatsbosbeheer Regio Noord,info@staatsbosbeheer.nl,...,050 707 4444,http://www.staatsbosbeheer.nl,Groningen,goed,nl,Het zwemwater Spoekeplas ligt ten zuidwesten v...,OPENBAAR ONBETAALD,None,956,"Spokedam, Noordwolde"
2,Appelscha,Canadameer Appelscha.png,212248.0,image/png,1678,Canadameer,Canadameer,zwemplek,Staatsbosbeheer Regio Noord,info@staatsbosbeheer.nl,...,050 707 4444,http://www.staatsbosbeheer.nl,Groningen,goed,nl,Het Canadameer (ook wel Aekingermeer genoemd) ...,OPENBAAR ONBETAALD,None,957,"Canada, Appelscha"
3,Smalle Ee,FR-028-001 Smeliester SaÌ‚n.jpg,210638.0,image/pjpeg,1680,Smeliester Sân,Smeliester Sân,zwemplek,Gemeente Smallingerland,gemeente@smallingerland.nl,...,0512-581234,http://www.smallingerland.nl,Drachten,goed,nl,Het zwemwater ligt aan de zuidzijde van het ge...,OPENBAAR ONBETAALD,None,959,"Kleasterkampen, Smalle Ee"
4,Rottevalle,FR-027-001 De Leien.jpg,209646.0,image/pjpeg,1681,De Leien,De Leien,zwemplek,Staatsbosbeheer Regio Noord,info@staatsbosbeheer.nl,...,050 707 4444,http://www.staatsbosbeheer.nl,Groningen,goed,nl,Het zwemwater ligt enkele kilometers ten noord...,OPENBAAR ONBETAALD,None,960,"Bildreed, Rottevalle"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950,Stavoren,None,NaN,None,8435100,None,Noorderstrand,zwemplek,Gemeente Súdwest Fryslân,info@sudwestfryslan.nl,...,0515-489000,http://www.gemeentesudwestfryslan.nl,Sneek,goed,nl,Zwemlocatie Noorderstrand (Stavoren Noord) lig...,None,None,8435070,"Stadsfenne, Stavoren"
951,Hoorn,NH-020-004.PNG,222275.0,image/png,8439140,Hoorn-Zuid,Hoorn-Zuid,zwemplek,Recreatieschap West-Friesland,info@recreatieschapwestfriesland.nl,...,0228-565750,http://www.recreatieschapwestfriesland.nl,Bovenkarspel,goed,nl,In 2024 is de zwemwaterlocatie inclusief de zw...,OPENBAAR ONBETAALD,https://www.hoornsestadsstrand.nl/,8439110,"Westerdijk, Hoorn"
952,Heijen,None,NaN,None,8449920,Het Heijderbos,Center Parcs Het Heijderbos,zwemplek,Center Parcs Het Heijderbos,guestrelations.heijderbos@groupepvcp.com,...,0485-496700,https://www.centerparcs.nl/nl-nl/nederland/fp_...,Heijen,goed,nl,"De zwemlocatie is onderdeel van Center Parcs ""...",None,https://www.centerparcs.nl/nl-nl/nederland/fp_...,8449690,"Hommersumseweg 43, Heijen"
953,Bergen (NH),NH-004-004.PNG,166515.0,image/png,8452761,Lagune Camperduin,Lagune Camperduin,zwemplek,Gemeente Bergen,info@bergen-nh.nl,...,072-8880000,http://www.bergen-nh.nl,Bergen,goed,nl,De Lagune Camperduin is een waterlichaam dat g...,None,None,8452780,Bergen (NH)
954,Waalwijk,None,NaN,None,8455080,Surfvijver Waalwijk,Surfvijver Waalwijk,zwemplek,Gemeente Waalwijk,info@waalwijk.nl,...,0416-683456,None,Waalwijk,WAARSCHUWING,nl,De Surfvijver in Waalwijk is gelegen in de pro...,gratis,None,8455040,"Vijverlaan, Waalwijk"

In [8]:
zwemplekken_details.columns

Index(['adr_woonplaats', 'info_filename', 'info_length', 'info_mime_type',
       'key_id', 'korte_naam', 'naam', 'objecttype', 'org_bedrijfsnaam',
       'org_email', 'org_fax', 'org_huisletter', 'org_huisnumeer',
       'org_huisnummertoevoeging', 'org_id', 'org_postcode', 'org_straat',
       'org_telefoon', 'org_website', 'org_woonplaats', 'status', 'taal',
       'tekst', 'toegang', 'website', 'zwemwaterlocatie_id', 'address'],
      dtype='object')

In [9]:
photos = load_wfs_layer("zwr_public:locatiefotos")
photos

,id,filename,key_id,length,mime_type,zwemplek_id,geometry
0,locatiefotos.fid-4e6d9d79_1976962f2a2_-1376,testgegevens.csv,559072,23483,application/vnd.ms-excel,NaN,None
1,locatiefotos.fid-4e6d9d79_1976962f2a2_-1375,18-07-2012.jpg,559074,18482,image/pjpeg,1762.0,"POLYGON ((5.9978 52.311, 5.998 52.3109, 6.0003..."
2,locatiefotos.fid-4e6d9d79_1976962f2a2_-1374,FR-005-001 Badstrand Nes.jpg,1092,327074,image/pjpeg,NaN,None
3,locatiefotos.fid-4e6d9d79_1976962f2a2_-1373,FR-004-001 Badstrand Hollum.jpg,1091,280508,image/pjpeg,NaN,None
4,locatiefotos.fid-4e6d9d79_1976962f2a2_-1372,FR-009-001 De Vleyen.jpg,1093,271129,image/pjpeg,NaN,None
...,...,...,...,...,...,...,...
6059,locatiefotos.fid-4e6d9d79_1976962f2a2_435,Waarschuwing ivm zwemmersjeuk.odt,8520262,5904,application/vnd.oasis.opendocument.text,NaN,None
6060,locatiefotos.fid-4e6d9d79_1976962f2a2_436,Waarschuwing ivm zwemmersjeuk.odt,8520263,5904,application/vnd.oasis.opendocument.text,NaN,None
6061,locatiefotos.fid-4e6d9d79_1976962f2a2_437,Blauwalg natuurbad Tynaarloo.docx,8520264,19910,application/vnd.openxmlformats-officedocument....,NaN,None
6062,locatiefotos.fid-4e6d9d79_1976962f2a2_438,waarschuwing oostvoornse meer noordzijde en zu...,8520265,13872,application/vnd.openxmlformats-officedocument....,NaN,None
6063,locatiefotos.fid-4e6d9d79_1976962f2a2_439,waarschuwing oostvoornse meer noordzijde en zu...,8520266,13872,application/vnd.openxmlformats-officedocument....,NaN,None

In [10]:
photos["mime_type"].unique()

array(['application/vnd.ms-excel', 'image/pjpeg', 'image/jpeg',
       'image/png', 'application/pdf', 'application/octet-stream',
       'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
       'application/msword',
       'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
       'text/plain', 'ds/document', 'text/html',
       'application/vnd.oasis.opendocument.text'], dtype=object)

In [11]:
photos = photos[
    photos['mime_type'].isin([
        'image/pjpeg', 
        'image/jpeg',
        'image/png'
    ])
]
photos

,id,filename,key_id,length,mime_type,zwemplek_id,geometry
1,locatiefotos.fid-4e6d9d79_1976962f2a2_-1375,18-07-2012.jpg,559074,18482,image/pjpeg,1762.0,"POLYGON ((5.9978 52.311, 5.998 52.3109, 6.0003..."
2,locatiefotos.fid-4e6d9d79_1976962f2a2_-1374,FR-005-001 Badstrand Nes.jpg,1092,327074,image/pjpeg,NaN,None
3,locatiefotos.fid-4e6d9d79_1976962f2a2_-1373,FR-004-001 Badstrand Hollum.jpg,1091,280508,image/pjpeg,NaN,None
4,locatiefotos.fid-4e6d9d79_1976962f2a2_-1372,FR-009-001 De Vleyen.jpg,1093,271129,image/pjpeg,NaN,None
5,locatiefotos.fid-4e6d9d79_1976962f2a2_-1371,FR-006-001 Badstrand Buren.jpg,1094,299640,image/pjpeg,NaN,None
...,...,...,...,...,...,...,...
6019,locatiefotos.fid-4e6d9d79_1976962f2a2_40d,NH-004-004.PNG,8487451,166515,image/png,NaN,None
6022,locatiefotos.fid-4e6d9d79_1976962f2a2_410,speelvijver-kibbelkoele[1].jpg,8488652,99707,image/jpeg,2128.0,"POLYGON ((6.7901 52.8098, 6.7912 52.8101, 6.79..."
6049,locatiefotos.fid-4e6d9d79_1976962f2a2_42b,2025-05-19 16.29.23_9214 VP.jpeg,8494120,2671508,image/jpeg,NaN,None
6051,locatiefotos.fid-4e6d9d79_1976962f2a2_42d,NH-020-004.PNG,8512040,222275,image/png,NaN,None
6052,locatiefotos.fid-4e6d9d79_1976962f2a2_42e,NH-020-004.PNG,8512041,222275,image/png,NaN,None

In [12]:
photos = photos.query("zwemplek_id.notnull()")
photodata = photos[['zwemplek_id', 'key_id', 'filename']].copy()
photodata['zwemplek_id'] = photodata['zwemplek_id'].astype(int)
photodata['key_id'] = "https://register.zwemwater.nl/zwr/api/files/" + photodata['key_id'].astype(str)
for item in photodata.query('zwemplek_id == 6187300').iterrows():
    print(item)

(4002, zwemplek_id                                              6187300
key_id         https://register.zwemwater.nl/zwr/api/files/61...
filename                            WP_20170413_12_40_27_Pro.jpg
Name: 4002, dtype: object)
(4003, zwemplek_id                                              6187300
key_id         https://register.zwemwater.nl/zwr/api/files/61...
filename                         2019 IMG_20190629_101301032.jpg
Name: 4003, dtype: object)
(4004, zwemplek_id                                              6187300
key_id         https://register.zwemwater.nl/zwr/api/files/61...
filename        2017 Overzichtsfoto WP_20170413_12_42_21_Pro.jpg
Name: 4004, dtype: object)

In [13]:
base_data = zwemplekken_details.copy()
base_data = base_data[["zwemwaterlocatie_id", "naam", "korte_naam", "address", "adr_woonplaats", "status", "tekst", "info_filename", "website"]]
base_data

,zwemwaterlocatie_id,naam,korte_naam,address,adr_woonplaats,status,tekst,info_filename,website
0,955,De Heide,Heide,"De Dreef, Heerenveen",Heerenveen,goed,"Het recreatiegebied “De Heide”, ligt aan de zu...",FR-043-001 De Heide.jpg,None
1,956,Spoekeplas,Spoekeplas,"Spokedam, Noordwolde",Noordwolde,goed,Het zwemwater Spoekeplas ligt ten zuidwesten v...,FR-046-001 Spoekeplas.jpg,None
2,957,Canadameer,Canadameer,"Canada, Appelscha",Appelscha,goed,Het Canadameer (ook wel Aekingermeer genoemd) ...,Canadameer Appelscha.png,None
3,959,Smeliester Sân,Smeliester Sân,"Kleasterkampen, Smalle Ee",Smalle Ee,goed,Het zwemwater ligt aan de zuidzijde van het ge...,FR-028-001 Smeliester SaÌ‚n.jpg,None
4,960,De Leien,De Leien,"Bildreed, Rottevalle",Rottevalle,goed,Het zwemwater ligt enkele kilometers ten noord...,FR-027-001 De Leien.jpg,None
...,...,...,...,...,...,...,...,...,...
950,8435070,Noorderstrand,None,"Stadsfenne, Stavoren",Stavoren,goed,Zwemlocatie Noorderstrand (Stavoren Noord) lig...,None,None
951,8439110,Hoorn-Zuid,Hoorn-Zuid,"Westerdijk, Hoorn",Hoorn,goed,In 2024 is de zwemwaterlocatie inclusief de zw...,NH-020-004.PNG,https://www.hoornsestadsstrand.nl/
952,8449690,Center Parcs Het Heijderbos,Het Heijderbos,"Hommersumseweg 43, Heijen",Heijen,goed,"De zwemlocatie is onderdeel van Center Parcs ""...",None,https://www.centerparcs.nl/nl-nl/nederland/fp_...
953,8452780,Lagune Camperduin,Lagune Camperduin,Bergen (NH),Bergen (NH),goed,De Lagune Camperduin is een waterlichaam dat g...,NH-004-004.PNG,None
954,8455040,Surfvijver Waalwijk,Surfvijver Waalwijk,"Vijverlaan, Waalwijk",Waalwijk,WAARSCHUWING,De Surfvijver in Waalwijk is gelegen in de pro...,None,None

In [28]:
zwemplekdata = base_data.merge(zwemplekken, left_on="zwemwaterlocatie_id", right_on="zwemwaterlocatie_id", how="left")
zwemplekdata['lat'] = zwemplekdata['geometry'].apply(lambda geom: geom.y if geom else None)
zwemplekdata['lon'] = zwemplekdata['geometry'].apply(lambda geom: geom.x if geom else None)
zwemplekdata = zwemplekdata.drop(columns=["korte_naam_x", "naam_x", "status_x", "geometry"])
zwemplekdata = zwemplekdata.rename(columns={
    "naam_y": "naam",
    "korte_naam_y": "korte_naam",
    "status_y": "status"
})
zwemplekdata.sort_values(by=["naam"], inplace=True)
zwemplekdata

,zwemwaterlocatie_id,address,adr_woonplaats,tekst,info_filename,website,korte_naam,naam,status,lat,lon
574,1259,"Hoefsvenlaan, Waalwijk",Waalwijk,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,'T Hoefsven,'T Hoefsven,goed,51.6761,5.0942
278,1341,"Bosweg, Gasselte",Gasselte,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,'T Nije Hemelriek,'T Nije Hemelriek,goed,52.9725,6.7556
605,1315,"Holthesedijk, Overloon",Overloon,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,'T Schaartven,'T Schaartven,goed,51.5735,5.9749
281,1344,"Paralelleweg, Tynaarlo",Tynaarlo,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,'T Veenmeer,'T Veenmeer,goed,53.0829,6.6303
257,1291,"Witvenseweg, Veldhoven",Veldhoven,De zwemlocatie ligt ten zuiden van de gemeente...,NB-059-001 't Witven.jpg,http://www.witven.nl,Witven,'T Witven,goed,51.3979,5.4108
...,...,...,...,...,...,...,...,...,...,...,...
727,7941840,Kortgene,Kortgene,Door camping de Paardekreek aangelegd zandstra...,None,None,Paardekreek,strand Kortgene Paardekreek,goed,51.5496,3.8096
710,7356682,,,strand zoutkamp in onderzoek,None,None,None,strand zoutkamp,goed,53.3388,6.2973
690,6837320,"Elfenbank 1, Blauwe stad",Blauwe stad,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,strand zuid,strand zuid Oldambtmeer,goed,53.1651,7.0372
689,6997562,,,Strandje naast jachthaven van Brouwershaven,None,None,Brouwershaven,strandje Brouwershaven,goed,51.7315,3.9154
231,1240,"Oude Raadhuislaan 154, Rotterdam",Rotterdam,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,'t Zwarte Plasje,t Zwarte Plasje,goed,51.9593,4.4913

### EU statussen

In [30]:
eu_designations = load_wfs_layer("zwr_public:eustatussen")
eu_designations = eu_designations[eu_designations['jaar'] == 2024].drop(columns=['type_eu_status_id', 'geometry', 'omschrijving', 'id'])
eu_designations

     code   key_id  jaar  zwemwaterlocatie_id
1020    1  8421624  2024              6505733
1854    2  8413390  2024                 1340
3606    4  8421625  2024              6837321
3635    1  8421626  2024              7356682
7713    7  8413417  2024                 1372
...   ...      ...   ...                  ...
8447    1  8423281  2024                 1626
8448    7  8422156  2024                 1586
8449    2  8423021  2024                 1388
8450    7  8420512  2024                 1185
8451    4  8423028  2024                 1460

[736 rows x 4 columns]

In [31]:
eu_current_designations = eu_designations.drop(columns=["key_id", "jaar"])
eu_current_designations
data = zwemplekdata.merge(eu_current_designations, left_on="zwemwaterlocatie_id", right_on="zwemwaterlocatie_id", how="left")
data.fillna({'code': 0}, inplace=True)
data

,zwemwaterlocatie_id,address,adr_woonplaats,tekst,info_filename,website,korte_naam,naam,status,lat,lon,code
0,1259,"Hoefsvenlaan, Waalwijk",Waalwijk,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,'T Hoefsven,'T Hoefsven,goed,51.6761,5.0942,1
1,1341,"Bosweg, Gasselte",Gasselte,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,'T Nije Hemelriek,'T Nije Hemelriek,goed,52.9725,6.7556,1
2,1315,"Holthesedijk, Overloon",Overloon,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,'T Schaartven,'T Schaartven,goed,51.5735,5.9749,1
3,1344,"Paralelleweg, Tynaarlo",Tynaarlo,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,'T Veenmeer,'T Veenmeer,goed,53.0829,6.6303,1
4,1291,"Witvenseweg, Veldhoven",Veldhoven,De zwemlocatie ligt ten zuiden van de gemeente...,NB-059-001 't Witven.jpg,http://www.witven.nl,Witven,'T Witven,goed,51.3979,5.4108,1
...,...,...,...,...,...,...,...,...,...,...,...,...
750,7941840,Kortgene,Kortgene,Door camping de Paardekreek aangelegd zandstra...,None,None,Paardekreek,strand Kortgene Paardekreek,goed,51.5496,3.8096,2
751,7356682,,,strand zoutkamp in onderzoek,None,None,None,strand zoutkamp,goed,53.3388,6.2973,1
752,6837320,"Elfenbank 1, Blauwe stad",Blauwe stad,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,strand zuid,strand zuid Oldambtmeer,goed,53.1651,7.0372,3
753,6997562,,,Strandje naast jachthaven van Brouwershaven,None,None,Brouwershaven,strandje Brouwershaven,goed,51.7315,3.9154,1
754,1240,"Oude Raadhuislaan 154, Rotterdam",Rotterdam,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,'t Zwarte Plasje,t Zwarte Plasje,goed,51.9593,4.4913,1

### Metingen

In [32]:
measurements = load_wfs_layer("zwr_public:resultaatsen")
measurements = measurements.drop(columns=['id', 'datum_geplande_monstername', 'monitoring_datum_id', 'monitoring_plan_id', 'monster_id', 'type_object_id', 'geometry'])
measurements = measurements.sort_values(["zwemwaterlocatie_id", "object_begin_tijd", "type_object_code"])
measurements = measurements.drop_duplicates(subset=["zwemwaterlocatie_id", "type_object_code"], keep="last")
measurements

,numerieke_waarde,object_begin_tijd,key_id,type_object_code,zwemwaterlocatie_id
2074,60,2025-06-10 09:06:00+00:00,8521219,E_COLI,955
4348,60,2025-06-10 09:06:00+00:00,8521230,INTTNLETRCCN,955
1902,80,2025-06-02 07:56:00+00:00,8514583,E_COLI,956
4175,160,2025-06-02 07:56:00+00:00,8514584,INTTNLETRCCN,956
1903,30,2025-06-02 08:35:00+00:00,8514605,E_COLI,957
...,...,...,...,...,...
4469,15,2025-06-10 06:09:00+00:00,8523502,INTTNLETRCCN,8449690
1924,15,2025-06-02 06:00:00+00:00,8516057,E_COLI,8452780
4197,15,2025-06-02 06:00:00+00:00,8516056,INTTNLETRCCN,8452780
2242,30,2025-06-10 07:26:57+00:00,8524779,E_COLI,8455040
4515,15,2025-06-10 07:26:57+00:00,8524790,INTTNLETRCCN,8455040

In [33]:
measure = measurements.pivot_table(values='numerieke_waarde', index='zwemwaterlocatie_id', columns='type_object_code')
measure

type_object_code     E_COLI  INTTNLETRCCN
zwemwaterlocatie_id
955                    60.0          60.0
956                    80.0         160.0
957                    30.0          20.0
959                    20.0          20.0
960                   270.0          20.0
...                     ...           ...
8435070                15.0          15.0
8439110                15.0          15.0
8449690                93.0          15.0
8452780                15.0          15.0
8455040                30.0          15.0

[734 rows x 2 columns]

In [34]:
data = data.merge(measure, on="zwemwaterlocatie_id", how="left")
data

,zwemwaterlocatie_id,address,adr_woonplaats,tekst,info_filename,website,korte_naam,naam,status,lat,lon,code,E_COLI,INTTNLETRCCN
0,1259,"Hoefsvenlaan, Waalwijk",Waalwijk,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,'T Hoefsven,'T Hoefsven,goed,51.6761,5.0942,1,180.0,46.0
1,1341,"Bosweg, Gasselte",Gasselte,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,'T Nije Hemelriek,'T Nije Hemelriek,goed,52.9725,6.7556,1,15.0,77.0
2,1315,"Holthesedijk, Overloon",Overloon,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,'T Schaartven,'T Schaartven,goed,51.5735,5.9749,1,15.0,15.0
3,1344,"Paralelleweg, Tynaarlo",Tynaarlo,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,'T Veenmeer,'T Veenmeer,goed,53.0829,6.6303,1,15.0,15.0
4,1291,"Witvenseweg, Veldhoven",Veldhoven,De zwemlocatie ligt ten zuiden van de gemeente...,NB-059-001 't Witven.jpg,http://www.witven.nl,Witven,'T Witven,goed,51.3979,5.4108,1,30.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,7941840,Kortgene,Kortgene,Door camping de Paardekreek aangelegd zandstra...,None,None,Paardekreek,strand Kortgene Paardekreek,goed,51.5496,3.8096,2,15.0,15.0
751,7356682,,,strand zoutkamp in onderzoek,None,None,None,strand zoutkamp,goed,53.3388,6.2973,1,NaN,NaN
752,6837320,"Elfenbank 1, Blauwe stad",Blauwe stad,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,strand zuid,strand zuid Oldambtmeer,goed,53.1651,7.0372,3,15.0,15.0
753,6997562,,,Strandje naast jachthaven van Brouwershaven,None,None,Brouwershaven,strandje Brouwershaven,goed,51.7315,3.9154,1,15.0,15.0
754,1240,"Oude Raadhuislaan 154, Rotterdam",Rotterdam,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,'t Zwarte Plasje,t Zwarte Plasje,goed,51.9593,4.4913,1,310.0,46.0

### Voorzieningen

In [35]:
zwemplek_voorziening = load_wfs_layer("zwr_public:zwemplek_voorziening")
zwemplek_voorziening

,id,aanvulling,code,groep,omschrijving,taal,key_id,voorziening_type_id,zwemplek_id,zwemwaterlocatie_id,geometry
0,zwemplek_voorziening.fid-4e6d9d79_1976962f2a2_...,EHBO post,5943900,ONBEPERKT,EHBO,nl,594394,5943900,1712,991,"POLYGON ((6.128 52.5405, 6.1282 52.5406, 6.129..."
1,zwemplek_voorziening.fid-4e6d9d79_1976962f2a2_...,None,5943900,ONBEPERKT,EHBO,None,594395,5943900,1834,1113,"POLYGON ((4.9111 52.8895, 4.9122 52.8892, 4.91..."
2,zwemplek_voorziening.fid-4e6d9d79_1976962f2a2_...,None,5943913,ONBEPERKT,Parkeergelegenheid,None,594396,5943913,1834,1113,"POLYGON ((4.9111 52.8895, 4.9122 52.8892, 4.91..."
3,zwemplek_voorziening.fid-4e6d9d79_1976962f2a2_...,None,5943906,ONBEPERKT,Horeca,None,594399,5943906,1834,1113,"POLYGON ((4.9111 52.8895, 4.9122 52.8892, 4.91..."
4,zwemplek_voorziening.fid-4e6d9d79_1976962f2a2_...,Blauwe Vlag,5943894,ONBEPERKT,Blauwe vlag,nl,594402,5943894,304213,29530,"POLYGON ((5.0644 51.6126, 5.0641 51.6123, 5.06..."
...,...,...,...,...,...,...,...,...,...,...,...
10810,zwemplek_voorziening.fid-4e6d9d79_1976983029e_...,2 drijflijnen,5943898,VEILIGHEID,Drijflijn,nl,600701,5943898,303128,1323,"POLYGON ((5.2454 51.705, 5.2457 51.7052, 5.245..."
10811,zwemplek_voorziening.fid-4e6d9d79_1976983029e_...,None,5943913,ONBEPERKT,Parkeergelegenheid,None,8463830,5943913,303128,1323,"POLYGON ((5.2454 51.705, 5.2457 51.7052, 5.245..."
10812,zwemplek_voorziening.fid-4e6d9d79_1976983029e_...,None,5943913,ONBEPERKT,Parkeergelegenheid,None,8463831,5943913,303129,1324,"POLYGON ((5.2426 51.7016, 5.2431 51.7015, 5.24..."
10813,zwemplek_voorziening.fid-4e6d9d79_1976983029e_...,Inclusief MIVA toilet,5943927,HYGIENE,WC / Toiletten,nl,8463832,5943927,303123,1284,"POLYGON ((5.3133 51.6748, 5.3159 51.6754, 5.31..."
10814,zwemplek_voorziening.fid-4e6d9d79_1976983029e_...,2 keer drijflijnen,5943898,VEILIGHEID,Drijflijn,nl,8463833,5943898,303123,1284,"POLYGON ((5.3133 51.6748, 5.3159 51.6754, 5.31..."

In [36]:
voorzieningen = zwemplek_voorziening.groupby('zwemwaterlocatie_id')['voorziening_type_id'].agg(list).reset_index()
voorzieningen

     zwemwaterlocatie_id                                voorziening_type_id
0                    955  [5943905, 5943906, 5943913, 5943913, 5943902, ...
1                    956  [5943905, 5943906, 5943913, 5943913, 5943902, ...
2                    957  [5943913, 5943930, 5943929, 5943907, 5943911, ...
3                    959  [5943913, 5943913, 5943902, 5943930, 5943929, ...
4                    960  [5943906, 5943913, 5943913, 5943902, 5943930, ...
..                   ...                                                ...
720              8194200  [5943891, 5943903, 5943892, 5943897, 5943927, ...
721              8428190  [5943916, 5943915, 5943929, 5943911, 5943927, ...
722              8435070  [5943892, 5943897, 5943915, 5943913, 5943907, ...
723              8439110  [5943913, 5943895, 5943929, 5943906, 5943921, ...
724              8452780  [5943892, 5943915, 5943913, 5943900, 5943907, ...

[725 rows x 2 columns]

In [37]:
data = data.merge(voorzieningen, on="zwemwaterlocatie_id", how="left")
data.rename(columns={
    "naam": "name",
    "korte_naam": "alternate_name",
    "adr_woonplaats": "placename",
    "status": "current_status",
    "tekst": "description",
    "info_filename": "photos",
    "code": "eu_designation",
    "E_COLI": "e_coli",
    "INTTNLETRCCN": "int_ent",
    "voorziening_type_id": "voorzieningen"
}, inplace=True)
data.set_index("zwemwaterlocatie_id", inplace=True)
data['name'] = data['name']\
    .str.strip()\
    .str.title()\
    .str.replace("^Rcn", "RCN", regex=True)\
    .str.replace("^T ", "'t ", regex=True)\
    .str.replace("['|`]T ", "'t ", regex=True)\
    .str.replace("['|`]S", "'s", regex=True)
data['alternate_name'] = data['alternate_name']\
    .str.strip()\
    .str.title()\
    .str.replace("^Rcn", "RCN", regex=True)\
    .str.replace("^T ", "'t ", regex=True)\
    .str.replace("['|`]T ", "'t ", regex=True)\
    .str.replace("['|`]S", "'s", regex=True)
data

,address,placename,description,photos,website,alternate_name,name,current_status,lat,lon,eu_designation,e_coli,int_ent,voorzieningen
zwemwaterlocatie_id,,,,,,,,,,,,,,
1259,"Hoefsvenlaan, Waalwijk",Waalwijk,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,'t Hoefsven,'t Hoefsven,goed,51.6761,5.0942,1,180.0,46.0,"[5943930, 5943929, 5943892, 5943907, 5943911, ..."
1341,"Bosweg, Gasselte",Gasselte,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,'t Nije Hemelriek,'t Nije Hemelriek,goed,52.9725,6.7556,1,15.0,77.0,"[5943906, 5943913, 5943902, 5943930, 5943929, ..."
1315,"Holthesedijk, Overloon",Overloon,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,'t Schaartven,'t Schaartven,goed,51.5735,5.9749,1,15.0,15.0,"[5943892, 5943916, 5943897, 5943900, 5943929, ..."
1344,"Paralelleweg, Tynaarlo",Tynaarlo,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,'t Veenmeer,'t Veenmeer,goed,53.0829,6.6303,1,15.0,15.0,"[5943901, 5943913, 5943906, 5943900, 5943902, ..."
1291,"Witvenseweg, Veldhoven",Veldhoven,De zwemlocatie ligt ten zuiden van de gemeente...,NB-059-001 't Witven.jpg,http://www.witven.nl,Witven,'t Witven,goed,51.3979,5.4108,1,30.0,15.0,"[5943902, 5943930, 5943929, 5943892, 5943927, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7941840,Kortgene,Kortgene,Door camping de Paardekreek aangelegd zandstra...,None,None,Paardekreek,Strand Kortgene Paardekreek,goed,51.5496,3.8096,2,15.0,15.0,NaN
7356682,,,strand zoutkamp in onderzoek,None,None,None,Strand Zoutkamp,goed,53.3388,6.2973,1,NaN,NaN,NaN
6837320,"Elfenbank 1, Blauwe stad",Blauwe stad,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,Strand Zuid,Strand Zuid Oldambtmeer,goed,53.1651,7.0372,3,15.0,15.0,"[5943927, 5943897, 5943892, 5943929, 5943916, ..."
6997562,,,Strandje naast jachthaven van Brouwershaven,None,None,Brouwershaven,Strandje Brouwershaven,goed,51.7315,3.9154,1,15.0,15.0,NaN
1240,"Oude Raadhuislaan 154, Rotterdam",Rotterdam,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,'t Zwarte Plasje,'t Zwarte Plasje,goed,51.9593,4.4913,1,310.0,46.0,"[5943929, 5943902, 5943930, 5943892, 5943927, ..."

### Waarschuwingen

In [38]:
preventative_measures = load_wfs_layer("zwr_public:zwemplek_maatregel")
preventative_measures = preventative_measures.drop(columns=['id', 'bw_code', 'object_type', 'toelichtingstandaardextended', 'type', 'geometry', 'zwemplek_naam'])
active_warnings = preventative_measures[(preventative_measures['objectbegintijd'] <= '2025-06-13')]
active_warnings = active_warnings.drop(columns=['redeningetrokken', 'objectbegintijd', 'objecteindtijd', 'omschrijving', 'key_id'])
active_warnings = active_warnings[[
    'zwemwaterlocatie_id', 'toelichtingstandaard', 'toelichtingpubliek']
]
active_warnings.set_index('zwemwaterlocatie_id', inplace=True)
active_warnings.rename(columns={
    'toelichtingstandaard': 'warning_type',
    'toelichtingpubliek': 'warning_description'
}, inplace=True)
active_warnings

,warning_type,warning_description
zwemwaterlocatie_id,,
6669260,VERBOD_KWALITEIT,Verboden te zwemmen in verband met een slechte...
1092,ONTRADEN_KWALITEIT,Deze zwemwaterlocatie is ingedeeld in de 4-jaa...
1366,ONTRADEN_KWALITEIT,Dit zwemseizoen (1 mei – 1 oktober) geldt voor...
1169,ONTRADEN_BLAUWALG,None
1408,WAARSCHUWING_BLAUWALG,None
...,...,...
1098,ONTRADEN_KWALITEIT,Deze zwemwaterlocatie is ingedeeld in de 4-jaa...
980,NORMOVERSCHRIJDING_GECONSTATEERD_WATERKWALITEIT,None
980,WAARSCHUWING_BLAUWALG,None
970,ONTRADEN_KWALITEIT,None
1123,ONTRADEN_KWALITEIT,None

In [39]:
warnings = active_warnings.groupby(['zwemwaterlocatie_id'])[['warning_type','warning_description']].apply(lambda x: x.to_dict('records')).reset_index(name='warnings')
warnings

    zwemwaterlocatie_id                                           warnings
0                   963  [{'warning_type': 'WAARSCHUWING_ZWEMMERSJEUK',...
1                   964  [{'warning_type': 'WAARSCHUWING_BLAUWALG', 'wa...
2                   970  [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
3                   971  [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
4                   972  [{'warning_type': 'WAARSCHUWING_BLAUWALG', 'wa...
..                  ...                                                ...
63              7176840  [{'warning_type': 'WAARSCHUWING_BLAUWALG', 'wa...
64              7346520  [{'warning_type': 'WAARSCHUWING_BLAUWALG', 'wa...
65              7716690  [{'warning_type': 'WAARSCHUWING_BLAUWALG', 'wa...
66              7961040  [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
67              8455040  [{'warning_type': 'WAARSCHUWING_ONVEILIGE_SITU...

[68 rows x 2 columns]

In [40]:
data = data.merge(warnings, on="zwemwaterlocatie_id", how="left")
data.rename(columns={
    "zwemwaterlocatie_id": "id",
    "voorzieningen": "amenities"
}, inplace=True)
data

,id,address,placename,description,photos,website,alternate_name,name,current_status,lat,lon,eu_designation,e_coli,int_ent,amenities,warnings
0,1259,"Hoefsvenlaan, Waalwijk",Waalwijk,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,'t Hoefsven,'t Hoefsven,goed,51.6761,5.0942,1,180.0,46.0,"[5943930, 5943929, 5943892, 5943907, 5943911, ...",NaN
1,1341,"Bosweg, Gasselte",Gasselte,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,'t Nije Hemelriek,'t Nije Hemelriek,goed,52.9725,6.7556,1,15.0,77.0,"[5943906, 5943913, 5943902, 5943930, 5943929, ...",NaN
2,1315,"Holthesedijk, Overloon",Overloon,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,'t Schaartven,'t Schaartven,goed,51.5735,5.9749,1,15.0,15.0,"[5943892, 5943916, 5943897, 5943900, 5943929, ...",NaN
3,1344,"Paralelleweg, Tynaarlo",Tynaarlo,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,'t Veenmeer,'t Veenmeer,goed,53.0829,6.6303,1,15.0,15.0,"[5943901, 5943913, 5943906, 5943900, 5943902, ...",NaN
4,1291,"Witvenseweg, Veldhoven",Veldhoven,De zwemlocatie ligt ten zuiden van de gemeente...,NB-059-001 't Witven.jpg,http://www.witven.nl,Witven,'t Witven,goed,51.3979,5.4108,1,30.0,15.0,"[5943902, 5943930, 5943929, 5943892, 5943927, ...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,7941840,Kortgene,Kortgene,Door camping de Paardekreek aangelegd zandstra...,None,None,Paardekreek,Strand Kortgene Paardekreek,goed,51.5496,3.8096,2,15.0,15.0,NaN,NaN
751,7356682,,,strand zoutkamp in onderzoek,None,None,None,Strand Zoutkamp,goed,53.3388,6.2973,1,NaN,NaN,NaN,NaN
752,6837320,"Elfenbank 1, Blauwe stad",Blauwe stad,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,Strand Zuid,Strand Zuid Oldambtmeer,goed,53.1651,7.0372,3,15.0,15.0,"[5943927, 5943897, 5943892, 5943929, 5943916, ...",NaN
753,6997562,,,Strandje naast jachthaven van Brouwershaven,None,None,Brouwershaven,Strandje Brouwershaven,goed,51.7315,3.9154,1,15.0,15.0,NaN,NaN
754,1240,"Oude Raadhuislaan 154, Rotterdam",Rotterdam,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,'t Zwarte Plasje,'t Zwarte Plasje,goed,51.9593,4.4913,1,310.0,46.0,"[5943929, 5943902, 5943930, 5943892, 5943927, ...",NaN

In [41]:
data['amenities'] = data['amenities'].apply(lambda x: set(x) if isinstance(x, (list, set, tuple)) else x)

In [42]:
data.to_json('../../api/nl/locations.json', orient="records")

In [43]:
import sqlite3

sql_data = data.copy()
sql_data["amenities"] = sql_data["amenities"].astype(str)
sql_data["warnings"] = sql_data["warnings"].astype(str)
db = sqlite3.connect('../dataset.sqlite3')
sql_data.to_sql('locations', db, index=False, if_exists='append')

755

In [44]:
data.columns

Index(['id', 'address', 'placename', 'description', 'photos', 'website',
       'alternate_name', 'name', 'current_status', 'lat', 'lon',
       'eu_designation', 'e_coli', 'int_ent', 'amenities', 'warnings'],
      dtype='object')

# GeoJSON

In [45]:
from geojson import Feature, Point, FeatureCollection, dumps

In [46]:
collection = []

In [47]:
for index, row in data.iterrows():
    print(row)
    feature = Feature(id=row['id'],
                      geometry=Point((row['lon'], row['lat'])),
                      properties={
        "name": row['name'],
        "alternate_name": row['alternate_name']
    })
    collection.append(feature)

id                                                             1259
address                                      Hoefsvenlaan, Waalwijk
placename                                                  Waalwijk
description       De locatie ligt ten zuidoosten van Waalwijk. E...
photos                                   NB-063-001 't Hoefsven.jpg
website                                                        None
alternate_name                                          't Hoefsven
name                                                    't Hoefsven
current_status                                                 goed
lat                                                         51.6761
lon                                                          5.0942
eu_designation                                                    1
e_coli                                                        180.0
int_ent                                                        46.0
amenities         {5943907, 5943911, 5943913, 5943916, 5943891, ...
warnings                                                        NaN
Name: 0, dtype: object
id                                                             1341
address                                            Bosweg, Gasselte
placename                                                  Gasselte
description       De zwemlocatie “’t Nije Hemelriek” is gelegen ...
photos                          Recreatiezone_'t_Nije_Hemelriek.jpg
website                                                        None
alternate_name                                    't Nije Hemelriek
name                                              't Nije Hemelriek
current_status                                                 goed
lat                                                         52.9725
lon                                                          6.7556
eu_designation                                                    1
e_coli                                                         15.0
int_ent                                                        77.0
amenities         {5943906, 5943907, 5943895, 5943911, 5943913, ...
warnings                                                        NaN
Name: 1, dtype: object
id                                                             1315
address                                      Holthesedijk, Overloon
placename                                                  Overloon
description       ‘t Schaartven is een voormalige zandwinplas, g...
photos                                                         None
website                                                        None
alternate_name                                        't Schaartven
name                                                  't Schaartven
current_status                                                 goed
lat                                                         51.5735
lon                                                          5.9749
eu_designation                                                    1
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943911, 5943916, 5943929, 5943892, 5943898, ...
warnings                                                        NaN
Name: 2, dtype: object
id                                                             1344
address                                      Paralelleweg, Tynaarlo
placename                                                  Tynaarlo
description       De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...
photos                                Recreatiezone_'t_Veenmeer.jpg
website                                                        None
alternate_name                                          't Veenmeer
name                                                    't Veenmeer
current_status                                                 goed
lat                                                         53.0829
lon                                                          6.6303
eu_designation                                                    1
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943906, 5943907, 5943895, 5943911, 5943913, ...
warnings                                                        NaN
Name: 3, dtype: object
id                                                             1291
address                                      Witvenseweg, Veldhoven
placename                                                 Veldhoven
description       De zwemlocatie ligt ten zuiden van de gemeente...
photos                                     NB-059-001 't Witven.jpg
website                                        http://www.witven.nl
alternate_name                                               Witven
name                                                      't Witven
current_status                                                 goed
lat                                                         51.3979
lon                                                          5.4108
eu_designation                                                    1
e_coli                                                         30.0
int_ent                                                        15.0
amenities         {5943907, 5943911, 5943915, 5943916, 5943917, ...
warnings                                                        NaN
Name: 4, dtype: object
id                                                 7350900
address                   Slag Vlugtenburg, 's-Gravenzande
placename                                   's-Gravenzande
description               Het badstrand van 's-Gravenzande
photos            01i_1_s-Gravenzande_slag_Vlugtenburg.jpg
website                                               None
alternate_name                              's-Gravenzande
name                                        's-Gravenzande
current_status                                        goed
lat                                                52.0126
lon                                                 4.1392
eu_designation                                           1
e_coli                                                30.0
int_ent                                               15.0
amenities                                              NaN
warnings                                               NaN
Name: 5, dtype: object
id                                                          6841460
address                                            Bosweg, Gasselte
placename                                                  Gasselte
description       De zwemlocatie “’t Gasselterveld” is gelegen i...
photos                                                         None
website                                                        None
alternate_name                                     't Gasselterveld
name                                               't Gasselterveld
current_status                                                 goed
lat                                                         52.9722
lon                                                          6.7498
eu_designation                                                    1
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943906, 5943907, 5943895, 5943911, 5943913, ...
warnings                                                        NaN
Name: 6, dtype: object
id                                                             1029
address                                     Hilgeloweg, Winterswijk
placename                                               Winterswijk
description       Recreatiegebied ‟t Hilgelo ligt aan de noordzi...
photos                            GLD-019-001_HILGELO_BORD 2024.jpg
website                                 http://www.leisurelands.nl/
alternate_name                                           't Hilgelo
name                                                     't Hilgelo
current_status                                                 goed
lat                                                         51.9936
lon                                                          6.7208
eu_designation                                                    1
e_coli                                                         61.0
int_ent                                                        15.0
amenities         {5943904, 5943906, 5943907, 5943911, 5943912, ...
warnings                                                        NaN
Name: 7, dtype: object
id                                                             1118
address                                      Havenstraat, Zijdewind
placename                                                 Zijdewind
description       Deze zwemwaterlocatie is ingedeeld in de 4-jaa...
photos                                                 't Petje.PNG
website                                                        None
alternate_name                                             't Petje
name                                                       't Petje
current_status                                  NEGATIEF_ZWEMADVIES
lat                                                         52.7392
lon                                                          4.8396
eu_designation                                                    4
e_coli                                                        332.0
int_ent                                                        46.0
amenities         {5943932, 5943906, 5943910, 5943913, 5943915, ...
warnings          [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
Name: 8, dtype: object
id                                                             1114
address                                    Skarpetweg, Oude Niedorp
placename                                              Oude Niedorp
description       Deze zwemwaterlocatie is ingedeeld in de 4-jaa...
photos                                               't Skarpet.PNG
website                                                        None
alternate_name                                           't Skarpet
name                                                     't Skarpet
current_status                                  NEGATIEF_ZWEMADVIES
lat                                                         52.7175
lon                                                          4.8725
eu_designation                                                    4
e_coli                                                         46.0
int_ent                                                        30.0
amenities         {5943932, 5943906, 5943907, 5943910, 5943911, ...
warnings          [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
Name: 9, dtype: object
id                                                             1143
address                                            Zeeweg, Overveen
placename                                                  Overveen
description       't Wed ligt in het nationale park Zuid-Kenneme...
photos                                                     tWed.PNG
website                                                        None
alternate_name                                               't Wed
name                                                         't Wed
current_status                                         WAARSCHUWING
lat                                                         52.3996
lon                                                          4.5898
eu_designation                                                    1
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943907, 5943891, 5943892, 5943930, 5943927, ...
warnings          [{'warning_type': 'WAARSCHUWING_ZWEMMERSJEUK',...
Name: 10, dtype: object
id                                                           299241
address                                  Maastrichtsebaan 1, Alphen
placename                                                    Alphen
description       Zwemplas 't Zand wordt omgeven door bosgebied....
photos                                       NB-002-001 't Zand.jpg
website                                                        None
alternate_name                                              't Zand
name                                                        't Zand
current_status                                                 goed
lat                                                         51.4993
lon                                                          4.9497
eu_designation                                                    1
e_coli                                                         15.0
int_ent                                                        77.0
amenities         {5943907, 5943911, 5943915, 5943916, 5943892, ...
warnings                                                        NaN
Name: 11, dtype: object
id                                                             1249
address                                         Fransebaan, 't Zand
placename                                                   't Zand
description                                        nog in te vullen
photos                                       NB-002-001 't Zand.jpg
website                                                        None
alternate_name                                              't Zand
name                                           't Zand Middenstrand
current_status                                                 goed
lat                                                         51.4997
lon                                                          4.9532
eu_designation                                                    1
e_coli                                                        220.0
int_ent                                                        61.0
amenities         {5943907, 5943911, 5943913, 5943919, 5943891, ...
warnings                                                        NaN
Name: 12, dtype: object
id                                                             1619
address                                Aakvlaaiweg, Geertruidenberg
placename                                           Geertruidenberg
description       De Aakvlaai is een 150 hectare groot waterspor...
photos                                      NB-014-002 Aakvlaai.jpg
website                                    https://www.biesbosch.nu
alternate_name                                  Aakvlaai, Badstrand
name                                            Aakvlaai, Badstrand
current_status                                  NEGATIEF_ZWEMADVIES
lat                                                         51.7236
lon                                                          4.8646
eu_designation                                                    1
e_coli                                                         15.0
int_ent                                                        15.0
amenities             {5943907, 5943911, 5943891, 5943892, 5943929}
warnings          [{'warning_type': 'ONTRADEN_ONVEILIGE_SITUATIE...
Name: 13, dtype: object
id                                                             1550
address                                    Drontermeerdijk, Dronten
placename                                                   Dronten
description       Het Abbertstrand ligt aan het Drontermeer tuss...
photos            DOCUVITP-#1332258-v1-12_067_Abbertstrand-1_pdf...
website                            https://www.atsea-restaurant.nl/
alternate_name                                         Abbertstrand
name                                                   Abbertstrand
current_status                                                 goed
lat                                                         52.5127
lon                                                          5.8547
eu_designation                                                    3
e_coli                                                        140.0
int_ent                                                        15.0
amenities         {5943907, 5943895, 5943911, 5943917, 5943921, ...
warnings                                                        NaN
Name: 14, dtype: object
id                                                              990
address                                     Agnietenbergweg, Zwolle
placename                                                    Zwolle
description       Aan de rand van Zwolle, aan de Haersterveerweg...
photos                         Informatiebord Agnietenplas Oost.png
website           https://www.zwolle.nl/vrije-tijd/sport/zwempla...
alternate_name                                    Agnietenplas Oost
name                                              Agnietenplas Oost
current_status                                                 goed
lat                                                         52.5407
lon                                                          6.1316
eu_designation                                                    3
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943907, 5943911, 5943891, 5943892, 5943930, ...
warnings                                                        NaN
Name: 15, dtype: object
id                                                              991
address                                     Agnietenbergweg, Zwolle
placename                                                    Zwolle
description       Aan de rand van Zwolle, aan de Haersterveerweg...
photos                         Informatiebord Agnietenplas West.png
website           https://www.zwolle.nl/vrije-tijd/sport/zwempla...
alternate_name                                    Agnietenplas West
name                                              Agnietenplas West
current_status                                                 goed
lat                                                         52.5405
lon                                                          6.1291
eu_designation                                                    2
e_coli                                                        245.0
int_ent                                                        15.0
amenities         {5943907, 5943911, 5943891, 5943892, 5943930, ...
warnings                                                        NaN
Name: 16, dtype: object
id                                                             1051
address                                  Klaas Hoornlaan, Akersloot
placename                                                 Akersloot
description       Even ten zuiden van Alkmaar ligt het Alkmaarde...
photos                                               NH-043-001.JPG
website                                                        None
alternate_name                                            Akersloot
name                                                      Akersloot
current_status                                                 goed
lat                                                         52.5593
lon                                                          4.7437
eu_designation                                                    2
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943907, 5943911, 5943913, 5943916, 5943892, ...
warnings                                                        NaN
Name: 17, dtype: object
id                                                              978
address                                       Stasjonsleane, Oudega

In [48]:
geojson = FeatureCollection(collection)

In [49]:
with open("../../api/nl/map.geojson", "w") as outputGeoJson:
    outputGeoJson.write(dumps(geojson))

In [50]:
from ipyleaflet import Map, Marker, GeoJSON
import random

center = (52.204793, 360.121558)

m = Map(center=center, zoom=15)

geo_json = GeoJSON(
    data=geojson,
    style={
        'color': 'black'
    }
)
m.layers = [m.layers[0], geo_json]
m

Map(center=[52.204793, 360.121558], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title'…

In [51]:
unique_amenities = zwemplek_voorziening.copy()
unique_amenities = unique_amenities.drop_duplicates("code").drop(columns=['id', 'taal', 'zwemplek_id', 'zwemwaterlocatie_id', 'geometry'])
unique_amenities = unique_amenities[['voorziening_type_id', 'omschrijving', 'groep']].set_index('voorziening_type_id')
unique_amenities.to_csv('../../api/nl/amenities.csv')