In [2]:
import geopandas as gpd
from requests import Request
from owslib.wfs import WebFeatureService

In [3]:
url = "https://pubgeo.zwemwater.nl/geoserver/zwr_public/wfs"
wfs = WebFeatureService(url=url)

In [4]:
def load_wfs_layer(layer_name):
    params = dict(service='WFS', version="2.0.0", request='GetFeature',
      typeName=layer_name, outputFormat='json', srsName="EPSG:4326")
    wfs_request_url = Request('GET', url, params=params).prepare().url
    return gpd.read_file(wfs_request_url)

# Data

### Zwemplekken

In [5]:
zwemplekken = load_wfs_layer("zwr_public:zwemplekken")
zwemplekken = zwemplekken.drop(columns=['id', 'datum']).set_index('key_id')
zwemplekken

,korte_naam,naam,status,zwemwaterlocatie_id,geometry
key_id,,,,,
6187300,Voorveldse Polder,Voorveldse Polder,NEGATIEF_ZWEMADVIES,1185,POINT (5.1522 52.1005)
2316,'t Kleine Zeetje,Recreatiepark 't Kleine Zeetje,NEGATIEF_ZWEMADVIES,1595,POINT (5.3762 52.2602)
1954,Plas Vrijenburgbos,Plas Vrijenburgbos,NEGATIEF_ZWEMADVIES,1233,POINT (4.5003 51.868)
1962,Kralinger Esch,Kralinger Esch,NEGATIEF_ZWEMADVIES,1241,POINT (4.5253 51.9138)
2307,De Oude Pol,De Oude Pol,NEGATIEF_ZWEMADVIES,1586,POINT (5.7259 52.3925)
...,...,...,...,...,...
8184931,De Stronk,Bussloo De Stronk,goed,8184901,POINT (6.1098 52.2034)
8184932,'t Gorsselaar,Bussloo 't Gorsselaar,goed,8184902,POINT (6.0963 52.2021)
8184934,De Kuiter,Bussloo De Kuiter (Naturistenstrand),goed,8184903,POINT (6.0998 52.1959)
8186500,Aquapark,Kempervennen Aquapark,goed,8186460,POINT (5.4247 51.3272)
8194230,Badstrand Ballum,"Badstrand Ballum, Ameland",goed,8194200,POINT (5.6959 53.4642)

In [6]:
zwemplekken_details = load_wfs_layer("zwr_public:zwemplekken_details")
zwemplekken_details = zwemplekken_details.drop(columns=["id", "info_id", "geometry", "datum"])
zwemplekken_details

,adr_huisletter,adr_huisnummer,adr_huisnummertoevoeging,adr_postcode,adr_straat,adr_woonplaats,info_filename,info_length,info_mime_type,key_id,...,org_straat,org_telefoon,org_website,org_woonplaats,status,taal,tekst,toegang,website,zwemwaterlocatie_id
0,None,NaN,None,None,De Dreef,Heerenveen,FR-043-001 De Heide.jpg,356023.0,image/jpeg,1676,...,,0513-617 617,http://www.heerenveen.nl,Heerenveen,goed,nl,"Het recreatiegebied “De Heide”, ligt aan de zu...",OPENBAAR ONBETAALD,None,955
1,,NaN,,None,Spokedam,Noordwolde,FR-046-001 Spoekeplas.jpg,297473.0,image/pjpeg,1677,...,,050 707 4444,http://www.staatsbosbeheer.nl,Groningen,goed,nl,Het zwemwater Spoekeplas ligt ten zuidwesten v...,OPENBAAR ONBETAALD,None,956
2,None,NaN,None,None,Canada,Appelscha,Canadameer Appelscha.png,212248.0,image/png,1678,...,,050 707 4444,http://www.staatsbosbeheer.nl,Groningen,goed,nl,Het Canadameer (ook wel Aekingermeer genoemd) ...,OPENBAAR ONBETAALD,None,957
3,None,NaN,None,None,Kleasterkampen,Smalle Ee,FR-028-001 Smeliester SaÌ‚n.jpg,210638.0,image/pjpeg,1680,...,,0512-581234,http://www.smallingerland.nl,Drachten,goed,nl,Het zwemwater ligt aan de zuidzijde van het ge...,OPENBAAR ONBETAALD,None,959
4,None,NaN,None,None,Bildreed,Rottevalle,FR-027-001 De Leien.jpg,209646.0,image/pjpeg,1681,...,,050 707 4444,http://www.staatsbosbeheer.nl,Groningen,NEGATIEF_ZWEMADVIES,nl,Het zwemwater ligt enkele kilometers ten noord...,OPENBAAR ONBETAALD,None,960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953,None,NaN,None,None,Kneuterstraat,Wilp,GLD-004-007 BUSSLOO GORSSELAAR 2020.jpg,2995096.0,image/jpeg,8184932,...,Westervoortsedijk 73-LB,026-3848800,http://www.leisurelands.nl,Arnhem,goed,nl,De recreatieplas Bussloo ligt temidden van de ...,Openbaar betaald parkeren voor auto's,http://www.leisurelands.nl/,8184902
954,None,NaN,None,None,Bloemenksweg,Wilp,GLD-004-013 BUSSLOO DE KUITER 2020.jpg,2981855.0,image/jpeg,8184934,...,Westervoortsedijk 73-LB,026-3848800,http://www.leisurelands.nl,Arnhem,goed,nl,De recreatieplas Bussloo ligt temidden van de ...,"Openbaar, betaald parkeren voor auto's",http://www.leisurelands.nl/,8184903
955,None,8.0,None,5563VB,Kempervennendreef,Westerhoven,None,NaN,None,8186500,...,Bosscheweg,(0411) 618 618,http://www.dommel.nl/,Boxtel,goed,nl,zwemlocatie Aquapark is ingericht als een drij...,Openbaar toegankelijk via kaartjesverkoop,None,8186460
956,None,35.0,None,3263RA,Randweg,Oud-Beijerland,None,NaN,None,8192100,...,Sportlaan,088-6473647,https://www.gemeentehw.nl/,Maasdam,NEGATIEF_ZWEMADVIES,nl,De zwemlocatie heeft een zwembaai gelegen aan ...,None,None,8192060
957,None,NaN,None,None,None,Ballum,None,NaN,None,8194230,...,None,0519-555555,http://www.ameland.nl,Ameland,goed,nl,Zwemlocatie Badstrand Ballum is een zwemlocati...,None,None,8194200

In [7]:
zwemplekken_details.columns

Index(['adr_huisletter', 'adr_huisnummer', 'adr_huisnummertoevoeging',
       'adr_postcode', 'adr_straat', 'adr_woonplaats', 'info_filename',
       'info_length', 'info_mime_type', 'key_id', 'korte_naam', 'naam',
       'objecttype', 'org_bedrijfsnaam', 'org_email', 'org_fax',
       'org_huisletter', 'org_huisnumeer', 'org_huisnummertoevoeging',
       'org_id', 'org_postcode', 'org_straat', 'org_telefoon', 'org_website',
       'org_woonplaats', 'status', 'taal', 'tekst', 'toegang', 'website',
       'zwemwaterlocatie_id'],
      dtype='object')

In [8]:
photos = load_wfs_layer("zwr_public:locatiefotos")
photos

,id,filename,key_id,length,mime_type,zwemplek_id,geometry
0,locatiefotos.fid-6d4f78c4_191efb3e912_34dd,testgegevens.csv,559072,23483,application/vnd.ms-excel,NaN,None
1,locatiefotos.fid-6d4f78c4_191efb3e912_34de,2024-09-11 DE NESWAARDEN TE AALST.docx,8385643,22953,application/vnd.openxmlformats-officedocument....,NaN,None
2,locatiefotos.fid-6d4f78c4_191efb3e912_34df,Oostmahorn Lauwersmeer 9 september 2024.pdf,8385644,200043,application/pdf,NaN,None
3,locatiefotos.fid-6d4f78c4_191efb3e912_34e0,18-07-2012.jpg,559074,18482,image/pjpeg,1762.0,"POLYGON ((5.9978 52.311, 5.998 52.3109, 6.0003..."
4,locatiefotos.fid-6d4f78c4_191efb3e912_34e1,FR-005-001 Badstrand Nes.jpg,1092,327074,image/pjpeg,NaN,None
...,...,...,...,...,...,...,...
5905,locatiefotos.fid-6d4f78c4_191efb3e912_4bee,Er geldt een nader onderzoek i.docx,8382596,12384,application/vnd.openxmlformats-officedocument....,NaN,None
5906,locatiefotos.fid-6d4f78c4_191efb3e912_4bef,Beekse Bergen zone 1 waarschuwing blauwalgen.docx,8382597,25488,application/vnd.openxmlformats-officedocument....,NaN,None
5907,locatiefotos.fid-6d4f78c4_191efb3e912_4bf0,20240910 spuien katwijk noord en zuid.docx,8385640,21736,application/vnd.openxmlformats-officedocument....,NaN,None
5908,locatiefotos.fid-6d4f78c4_191efb3e912_4bf1,20240910 spuien katwijk noord en zuid.docx,8385641,21736,application/vnd.openxmlformats-officedocument....,NaN,None
5909,locatiefotos.fid-6d4f78c4_191efb3e912_4bf2,20240911 overstort Oude tol.docx,8385642,22832,application/vnd.openxmlformats-officedocument....,NaN,None

In [9]:
photos["mime_type"].unique()

array(['application/vnd.ms-excel',
       'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
       'application/pdf', 'image/pjpeg', 'image/jpeg', 'image/png',
       'application/vnd.adobe.pdx', 'application/octet-stream',
       'application/msword',
       'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
       'text/plain', 'ds/document', 'text/html'], dtype=object)

In [10]:
photos = photos[
    photos['mime_type'].isin([
        'image/pjpeg', 
        'image/jpeg',
        'image/png'
    ])
]
photos

,id,filename,key_id,length,mime_type,zwemplek_id,geometry
3,locatiefotos.fid-6d4f78c4_191efb3e912_34e0,18-07-2012.jpg,559074,18482,image/pjpeg,1762.0,"POLYGON ((5.9978 52.311, 5.998 52.3109, 6.0003..."
4,locatiefotos.fid-6d4f78c4_191efb3e912_34e1,FR-005-001 Badstrand Nes.jpg,1092,327074,image/pjpeg,NaN,None
5,locatiefotos.fid-6d4f78c4_191efb3e912_34e2,FR-004-001 Badstrand Hollum.jpg,1091,280508,image/pjpeg,NaN,None
6,locatiefotos.fid-6d4f78c4_191efb3e912_34e3,FR-009-001 De Vleyen.jpg,1093,271129,image/pjpeg,NaN,None
7,locatiefotos.fid-6d4f78c4_191efb3e912_34e4,FR-006-001 Badstrand Buren.jpg,1094,299640,image/pjpeg,NaN,None
...,...,...,...,...,...,...,...
5799,locatiefotos.fid-6d4f78c4_191efb3e912_4b84,20240718_132622.jpg,8314632,8902420,image/jpeg,NaN,None
5824,locatiefotos.fid-6d4f78c4_191efb3e912_4b9d,IMG-20240803-WA0000.jpg,8334760,345646,image/jpeg,NaN,None
5848,locatiefotos.fid-6d4f78c4_191efb3e912_4bb5,20240817_113954000_iOS.jpg,8356820,1774739,image/jpeg,NaN,None
5849,locatiefotos.fid-6d4f78c4_191efb3e912_4bb6,20240819_094333000_iOS.jpg,8356821,440823,image/jpeg,NaN,None
5876,locatiefotos.fid-6d4f78c4_191efb3e912_4bd1,IMG_1412.JPG,8370661,2497182,image/jpeg,NaN,None

In [11]:
photos = photos.query("zwemplek_id.notnull()")
photodata = photos[['zwemplek_id', 'key_id', 'filename']].copy()
photodata['zwemplek_id'] = photodata['zwemplek_id'].astype(int)
photodata['key_id'] = "https://register.zwemwater.nl/zwr/api/files/" + photodata['key_id'].astype(str)
for item in photodata.query('zwemplek_id == 6187300').iterrows():
    print(item)

(4010, zwemplek_id                                              6187300
key_id         https://register.zwemwater.nl/zwr/api/files/61...
filename                            WP_20170413_12_40_27_Pro.jpg
Name: 4010, dtype: object)
(4011, zwemplek_id                                              6187300
key_id         https://register.zwemwater.nl/zwr/api/files/61...
filename                         2019 IMG_20190629_101301032.jpg
Name: 4011, dtype: object)
(4012, zwemplek_id                                              6187300
key_id         https://register.zwemwater.nl/zwr/api/files/61...
filename        2017 Overzichtsfoto WP_20170413_12_42_21_Pro.jpg
Name: 4012, dtype: object)

In [12]:
base_data = zwemplekken_details.copy()
base_data = base_data[["zwemwaterlocatie_id", "naam", "korte_naam", "adr_woonplaats", "status", "tekst", "info_filename", "website"]]
base_data

,zwemwaterlocatie_id,naam,korte_naam,adr_woonplaats,status,tekst,info_filename,website
0,955,De Heide,Heide,Heerenveen,goed,"Het recreatiegebied “De Heide”, ligt aan de zu...",FR-043-001 De Heide.jpg,None
1,956,Spoekeplas,Spoekeplas,Noordwolde,goed,Het zwemwater Spoekeplas ligt ten zuidwesten v...,FR-046-001 Spoekeplas.jpg,None
2,957,Canadameer,Canadameer,Appelscha,goed,Het Canadameer (ook wel Aekingermeer genoemd) ...,Canadameer Appelscha.png,None
3,959,Smeliester Sân,Smeliester Sân,Smalle Ee,goed,Het zwemwater ligt aan de zuidzijde van het ge...,FR-028-001 Smeliester SaÌ‚n.jpg,None
4,960,De Leien,De Leien,Rottevalle,NEGATIEF_ZWEMADVIES,Het zwemwater ligt enkele kilometers ten noord...,FR-027-001 De Leien.jpg,None
...,...,...,...,...,...,...,...,...
953,8184902,Bussloo 't Gorsselaar,'t Gorsselaar,Wilp,goed,De recreatieplas Bussloo ligt temidden van de ...,GLD-004-007 BUSSLOO GORSSELAAR 2020.jpg,http://www.leisurelands.nl/
954,8184903,Bussloo De Kuiter (Naturistenstrand),De Kuiter,Wilp,goed,De recreatieplas Bussloo ligt temidden van de ...,GLD-004-013 BUSSLOO DE KUITER 2020.jpg,http://www.leisurelands.nl/
955,8186460,Kempervennen Aquapark,Aquapark,Westerhoven,goed,zwemlocatie Aquapark is ingericht als een drij...,None,None
956,8192060,Oude Tol,Oude Tol,Oud-Beijerland,NEGATIEF_ZWEMADVIES,De zwemlocatie heeft een zwembaai gelegen aan ...,None,None
957,8194200,"Badstrand Ballum, Ameland",Badstrand Ballum,Ballum,goed,Zwemlocatie Badstrand Ballum is een zwemlocati...,None,None

In [13]:
zwemplekdata = zwemplekken.merge(base_data, left_on="zwemwaterlocatie_id", right_on="zwemwaterlocatie_id", how="left")
zwemplekdata['lat'] = zwemplekdata['geometry'].y
zwemplekdata['lon'] = zwemplekdata['geometry'].x
zwemplekdata = zwemplekdata.drop(columns=["korte_naam_x", "naam_x", "status_x", "geometry"])
zwemplekdata = zwemplekdata.rename(columns={
    "naam_y": "naam",
    "korte_naam_y": "korte_naam",
    "status_y": "status"
})
zwemplekdata.sort_values(by=["naam"], inplace=True)
zwemplekdata

,zwemwaterlocatie_id,naam,korte_naam,adr_woonplaats,status,tekst,info_filename,website,lat,lon
1635,1323,Engelermeer Oost,Engelermeer Oost,'s-Hertogenbosch,goed,Het Engelermeer is een serie kunstmatige plass...,NB-031-001 Engelermeer Oost.jpg,None,51.7046,5.2461
1614,1259,'T Hoefsven,'T Hoefsven,Waalwijk,goed,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,51.6761,5.0942
572,1341,'T Nije Hemelriek,'T Nije Hemelriek,Gasselte,goed,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,52.9725,6.7556
1643,1315,'T Schaartven,'T Schaartven,Overloon,goed,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,51.5735,5.9749
575,1344,'T Veenmeer,'T Veenmeer,Tynaarlo,goed,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,53.0829,6.6303
...,...,...,...,...,...,...,...,...,...,...
375,7941840,strand Kortgene Paardekreek,Paardekreek,Kortgene,NEGATIEF_ZWEMADVIES,Door camping de Paardekreek aangelegd zandstra...,None,None,51.5496,3.8096
1964,7356682,strand zoutkamp,None,None,goed,strand zoutkamp in onderzoek,None,None,53.3388,6.2973
1938,6837320,strand zuid Oldambtmeer,strand zuid,Blauwe stad,goed,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,53.1651,7.0372
1937,6997562,strandje Brouwershaven,Brouwershaven,None,goed,Strandje naast jachthaven van Brouwershaven,None,None,51.7315,3.9154
534,1240,t Zwarte Plasje,'t Zwarte Plasje,Rotterdam,goed,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,51.9593,4.4913

### EU statussen

In [14]:
eu_designations = load_wfs_layer("zwr_public:eustatussen")
eu_designations = eu_designations[eu_designations['jaar'] == 2023].drop(columns=['type_eu_status_id', 'geometry', 'omschrijving', 'id'])
eu_designations

     code   key_id  jaar  zwemwaterlocatie_id
7010    1  8135490  2023                 1267
7011    1  8135491  2023                 1268
7012    1  8135492  2023                 1270
7013    1  8135493  2023                 1271
7014    1  8135494  2023                 1273
...   ...      ...   ...                  ...
7751    4  8167548  2023                 1112
7752    4  8167553  2023                 1118
7753    3  8167559  2023                 1124
7754    4  8167555  2023                 1120
7755    4  8167550  2023                 1114

[731 rows x 4 columns]

In [15]:
eu_current_designations = eu_designations.query("jaar == 2023")
eu_current_designations = eu_current_designations.drop(columns=["key_id", "jaar"])
eu_current_designations
data = zwemplekdata.merge(eu_current_designations, left_on="zwemwaterlocatie_id", right_on="zwemwaterlocatie_id", how="left")
data.fillna({'code': 0}, inplace=True)
data

,zwemwaterlocatie_id,naam,korte_naam,adr_woonplaats,status,tekst,info_filename,website,lat,lon,code
0,1323,Engelermeer Oost,Engelermeer Oost,'s-Hertogenbosch,goed,Het Engelermeer is een serie kunstmatige plass...,NB-031-001 Engelermeer Oost.jpg,None,51.7046,5.2461,1
1,1259,'T Hoefsven,'T Hoefsven,Waalwijk,goed,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,51.6761,5.0942,1
2,1341,'T Nije Hemelriek,'T Nije Hemelriek,Gasselte,goed,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,52.9725,6.7556,1
3,1315,'T Schaartven,'T Schaartven,Overloon,goed,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,51.5735,5.9749,1
4,1344,'T Veenmeer,'T Veenmeer,Tynaarlo,goed,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,53.0829,6.6303,1
...,...,...,...,...,...,...,...,...,...,...,...
2473,7941840,strand Kortgene Paardekreek,Paardekreek,Kortgene,NEGATIEF_ZWEMADVIES,Door camping de Paardekreek aangelegd zandstra...,None,None,51.5496,3.8096,1
2474,7356682,strand zoutkamp,None,None,goed,strand zoutkamp in onderzoek,None,None,53.3388,6.2973,1
2475,6837320,strand zuid Oldambtmeer,strand zuid,Blauwe stad,goed,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,53.1651,7.0372,2
2476,6997562,strandje Brouwershaven,Brouwershaven,None,goed,Strandje naast jachthaven van Brouwershaven,None,None,51.7315,3.9154,1
2477,1240,t Zwarte Plasje,'t Zwarte Plasje,Rotterdam,goed,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,51.9593,4.4913,1

### Metingen

In [16]:
measurements = load_wfs_layer("zwr_public:resultaatsen")
measurements = measurements.drop(columns=['id', 'datum_geplande_monstername', 'monitoring_datum_id', 'monitoring_plan_id', 'monster_id', 'type_object_id', 'geometry'])
measurements = measurements.sort_values(["zwemwaterlocatie_id", "object_begin_tijd", "type_object_code"])
measurements = measurements.drop_duplicates(subset=["zwemwaterlocatie_id", "type_object_code"], keep="last")
measurements

,numerieke_waarde,object_begin_tijd,key_id,type_object_code,zwemwaterlocatie_id
5956,20,2024-09-02 10:16:00+00:00,8377349,E_COLI,955
12520,15,2024-09-02 10:16:00+00:00,8377360,INTTNLETRCCN,955
6216,30,2024-09-09 09:42:00+00:00,8386110,E_COLI,956
12779,15,2024-09-09 09:42:00+00:00,8386111,INTTNLETRCCN,956
6217,20,2024-09-09 10:17:00+00:00,8386132,E_COLI,957
...,...,...,...,...,...
12591,15,2024-09-03 09:20:00+00:00,8380148,INTTNLETRCCN,8186460
6554,45,2024-09-10 11:21:00+00:00,8392354,E_COLI,8192060
13114,93,2024-09-10 11:21:00+00:00,8392356,INTTNLETRCCN,8192060
6232,30,2024-09-09 06:30:00+00:00,8387735,E_COLI,8194200
12795,20,2024-09-09 06:30:00+00:00,8387734,INTTNLETRCCN,8194200

In [17]:
measure = measurements.pivot_table(values='numerieke_waarde', index='zwemwaterlocatie_id', columns='type_object_code')
measure

type_object_code     E_COLI  INTTNLETRCCN
zwemwaterlocatie_id
955                    20.0          15.0
956                    30.0          15.0
957                    20.0          15.0
959                    80.0          15.0
960                   200.0          60.0
...                     ...           ...
8184902                61.0          30.0
8184903               253.0          61.0
8186460                61.0          15.0
8192060                45.0          93.0
8194200                30.0          20.0

[749 rows x 2 columns]

In [18]:
data = data.merge(measure, on="zwemwaterlocatie_id", how="left")
data

,zwemwaterlocatie_id,naam,korte_naam,adr_woonplaats,status,tekst,info_filename,website,lat,lon,code,E_COLI,INTTNLETRCCN
0,1323,Engelermeer Oost,Engelermeer Oost,'s-Hertogenbosch,goed,Het Engelermeer is een serie kunstmatige plass...,NB-031-001 Engelermeer Oost.jpg,None,51.7046,5.2461,1,46.0,46.0
1,1259,'T Hoefsven,'T Hoefsven,Waalwijk,goed,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,51.6761,5.0942,1,77.0,46.0
2,1341,'T Nije Hemelriek,'T Nije Hemelriek,Gasselte,goed,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,52.9725,6.7556,1,15.0,15.0
3,1315,'T Schaartven,'T Schaartven,Overloon,goed,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,51.5735,5.9749,1,15.0,15.0
4,1344,'T Veenmeer,'T Veenmeer,Tynaarlo,goed,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,53.0829,6.6303,1,15.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,7941840,strand Kortgene Paardekreek,Paardekreek,Kortgene,NEGATIEF_ZWEMADVIES,Door camping de Paardekreek aangelegd zandstra...,None,None,51.5496,3.8096,1,8329.0,11636.0
2474,7356682,strand zoutkamp,None,None,goed,strand zoutkamp in onderzoek,None,None,53.3388,6.2973,1,61.0,15.0
2475,6837320,strand zuid Oldambtmeer,strand zuid,Blauwe stad,goed,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,53.1651,7.0372,2,461.0,161.0
2476,6997562,strandje Brouwershaven,Brouwershaven,None,goed,Strandje naast jachthaven van Brouwershaven,None,None,51.7315,3.9154,1,30.0,15.0
2477,1240,t Zwarte Plasje,'t Zwarte Plasje,Rotterdam,goed,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,51.9593,4.4913,1,30.0,15.0

### Voorzieningen

In [19]:
zwemplek_voorziening = load_wfs_layer("zwr_public:zwemplek_voorziening")
zwemplek_voorziening

,id,aanvulling,code,groep,omschrijving,taal,key_id,voorziening_type_id,zwemplek_id,zwemwaterlocatie_id,geometry
0,zwemplek_voorziening.fid--7a812bbb_191efd16c47...,None,5943913,ONBEPERKT,Parkeergelegenheid,None,594756,5943913,1709,988,"POLYGON ((6.0198 52.8794, 6.0204 52.8795, 6.02..."
1,zwemplek_voorziening.fid--7a812bbb_191efd16c47...,EHBO post,5943900,ONBEPERKT,EHBO,nl,594394,5943900,1712,991,"POLYGON ((6.128 52.5405, 6.1282 52.5406, 6.129..."
2,zwemplek_voorziening.fid--7a812bbb_191efd16c47...,None,5943906,ONBEPERKT,Horeca,None,595410,5943906,184348,1496,"POLYGON ((3.5334 51.5801, 3.5368 51.5814, 3.53..."
3,zwemplek_voorziening.fid--7a812bbb_191efd16c47...,None,5943900,ONBEPERKT,EHBO,None,594395,5943900,1834,1113,"POLYGON ((4.9111 52.8895, 4.9122 52.8892, 4.91..."
4,zwemplek_voorziening.fid--7a812bbb_191efd16c47...,None,5943913,ONBEPERKT,Parkeergelegenheid,None,594396,5943913,1834,1113,"POLYGON ((4.9111 52.8895, 4.9122 52.8892, 4.91..."
...,...,...,...,...,...,...,...,...,...,...,...
10991,zwemplek_voorziening.fid--7a812bbb_191efd16c47...,None,5943929,RECREATIE,Zandstrand,None,8200653,5943929,7714058,1675,"POLYGON ((4.5976 52.5286, 4.5986 52.5285, 4.59..."
10992,zwemplek_voorziening.fid--7a812bbb_191efd16c47...,None,5943929,RECREATIE,Zandstrand,None,8200654,5943929,2396,1675,"POLYGON ((4.5958 52.5236, 4.5957 52.5231, 4.59..."
10993,zwemplek_voorziening.fid--7a812bbb_191efd16c47...,None,5943929,RECREATIE,Zandstrand,None,8200655,5943929,7714057,1675,"POLYGON ((4.5863 52.4989, 4.5876 52.4986, 4.58..."
10994,zwemplek_voorziening.fid--7a812bbb_191efd16c47...,None,5943907,GENERIEK,Infobord,None,8273310,5943907,8011970,1115,"POLYGON ((4.7642 52.6814, 4.7641 52.681, 4.764..."
10995,zwemplek_voorziening.fid--7a812bbb_191efd16c47...,None,5943906,ONBEPERKT,Horeca,None,8273311,5943906,8011970,1115,"POLYGON ((4.7642 52.6814, 4.7641 52.681, 4.764..."

In [20]:
voorzieningen = zwemplek_voorziening.groupby('zwemwaterlocatie_id')['voorziening_type_id'].agg(list).reset_index()
voorzieningen

     zwemwaterlocatie_id                                voorziening_type_id
0                    955  [5943905, 5943906, 5943913, 5943913, 5943902, ...
1                    956  [5943905, 5943906, 5943913, 5943913, 5943902, ...
2                    957  [5943913, 5943930, 5943929, 5943907, 5943911, ...
3                    959  [5943913, 5943913, 5943902, 5943930, 5943929, ...
4                    960  [5943906, 5943913, 5943913, 5943902, 5943930, ...
..                   ...                                                ...
714              8184901  [5943891, 5943892, 5943916, 5943907, 5943929, ...
715              8184902  [5943892, 5943916, 5943913, 5943907, 5943929, ...
716              8184903  [5943891, 5943898, 5943892, 5943916, 5943913, ...
717              8186460      [5943928, 5943892, 5943915, 5943908, 5943917]
718              8194200  [5943891, 5943903, 5943892, 5943897, 5943927, ...

[719 rows x 2 columns]

In [21]:
data = data.merge(voorzieningen, on="zwemwaterlocatie_id", how="left")
data.rename(columns={
    "naam": "name",
    "korte_naam": "alternate_name",
    "adr_woonplaats": "placename",
    "status": "current_status",
    "tekst": "description",
    "info_filename": "photos",
    "code": "eu_designation",
    "E_COLI": "e_coli",
    "INTTNLETRCCN": "int_ent",
    "voorziening_type_id": "voorzieningen"
}, inplace=True)
data.set_index("zwemwaterlocatie_id", inplace=True)
data['name'] = data['name']\
    .str.strip()\
    .str.title()\
    .str.replace("^Rcn", "RCN", regex=True)\
    .str.replace("^T ", "'t ", regex=True)\
    .str.replace("['|`]T ", "'t ", regex=True)\
    .str.replace("['|`]S", "'s", regex=True)
data['alternate_name'] = data['alternate_name']\
    .str.strip()\
    .str.title()\
    .str.replace("^Rcn", "RCN", regex=True)\
    .str.replace("^T ", "'t ", regex=True)\
    .str.replace("['|`]T ", "'t ", regex=True)\
    .str.replace("['|`]S", "'s", regex=True)
data

,name,alternate_name,placename,current_status,description,photos,website,lat,lon,eu_designation,e_coli,int_ent,voorzieningen
zwemwaterlocatie_id,,,,,,,,,,,,,
1323,Engelermeer Oost,Engelermeer Oost,'s-Hertogenbosch,goed,Het Engelermeer is een serie kunstmatige plass...,NB-031-001 Engelermeer Oost.jpg,None,51.7046,5.2461,1,46.0,46.0,"[5943902, 5943930, 5943929, 5943896, 5943923, ..."
1259,'t Hoefsven,'t Hoefsven,Waalwijk,goed,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,51.6761,5.0942,1,77.0,46.0,"[5943930, 5943929, 5943892, 5943907, 5943911, ..."
1341,'t Nije Hemelriek,'t Nije Hemelriek,Gasselte,goed,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,52.9725,6.7556,1,15.0,15.0,"[5943906, 5943913, 5943902, 5943930, 5943929, ..."
1315,'t Schaartven,'t Schaartven,Overloon,goed,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,51.5735,5.9749,1,15.0,15.0,"[5943892, 5943916, 5943897, 5943900, 5943929, ..."
1344,'t Veenmeer,'t Veenmeer,Tynaarlo,goed,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,53.0829,6.6303,1,15.0,15.0,"[5943901, 5943913, 5943906, 5943900, 5943892, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7941840,Strand Kortgene Paardekreek,Paardekreek,Kortgene,NEGATIEF_ZWEMADVIES,Door camping de Paardekreek aangelegd zandstra...,None,None,51.5496,3.8096,1,8329.0,11636.0,NaN
7356682,Strand Zoutkamp,None,None,goed,strand zoutkamp in onderzoek,None,None,53.3388,6.2973,1,61.0,15.0,NaN
6837320,Strand Zuid Oldambtmeer,Strand Zuid,Blauwe stad,goed,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,53.1651,7.0372,2,461.0,161.0,"[5943927, 5943897, 5943892, 5943929, 5943916, ..."
6997562,Strandje Brouwershaven,Brouwershaven,None,goed,Strandje naast jachthaven van Brouwershaven,None,None,51.7315,3.9154,1,30.0,15.0,NaN
1240,'t Zwarte Plasje,'t Zwarte Plasje,Rotterdam,goed,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,51.9593,4.4913,1,30.0,15.0,"[5943929, 5943902, 5943930, 5943892, 5943927, ..."

### Waarschuwingen

In [22]:
preventative_measures = load_wfs_layer("zwr_public:zwemplek_maatregel")
preventative_measures = preventative_measures.drop(columns=['id', 'bw_code', 'object_type', 'toelichtingstandaardextended', 'type', 'geometry', 'zwemplek_naam'])
active_warnings = preventative_measures[(preventative_measures['objectbegintijd'] <= '2024-08-02')]
active_warnings = active_warnings.drop(columns=['redeningetrokken', 'objectbegintijd', 'objecteindtijd', 'omschrijving', 'key_id'])
active_warnings = active_warnings[[
    'zwemwaterlocatie_id', 'toelichtingstandaard', 'toelichtingpubliek']
]
active_warnings.set_index('zwemwaterlocatie_id', inplace=True)
active_warnings.rename(columns={
    'toelichtingstandaard': 'warning_type',
    'toelichtingpubliek': 'warning_description'
}, inplace=True)
active_warnings

,warning_type,warning_description
zwemwaterlocatie_id,,
1092,ONTRADEN_KWALITEIT,None
1352,ONTRADEN_ZWEMMERSJEUK,None
1375,ONTRADEN_BLAUWALG,None
1366,WAARSCHUWING_KWALITEIT,De waterkwaliteit is op dit moment goed. Volge...
1204,ONTRADEN_BLAUWALG,None
...,...,...
1595,ONTRADEN_KWALITEIT,Deze zwemwaterlocatie is ingedeeld in de 4-jaa...
1191,ONTRADEN_KWALITEIT,Voor deze locatie geldt gedurende het gehele z...
1167,ONTRADEN_KWALITEIT,Voor deze locatie geldt gedurende het gehele z...
1377,WAARSCHUWING_BLAUWALG,None
1502,WAARSCHUWING_ONVEILIGE_SITUATIE,Gevaarlijke waterbodem

In [23]:
warnings = active_warnings.groupby(['zwemwaterlocatie_id'])[['warning_type','warning_description']].apply(lambda x: x.to_dict('records')).reset_index(name='warnings')
warnings

    zwemwaterlocatie_id                                           warnings
0                   963  [{'warning_type': 'WAARSCHUWING_ZWEMMERSJEUK',...
1                   964  [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
2                   966  [{'warning_type': 'WAARSCHUWING_BLAUWALG', 'wa...
3                   969  [{'warning_type': 'WAARSCHUWING_BLAUWALG', 'wa...
4                   971  [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
..                  ...                                                ...
70              6505732  [{'warning_type': 'ONTRADEN_BLAUWALG', 'warnin...
71              6505733  [{'warning_type': 'ONTRADEN_BLAUWALG', 'warnin...
72              6672410  [{'warning_type': 'WAARSCHUWING_BIJZONDERE_OMS...
73              6834321  [{'warning_type': 'WAARSCHUWING_BLAUWALG', 'wa...
74              7941840  [{'warning_type': 'WAARSCHUWING_BIJZONDERE_OMS...

[75 rows x 2 columns]

In [24]:
data = data.merge(warnings, on="zwemwaterlocatie_id", how="left")
data.rename(columns={
    "zwemwaterlocatie_id": "id",
    "voorzieningen": "amenities"
}, inplace=True)
data

,id,name,alternate_name,placename,current_status,description,photos,website,lat,lon,eu_designation,e_coli,int_ent,amenities,warnings
0,1323,Engelermeer Oost,Engelermeer Oost,'s-Hertogenbosch,goed,Het Engelermeer is een serie kunstmatige plass...,NB-031-001 Engelermeer Oost.jpg,None,51.7046,5.2461,1,46.0,46.0,"[5943902, 5943930, 5943929, 5943896, 5943923, ...",NaN
1,1259,'t Hoefsven,'t Hoefsven,Waalwijk,goed,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,None,51.6761,5.0942,1,77.0,46.0,"[5943930, 5943929, 5943892, 5943907, 5943911, ...",NaN
2,1341,'t Nije Hemelriek,'t Nije Hemelriek,Gasselte,goed,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,None,52.9725,6.7556,1,15.0,15.0,"[5943906, 5943913, 5943902, 5943930, 5943929, ...",NaN
3,1315,'t Schaartven,'t Schaartven,Overloon,goed,"‘t Schaartven is een voormalige zandwinplas, g...",None,None,51.5735,5.9749,1,15.0,15.0,"[5943892, 5943916, 5943897, 5943900, 5943929, ...",NaN
4,1344,'t Veenmeer,'t Veenmeer,Tynaarlo,goed,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,None,53.0829,6.6303,1,15.0,15.0,"[5943901, 5943913, 5943906, 5943900, 5943892, ...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,7941840,Strand Kortgene Paardekreek,Paardekreek,Kortgene,NEGATIEF_ZWEMADVIES,Door camping de Paardekreek aangelegd zandstra...,None,None,51.5496,3.8096,1,8329.0,11636.0,NaN,[{'warning_type': 'WAARSCHUWING_BIJZONDERE_OMS...
2474,7356682,Strand Zoutkamp,None,None,goed,strand zoutkamp in onderzoek,None,None,53.3388,6.2973,1,61.0,15.0,NaN,NaN
2475,6837320,Strand Zuid Oldambtmeer,Strand Zuid,Blauwe stad,goed,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,None,53.1651,7.0372,2,461.0,161.0,"[5943927, 5943897, 5943892, 5943929, 5943916, ...",NaN
2476,6997562,Strandje Brouwershaven,Brouwershaven,None,goed,Strandje naast jachthaven van Brouwershaven,None,None,51.7315,3.9154,1,30.0,15.0,NaN,NaN
2477,1240,'t Zwarte Plasje,'t Zwarte Plasje,Rotterdam,goed,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,None,51.9593,4.4913,1,30.0,15.0,"[5943929, 5943902, 5943930, 5943892, 5943927, ...",NaN

In [25]:
data['amenities'] = data['amenities'].apply(lambda x: set(x) if isinstance(x, (list, set, tuple)) else x)

In [26]:
data.to_json('../../api/nl/locations.json', orient="records")

In [27]:
import sqlite3

sql_data = data.copy()
sql_data["amenities"] = sql_data["amenities"].astype(str)
sql_data["warnings"] = sql_data["warnings"].astype(str)
db = sqlite3.connect('../dataset.sqlite3')
sql_data.to_sql('locations', db, index=False, if_exists='append')

2478

In [28]:
data.columns

Index(['id', 'name', 'alternate_name', 'placename', 'current_status',
       'description', 'photos', 'website', 'lat', 'lon', 'eu_designation',
       'e_coli', 'int_ent', 'amenities', 'warnings'],
      dtype='object')

# GeoJSON

In [29]:
from geojson import Feature, Point, FeatureCollection, dumps

In [30]:
collection = []

In [31]:
for index, row in data.iterrows():
    print(row)
    feature = Feature(id=row['id'],
                      geometry=Point((row['lon'], row['lat'])),
                      properties={
        "name": row['name'],
        "alternate_name": row['alternate_name']
    })
    collection.append(feature)

id                                                             1323
name                                               Engelermeer Oost
alternate_name                                     Engelermeer Oost
placename                                          's-Hertogenbosch
current_status                                                 goed
description       Het Engelermeer is een serie kunstmatige plass...
photos                              NB-031-001 Engelermeer Oost.jpg
website                                                        None
lat                                                         51.7046
lon                                                          5.2461
eu_designation                                                    1
e_coli                                                         46.0
int_ent                                                        46.0
amenities         {5943907, 5943895, 5943911, 5943915, 5943916, ...
warnings                                                        NaN
Name: 0, dtype: object
id                                                             1259
name                                                    't Hoefsven
alternate_name                                          't Hoefsven
placename                                                  Waalwijk
current_status                                                 goed
description       De locatie ligt ten zuidoosten van Waalwijk. E...
photos                                   NB-063-001 't Hoefsven.jpg
website                                                        None
lat                                                         51.6761
lon                                                          5.0942
eu_designation                                                    1
e_coli                                                         77.0
int_ent                                                        46.0
amenities         {5943907, 5943911, 5943913, 5943916, 5943891, ...
warnings                                                        NaN
Name: 1, dtype: object
id                                                             1341
name                                              't Nije Hemelriek
alternate_name                                    't Nije Hemelriek
placename                                                  Gasselte
current_status                                                 goed
description       De zwemlocatie “’t Nije Hemelriek” is gelegen ...
photos                          Recreatiezone_'t_Nije_Hemelriek.jpg
website                                                        None
lat                                                         52.9725
lon                                                          6.7556
eu_designation                                                    1
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943906, 5943907, 5943895, 5943911, 5943913, ...
warnings                                                        NaN
Name: 2, dtype: object
id                                                             1315
name                                                  't Schaartven
alternate_name                                        't Schaartven
placename                                                  Overloon
current_status                                                 goed
description       ‘t Schaartven is een voormalige zandwinplas, g...
photos                                                         None
website                                                        None
lat                                                         51.5735
lon                                                          5.9749
eu_designation                                                    1
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943911, 5943916, 5943929, 5943892, 5943898, ...
warnings                                                        NaN
Name: 3, dtype: object
id                                                             1344
name                                                    't Veenmeer
alternate_name                                          't Veenmeer
placename                                                  Tynaarlo
current_status                                                 goed
description       De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...
photos                                Recreatiezone_'t_Veenmeer.jpg
website                                                        None
lat                                                         53.0829
lon                                                          6.6303
eu_designation                                                    1
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943906, 5943907, 5943895, 5943911, 5943913, ...
warnings                                                        NaN
Name: 4, dtype: object
id                                                             1291
name                                                      't Witven
alternate_name                                               Witven
placename                                                 Veldhoven
current_status                                                 goed
description       De zwemlocatie ligt ten zuiden van de gemeente...
photos                                     NB-059-001 't Witven.jpg
website                                        http://www.witven.nl
lat                                                         51.3979
lon                                                          5.4108
eu_designation                                                    1
e_coli                                                         46.0
int_ent                                                        15.0
amenities         {5943907, 5943911, 5943915, 5943916, 5943917, ...
warnings                                                        NaN
Name: 5, dtype: object
id                                                 7350900
name                                        's-Gravenzande
alternate_name                              's-Gravenzande
placename                                   's-Gravenzande
current_status                                        goed
description               Het badstrand van 's-Gravenzande
photos            01i_1_s-Gravenzande_slag_Vlugtenburg.jpg
website                                               None
lat                                                52.0126
lon                                                 4.1392
eu_designation                                           1
e_coli                                                30.0
int_ent                                               46.0
amenities                                              NaN
warnings                                               NaN
Name: 6, dtype: object
id                                                          6841460
name                                               't Gasselterveld
alternate_name                                     't Gasselterveld
placename                                                  Gasselte
current_status                                                 goed
description       De zwemlocatie “’t Gasselterveld” is gelegen i...
photos                                                         None
website                                                        None
lat                                                         52.9722
lon                                                          6.7498
eu_designation                                                    1
e_coli                                                        144.0
int_ent                                                        77.0
amenities         {5943906, 5943907, 5943895, 5943911, 5943913, ...
warnings                                                        NaN
Name: 7, dtype: object
id                                                             1029
name                                                     't Hilgelo
alternate_name                                           't Hilgelo
placename                                               Winterswijk
current_status                                                 goed
description       Recreatiegebied ‟t Hilgelo ligt aan de noordzi...
photos                                 GLD-019-001 HILGELO 2021.jpg
website                                 http://www.leisurelands.nl/
lat                                                         51.9918
lon                                                          6.7242
eu_designation                                                    2
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943904, 5943906, 5943907, 5943911, 5943912, ...
warnings                                                        NaN
Name: 8, dtype: object
id                                                             1029
name                                                     't Hilgelo
alternate_name                                           't Hilgelo
placename                                               Winterswijk
current_status                                                 goed
description       Recreatiegebied ‟t Hilgelo ligt aan de noordzi...
photos                                 GLD-019-001 HILGELO 2021.jpg
website                                 http://www.leisurelands.nl/
lat                                                         51.9936
lon                                                          6.7208
eu_designation                                                    2
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943904, 5943906, 5943907, 5943911, 5943912, ...
warnings                                                        NaN
Name: 9, dtype: object
id                                                             1029
name                                         't Hilgelo Naaktstrand
alternate_name                               't Hilgelo Naaktstrand
placename                                               Winterswijk
current_status                                                 goed
description       Recreatiegebied ‟t Hilgelo ligt aan de noordzi...
photos                                 GLD-019-004 HILGELO 2021.jpg
website                                 http://www.leisurelands.nl/
lat                                                         51.9936
lon                                                          6.7208
eu_designation                                                    2
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943904, 5943906, 5943907, 5943911, 5943912, ...
warnings                                                        NaN
Name: 10, dtype: object
id                                                             1029
name                                         't Hilgelo Naaktstrand
alternate_name                               't Hilgelo Naaktstrand
placename                                               Winterswijk
current_status                                                 goed
description       Recreatiegebied ‟t Hilgelo ligt aan de noordzi...
photos                                 GLD-019-004 HILGELO 2021.jpg
website                                 http://www.leisurelands.nl/
lat                                                         51.9918
lon                                                          6.7242
eu_designation                                                    2
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943904, 5943906, 5943907, 5943911, 5943912, ...
warnings                                                        NaN
Name: 11, dtype: object
id                                                             1118
name                                                       't Petje
alternate_name                                             't Petje
placename                                                 Zijdewind
current_status                                  NEGATIEF_ZWEMADVIES
description       Deze locatie heeft een permanent negatief zwem...
photos                                                 't Petje.PNG
website                                                        None
lat                                                         52.7392
lon                                                          4.8396
eu_designation                                                    4
e_coli                                                        485.0
int_ent                                                       330.0
amenities         {5943932, 5943906, 5943910, 5943913, 5943915, ...
warnings          [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
Name: 12, dtype: object
id                                                             1114
name                                                     't Skarpet
alternate_name                                           't Skarpet
placename                                              Oude Niedorp
current_status                                  NEGATIEF_ZWEMADVIES
description       Deze locatie heeft een permanent negatief zwem...
photos                                               't Skarpet.PNG
website                                                        None
lat                                                         52.7175
lon                                                          4.8725
eu_designation                                                    4
e_coli                                                        705.0
int_ent                                                       109.0
amenities         {5943932, 5943906, 5943907, 5943910, 5943911, ...
warnings          [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
Name: 13, dtype: object
id                                                             1143
name                                                         't Wed
alternate_name                                               't Wed
placename                                                  Overveen
current_status                                         WAARSCHUWING
description       't Wed ligt in het nationale park Zuid-Kenneme...
photos                                                     tWed.PNG
website                                                        None
lat                                                         52.3996
lon                                                          4.5898
eu_designation                                                    1
e_coli                                                         15.0
int_ent                                                        15.0
amenities         {5943907, 5943891, 5943892, 5943930, 5943927, ...
warnings                                                        NaN
Name: 14, dtype: object
id                                                           299241
name                                                        't Zand
alternate_name                                              't Zand
placename                                                   't Zand
current_status                                                 goed
description       Zwemplas 't Zand wordt omgeven door bosgebied....
photos                                       NB-002-001 't Zand.jpg
website                                                        None
lat                                                         51.4993
lon                                                          4.9497
eu_designation                                                    1
e_coli                                                         77.0
int_ent                                                        15.0
amenities         {5943907, 5943911, 5943915, 5943916, 5943892, ...
warnings                                                        NaN
Name: 15, dtype: object
id                                                             1249
name                                           't Zand Middenstrand
alternate_name                                              't Zand
placename                                                   't Zand
current_status                                                 goed
description                                        nog in te vullen
photos                                       NB-002-001 't Zand.jpg
website                                                        None
lat                                                         51.4997
lon                                                          4.9532
eu_designation                                                    1
e_coli                                                         61.0
int_ent                                                        15.0
amenities         {5943907, 5943911, 5943913, 5943919, 5943891, ...
warnings                                                        NaN
Name: 16, dtype: object
id                                                             1619
name                                            Aakvlaai, Badstrand
alternate_name                                  Aakvlaai, Badstrand
placename                                           Geertruidenberg
current_status                                                 goed
description       De Aakvlaai is een 150 hectare groot waterspor...
photos                                      NB-014-002 Aakvlaai.jpg
website                                    https://www.biesbosch.nu
lat                                                         51.7236
lon                                                          4.8646
eu_designation                                                    1
e_coli                                                         60.0
int_ent                                                        15.0
amenities             {5943907, 5943911, 5943891, 5943892, 5943929}
warnings                                                        NaN
Name: 17, dtype: object
id                                                             1550
name                                                   Abbertstrand
alternate_name                                         Abbertstrand
placename                                                   Dronten
current_status                                                 goed
description       Het Abbertstrand ligt aan het Drontermeer tuss...
photos            DOCUVITP-#1332258-v1-12_067_Abbertstrand-1_pdf...
website                            https://www.atsea-restaurant.nl/
lat                                                         52.5127
lon                                                          5.8547
eu_designation                                                    3
e_coli                                                        160.0
int_ent                                                        15.0
amenities         {5943907, 5943895, 5943911, 5943917, 5943921, ...
warnings                                                        NaN
Name: 18, dtype: object
id                                                              990
name                                              Agnietenplas Oost
alternate_name                                    Agnietenplas Oost
placename                                                    Zwolle

In [32]:
geojson = FeatureCollection(collection)

In [33]:
with open("../../api/nl/map.geojson", "w") as outputGeoJson:
    outputGeoJson.write(dumps(geojson))

In [34]:
from ipyleaflet import Map, Marker, GeoJSON
import random

center = (52.204793, 360.121558)

m = Map(center=center, zoom=15)

geo_json = GeoJSON(
    data=geojson,
    style={
        'color': 'black'
    }
)
m.layers = [m.layers[0], geo_json]
m

Map(center=[52.204793, 360.121558], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title'…

In [35]:
unique_amenities = zwemplek_voorziening.copy()
unique_amenities = unique_amenities.drop_duplicates("code").drop(columns=['id', 'taal', 'zwemplek_id', 'zwemwaterlocatie_id', 'geometry'])
unique_amenities = unique_amenities[['voorziening_type_id', 'omschrijving', 'groep']].set_index('voorziening_type_id')
unique_amenities.to_csv('../../api/nl/amenities.csv')