In [7]:
import geopandas as gpd
from requests import Request
from owslib.wfs import WebFeatureService

In [8]:
url = "https://pubgeo.zwemwater.nl/geoserver/zwr_public/wfs"
wfs = WebFeatureService(url=url)

In [9]:
def load_wfs_layer(layer_name):
    params = dict(service='WFS', version="2.0.0", request='GetFeature',
      typeName=layer_name, outputFormat='json', srsName="EPSG:4326")
    wfs_request_url = Request('GET', url, params=params).prepare().url
    return gpd.read_file(wfs_request_url) # type: ignore

# Data

### Zwemplekken

In [10]:
zwemplekken = load_wfs_layer("zwr_public:zwemplekken")
zwemplekken = zwemplekken.drop(columns=['id', 'datum']).set_index('key_id')
zwemplekken.drop_duplicates(subset=['zwemwaterlocatie_id'], inplace=True)
zwemplekken

,korte_naam,naam,status,zwemwaterlocatie_id,geometry
key_id,,,,,
2265,Camping De Schans,Camping De Schans,goed,1544,POINT (5.4958 51.8357)
2172,Zwemplas Hommelheide,Zwemplas Hommelheide,goed,1451,POINT (5.8867 51.0678)
1928,Natuurbad Te Werve,Natuurbad Te Werve,goed,1207,POINT (4.3197 52.0449)
7556740,tenaxx,landgoed tennax,goed,7556710,POINT (7.0206 53.0754)
2183,Badstrand Badhuis,Badstrand Badhuis,goed,1462,POINT (5.0511 53.3051)
...,...,...,...,...,...
304930,Pieterman,Pieterman,goed,304870,POINT (5.0606 52.4871)
6249502,Beachstrand Eemhof,Beachstrand Eemhof,goed,6249511,POINT (5.3905 52.2599)
5921285,strndbad Win,Strandbad Winterswijk,goed,5921822,POINT (6.7254 51.9565)
2381,Noordwijk B,Noordwijk aan Zee Boulevard,goed,1660,POINT (4.4275 52.245)
6575132,lwm zeearend,Lauwersmeer strand Zeearend,goed,6505731,POINT (6.2222 53.397)

In [11]:
zwemplekken_details = load_wfs_layer("zwr_public:zwemplekken_details")
zwemplekken_details = zwemplekken_details.drop(columns=["id", "info_id", "geometry", "datum"])
zwemplekken_details['adr_huisnummer'] = zwemplekken_details['adr_huisnummer'].astype('Int64')
zwemplekken_details[['adr_huisletter', 'adr_huisnummertoevoeging', 'adr_straat']] = zwemplekken_details[['adr_huisletter', 'adr_huisnummertoevoeging', 'adr_straat']].fillna('')
zwemplekken_details[['adr_straat', 'adr_huisnummer', 'adr_huisletter', 'adr_huisnummertoevoeging']].astype(str)
zwemplekken_details['adr_huisnummer'] = zwemplekken_details['adr_huisnummer'].astype(str).replace('<NA>','')
zwemplekken_details['adr_postcode'] = zwemplekken_details['adr_postcode'].fillna('')
zwemplekken_details['adr_woonplaats'] = zwemplekken_details['adr_woonplaats'].fillna('')
# zwemplekken_details['street'] = zwemplekken_details[['adr_straat', 'adr_huisnummer', 'adr_huisletter', 'adr_huisnummertoevoeging']].applymap(lambda x: str(x).strip()).agg(' '.join, axis=1)
zwemplekken_details['street'] = (
    zwemplekken_details['adr_straat'].fillna('').astype(str).str.strip()
    .str.cat(
        zwemplekken_details[
            ['adr_huisnummer', 'adr_huisletter', 'adr_huisnummertoevoeging']
        ]
        .fillna('')
        .astype(str)
        .apply(lambda c: c.str.strip()),
        sep=' ',
    )
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
    .str.title()
)

# Function to concatenate values only if both columns have non-missing values
def concatenate_if_both_not_na(row):
    print(row)
    col1 = row['street'].strip()
    col2 = row['adr_woonplaats'].strip()
    if col1 and col2:
        return f"{col1}, {col2}"
    else:
        if len(col2.strip()) > 0:
            return col2
        return ""


zwemplekken_details['address'] = zwemplekken_details.apply(concatenate_if_both_not_na, axis=1)
zwemplekken_details.drop(columns=['adr_huisnummer', 'adr_huisletter', 'adr_huisnummertoevoeging', 'adr_straat', 'adr_postcode', 'street'], inplace=True)
zwemplekken_details.drop_duplicates(subset=['zwemwaterlocatie_id'], inplace=True)
zwemplekken_details

adr_huisletter
adr_huisnummer                                                            NaN
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                           De Dreef
adr_woonplaats                                                     Heerenveen
info_filename                                         FR-043-001 De Heide.jpg
info_length                                                          356023.0
info_mime_type                                                     image/jpeg
key_id                                                                   1676
korte_naam                                                              Heide
naam                                                                 De Heide
objecttype                                                           zwemplek
org_bedrijfsnaam                                          Gemeente Heerenveen
org_email                                              gemeente@heerenveen.nl
org_fax
org_huisletter
org_huisnumeer                                                            NaN
org_huisnummertoevoeging
org_id                                                                5922365
org_postcode                                                              NaN
org_straat
org_telefoon                                                    0513-617 617
org_website                                          http://www.heerenveen.nl
org_woonplaats                                                     Heerenveen
status                                                                   goed
taal                                                                       nl
tekst                       Het recreatiegebied “De Heide”, ligt aan de zu...
toegang                                                    OPENBAAR ONBETAALD
website                                                                   NaN
zwemwaterlocatie_id                                                       955
street                                                               De Dreef
Name: 0, dtype: object
adr_huisletter
adr_huisnummer                                                            NaN
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                           Spokedam
adr_woonplaats                                                     Noordwolde
info_filename                                       FR-046-001 Spoekeplas.jpg
info_length                                                          297473.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1677
korte_naam                                                         Spoekeplas
naam                                                               Spoekeplas
objecttype                                                           zwemplek
org_bedrijfsnaam                                  Staatsbosbeheer Regio Noord
org_email                                             info@staatsbosbeheer.nl
org_fax
org_huisletter
org_huisnumeer                                                            NaN
org_huisnummertoevoeging
org_id                                                                5922347
org_postcode                                                              NaN
org_straat
org_telefoon                                                    050 707 4444
org_website                                     http://www.staatsbosbeheer.nl
org_woonplaats                                                      Groningen
status                                                                   goed
taal                                                                       nl
tekst                       Het zwemwater Spoekeplas ligt ten zuidwesten v...
toegang                                                    OPENBAAR ONBETAALD
website                                                                   NaN
zwemwaterlocatie_id                                                       956
street                                                               Spokedam
Name: 1, dtype: object
adr_huisletter
adr_huisnummer                                                            NaN
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                             Canada
adr_woonplaats                                                      Appelscha
info_filename                                        Canadameer Appelscha.png
info_length                                                          212248.0
info_mime_type                                                      image/png
key_id                                                                   1678
korte_naam                                                         Canadameer
naam                                                               Canadameer
objecttype                                                           zwemplek
org_bedrijfsnaam                                  Staatsbosbeheer Regio Noord
org_email                                             info@staatsbosbeheer.nl
org_fax
org_huisletter
org_huisnumeer                                                            NaN
org_huisnummertoevoeging
org_id                                                                5922347
org_postcode                                                              NaN
org_straat
org_telefoon                                                    050 707 4444
org_website                                     http://www.staatsbosbeheer.nl
org_woonplaats                                                      Groningen
status                                                                   goed
taal                                                                       nl
tekst                       Het Canadameer (ook wel Aekingermeer genoemd) ...
toegang                                                    OPENBAAR ONBETAALD
website                                                                   NaN
zwemwaterlocatie_id                                                       957
street                                                                 Canada
Name: 2, dtype: object
adr_huisletter
adr_huisnummer                                                            NaN
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                     Kleasterkampen
adr_woonplaats                                                      Smalle Ee
info_filename                                 FR-028-001 Smeliester SaÌ‚n.jpg
info_length                                                          210638.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1680
korte_naam                                                     Smeliester Sân
naam                                                           Smeliester Sân
objecttype                                                           zwemplek
org_bedrijfsnaam                                      Gemeente Smallingerland
org_email                                          gemeente@smallingerland.nl
org_fax
org_huisletter
org_huisnumeer                                                            NaN
org_huisnummertoevoeging
org_id                                                                5922348
org_postcode                                                              NaN
org_straat
org_telefoon                                                      0512-581234
org_website                                      http://www.smallingerland.nl
org_woonplaats                                                       Drachten
status                                                                   goed
taal                                                                       nl
tekst                       Het zwemwater ligt aan de zuidzijde van het ge...
toegang                                                    OPENBAAR ONBETAALD
website                                                                   NaN
zwemwaterlocatie_id                                                       959
street                                                         Kleasterkampen
Name: 3, dtype: object
adr_huisletter
adr_huisnummer                                                            NaN
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                           Bildreed
adr_woonplaats                                                     Rottevalle
info_filename                                         FR-027-001 De Leien.jpg
info_length                                                          209646.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1681
korte_naam                                                           De Leien
naam                                                                 De Leien
objecttype                                                           zwemplek
org_bedrijfsnaam                                  Staatsbosbeheer Regio Noord
org_email                                             info@staatsbosbeheer.nl
org_fax
org_huisletter
org_huisnumeer                                                            NaN
org_huisnummertoevoeging
org_id                                                                5922347
org_postcode                                                              NaN
org_straat
org_telefoon                                                    050 707 4444
org_website                                     http://www.staatsbosbeheer.nl
org_woonplaats                                                      Groningen
status                                                                   goed
taal                                                                       nl
tekst                       Het zwemwater ligt enkele kilometers ten noord...
toegang                                                    OPENBAAR ONBETAALD
website                                                                   NaN
zwemwaterlocatie_id                                                       960
street                                                               Bildreed
Name: 4, dtype: object
adr_huisletter
adr_huisnummer                                                            NaN
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                    Koaidyk/Walddyk
adr_woonplaats                                                      Earnewâld
info_filename                                      FR-026-001 EarnewaÌ‚ld.jpg
info_length                                                          217711.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1682
korte_naam                                               Zwemplaats Earnewâld
naam                                                     Zwemplaats Earnewâld
objecttype                                                           zwemplek
org_bedrijfsnaam            Stichting Behear Rekreative Foarsjennings Earn...
org_email                                             sbrfearnewald@gmail.com
org_fax
org_huisletter
org_huisnumeer                                                            NaN
org_huisnummertoevoeging
org_id                                                                5922346
org_postcode                                                              NaN
org_straat
org_telefoon                                                      06-12142631
org_website                                      http://www.havenearnewald.nl
org_woonplaats                                                      Earnewâld
status                                                                   goed
taal                                                                       nl
tekst                       Zwemplaats Earnewâld, ook bekend als It Wiid, ...
toegang                                                    OPENBAAR ONBETAALD
website                                                                   NaN
zwemwaterlocatie_id                                                       961
street                                                        Koaidyk/Walddyk
Name: 5, dtype: object
adr_huisletter
adr_huisnummer                                                             30
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                      Solcamastraat
adr_woonplaats                                                          Sumar
info_filename                          FR-024-001 Klein Zwitserland Sumar.jpg
info_length                                                          264948.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1683
korte_naam                                                  Klein Zwitserland
naam                                    Dagrecreatieterrein Klein Zwitserland
objecttype                                                           zwemplek
org_bedrijfsnaam                                    Vakantiepark Bergumermeer
org_email                                                info@bergumermeer.nl
org_fax                                                                   NaN
org_huisletter                                                            NaN
org_huisnumeer                                                            NaN
org_huisnummertoevoeging                                                  NaN
org_id                                                                5922344
org_postcode                                                              NaN
org_straat                                                                NaN
org_telefoon                                                      0511-461385
org_website                                        http://www.bergumermeer.nl
org_woonplaats                                                          Sumar
status                                                                   goed
taal                                                                       nl
tekst                       Het zwemwater ligt aan de westzijde van het Bu...
toegang                                                    OPENBAAR ONBETAALD
website                                                                   NaN
zwemwaterlocatie_id                                                       962
street                                                       Solcamastraat 30
Name: 6, dtype: object
adr_huisletter
adr_huisnummer                                                            NaN
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                Prins Bernhardweg 1
adr_woonplaats                                                Schiermonnikoog
info_filename                                       FR-010-001 Berkenplas.jpg
info_length                                                          254584.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1684
korte_naam                                                         Berkenplas
naam                                                               Berkenplas
objecttype                                                           zwemplek
org_bedrijfsnaam            Vereniging Natuurmonumenten, Nationaal Park Sc...
org_email                                 schiermonnikoog@natuurmonumenten.nl
org_fax                                                                   NaN
org_huisletter                                                            NaN
org_huisnumeer                                                            NaN
org_huisnummertoevoeging                                                  NaN
org_id                                                                5922125
org_postcode                                                              NaN
org_straat                                                                NaN
org_telefoon                                                     0519 531 233
org_website                                                               NaN
org_woonplaats                                                Schiermonnikoog
status                                                                   goed
taal                                                                       nl
tekst                       De zwemlocatie ligt op Schiermonnikoog ten noo...
toegang                                                    OPENBAAR ONBETAALD
website                                                                   NaN
zwemwaterlocatie_id                                                       963
street                                                    Prins Bernhardweg 1
Name: 7, dtype: object
adr_huisletter
adr_huisnummer                                                            NaN
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                    Bramerduinenpad
adr_woonplaats                                                            Nes
info_filename                                        FR-009-001 De Vleyen.jpg
info_length                                                          271129.0
info_mime_type                                                    image/pjpeg
key_id                                                                   1685
korte_naam                                                             Vleyen
naam                                                                De Vleyen
objecttype                                                           zwemplek
org_bedrijfsnaam                                             Gemeente Ameland
org_email                                                     info@ameland.nl
org_fax                                                                   NaN
org_huisletter                                                            NaN
org_huisnumeer                                                            NaN
org_huisnummertoevoeging                                                  NaN
org_id                                                                 299378
org_postcode                                                              NaN
org_straat                                                                NaN
org_telefoon                                                      0519-555555
org_website                                             http://www.ameland.nl
org_woonplaats                                                        Ameland
status                                                                   goed
taal                                                                       nl
tekst                       De zwemwaterlocatie ligt op Ameland ten noordo...
toegang                                                    OPENBAAR ONBETAALD
website                                                                   NaN
zwemwaterlocatie_id                                                       964
street                                                        Bramerduinenpad
Name: 8, dtype: object
adr_huisletter
adr_huisnummer                                                            NaN
adr_huisnummertoevoeging
adr_postcode
adr_straat                                                        Mountsjewei
adr_woonplaats                                                     Leeuwarden
info_filename                                     FR-022-001 Lytse Wielen.jpg
info_length                                                          211342.0

,adr_woonplaats,info_filename,info_length,info_mime_type,key_id,korte_naam,naam,objecttype,org_bedrijfsnaam,org_email,...,org_telefoon,org_website,org_woonplaats,status,taal,tekst,toegang,website,zwemwaterlocatie_id,address
0,Heerenveen,FR-043-001 De Heide.jpg,356023.0,image/jpeg,1676,Heide,De Heide,zwemplek,Gemeente Heerenveen,gemeente@heerenveen.nl,...,0513-617 617,http://www.heerenveen.nl,Heerenveen,goed,nl,"Het recreatiegebied “De Heide”, ligt aan de zu...",OPENBAAR ONBETAALD,NaN,955,"De Dreef, Heerenveen"
1,Noordwolde,FR-046-001 Spoekeplas.jpg,297473.0,image/pjpeg,1677,Spoekeplas,Spoekeplas,zwemplek,Staatsbosbeheer Regio Noord,info@staatsbosbeheer.nl,...,050 707 4444,http://www.staatsbosbeheer.nl,Groningen,goed,nl,Het zwemwater Spoekeplas ligt ten zuidwesten v...,OPENBAAR ONBETAALD,NaN,956,"Spokedam, Noordwolde"
2,Appelscha,Canadameer Appelscha.png,212248.0,image/png,1678,Canadameer,Canadameer,zwemplek,Staatsbosbeheer Regio Noord,info@staatsbosbeheer.nl,...,050 707 4444,http://www.staatsbosbeheer.nl,Groningen,goed,nl,Het Canadameer (ook wel Aekingermeer genoemd) ...,OPENBAAR ONBETAALD,NaN,957,"Canada, Appelscha"
3,Smalle Ee,FR-028-001 Smeliester SaÌ‚n.jpg,210638.0,image/pjpeg,1680,Smeliester Sân,Smeliester Sân,zwemplek,Gemeente Smallingerland,gemeente@smallingerland.nl,...,0512-581234,http://www.smallingerland.nl,Drachten,goed,nl,Het zwemwater ligt aan de zuidzijde van het ge...,OPENBAAR ONBETAALD,NaN,959,"Kleasterkampen, Smalle Ee"
4,Rottevalle,FR-027-001 De Leien.jpg,209646.0,image/pjpeg,1681,De Leien,De Leien,zwemplek,Staatsbosbeheer Regio Noord,info@staatsbosbeheer.nl,...,050 707 4444,http://www.staatsbosbeheer.nl,Groningen,goed,nl,Het zwemwater ligt enkele kilometers ten noord...,OPENBAAR ONBETAALD,NaN,960,"Bildreed, Rottevalle"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,Heijen,NaN,NaN,NaN,8449920,Het Heijderbos,Center Parcs Het Heijderbos,zwemplek,Center Parcs Het Heijderbos,guestrelations.heijderbos@groupepvcp.com,...,0485-496700,https://www.centerparcs.nl/nl-nl/nederland/fp_...,Heijen,goed,nl,"De zwemlocatie is onderdeel van Center Parcs ""...",NaN,https://www.centerparcs.nl/nl-nl/nederland/fp_...,8449690,"Hommersumseweg 43, Heijen"
939,Bergen (NH),NH-004-004.PNG,166515.0,image/png,8452761,Camperduin Lagune,Camperduin Lagune,zwemplek,Gemeente Bergen,info@bergen-nh.nl,...,072-8880000,http://www.bergen-nh.nl,Bergen,goed,nl,De Lagune Camperduin is een waterlichaam dat g...,NaN,NaN,8452780,Bergen (NH)
940,Waalwijk,NaN,NaN,NaN,8455080,Surfvijver Waalwijk,Surfvijver Waalwijk,zwemplek,Gemeente Waalwijk,info@waalwijk.nl,...,0416-683456,NaN,Waalwijk,goed,nl,De Surfvijver in Waalwijk is gelegen in de pro...,gratis,NaN,8455040,"Vijverlaan, Waalwijk"
941,Groningen,NaN,NaN,NaN,8552250,stadspark,Springervijver Stadspark Groningen,zwemplek,Waterschap Noorderzijlvest,info@noorderzijlvest.nl,...,050-3048911,NaN,Groningen,goed,nl,Springervijver Stadspark Groningen,gratis,NaN,8550510,"Springerlaan, Groningen"
942,Altena,NaN,NaN,NaN,8637210,NaN,"Aakvlaai, Badstrand",zwemplek,Gemeente Altena,info@gemeenteAltena.nl,...,0183-516100,NaN,Altena,goed,nl,De Aakvlaai is een 150 hectare groot waterspor...,OPENBAAR ONBETAALD,NaN,1619,"Aakvlaaiweg, Altena"

In [12]:
zwemplekken_details.columns

Index(['adr_woonplaats', 'info_filename', 'info_length', 'info_mime_type',
       'key_id', 'korte_naam', 'naam', 'objecttype', 'org_bedrijfsnaam',
       'org_email', 'org_fax', 'org_huisletter', 'org_huisnumeer',
       'org_huisnummertoevoeging', 'org_id', 'org_postcode', 'org_straat',
       'org_telefoon', 'org_website', 'org_woonplaats', 'status', 'taal',
       'tekst', 'toegang', 'website', 'zwemwaterlocatie_id', 'address'],
      dtype='str')

In [13]:
photos = load_wfs_layer("zwr_public:locatiefotos")
photos

,id,filename,key_id,length,mime_type,zwemplek_id,geometry
0,locatiefotos.fid--9c481f8_19c09940889_-2eef,testgegevens.csv,559072,23483,application/vnd.ms-excel,NaN,None
1,locatiefotos.fid--9c481f8_19c09940889_-2eee,18-07-2012.jpg,559074,18482,image/pjpeg,1762.0,"POLYGON ((5.9978 52.311, 5.998 52.3109, 6.0003..."
2,locatiefotos.fid--9c481f8_19c09940889_-2eed,FR-005-001 Badstrand Nes.jpg,1092,327074,image/pjpeg,NaN,None
3,locatiefotos.fid--9c481f8_19c09940889_-2eec,FR-004-001 Badstrand Hollum.jpg,1091,280508,image/pjpeg,NaN,None
4,locatiefotos.fid--9c481f8_19c09940889_-2eeb,FR-009-001 De Vleyen.jpg,1093,271129,image/pjpeg,NaN,None
...,...,...,...,...,...,...,...
6355,locatiefotos.fid--9c481f8_19c09940889_-161c,GLD-008-002 ZEUMEREN 2026.jpg,8674542,3889852,image/jpeg,NaN,None
6356,locatiefotos.fid--9c481f8_19c09940889_-161b,GLD-008-003 ZEUMEREN 2026.jpg,8674543,3890211,image/jpeg,NaN,None
6357,locatiefotos.fid--9c481f8_19c09940889_-161a,14 juni 2008 005.jpg,8674592,820719,image/pjpeg,NaN,None
6358,locatiefotos.fid--9c481f8_19c09940889_-1619,14 juni 2008 005.jpg,8674593,820719,image/pjpeg,NaN,None
6359,locatiefotos.fid--9c481f8_19c09940889_-1618,14 juni 2008 005.jpg,8674594,820719,image/pjpeg,303591.0,"POLYGON ((5.9516 52.4388, 5.952 52.4381, 5.952..."

In [14]:
photos["mime_type"].unique()

<ArrowStringArray>
[                                               'application/vnd.ms-excel',
                                                             'image/pjpeg',
                                                              'image/jpeg',
                                                               'image/png',
                                                         'application/pdf',
                                                'application/octet-stream',
 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                                                      'application/msword',
       'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                                                              'text/plain',
                                                             'ds/document',
                                                               'text/html',
                                 'application/vnd.oasis.opendocument.text']
Length: 13, dtype: str

In [15]:
photos = photos[
    photos['mime_type'].isin([
        'image/pjpeg', 
        'image/jpeg',
        'image/png'
    ])
]
photos

,id,filename,key_id,length,mime_type,zwemplek_id,geometry
1,locatiefotos.fid--9c481f8_19c09940889_-2eee,18-07-2012.jpg,559074,18482,image/pjpeg,1762.0,"POLYGON ((5.9978 52.311, 5.998 52.3109, 6.0003..."
2,locatiefotos.fid--9c481f8_19c09940889_-2eed,FR-005-001 Badstrand Nes.jpg,1092,327074,image/pjpeg,NaN,None
3,locatiefotos.fid--9c481f8_19c09940889_-2eec,FR-004-001 Badstrand Hollum.jpg,1091,280508,image/pjpeg,NaN,None
4,locatiefotos.fid--9c481f8_19c09940889_-2eeb,FR-009-001 De Vleyen.jpg,1093,271129,image/pjpeg,NaN,None
5,locatiefotos.fid--9c481f8_19c09940889_-2eea,FR-006-001 Badstrand Buren.jpg,1094,299640,image/pjpeg,NaN,None
...,...,...,...,...,...,...,...
6355,locatiefotos.fid--9c481f8_19c09940889_-161c,GLD-008-002 ZEUMEREN 2026.jpg,8674542,3889852,image/jpeg,NaN,None
6356,locatiefotos.fid--9c481f8_19c09940889_-161b,GLD-008-003 ZEUMEREN 2026.jpg,8674543,3890211,image/jpeg,NaN,None
6357,locatiefotos.fid--9c481f8_19c09940889_-161a,14 juni 2008 005.jpg,8674592,820719,image/pjpeg,NaN,None
6358,locatiefotos.fid--9c481f8_19c09940889_-1619,14 juni 2008 005.jpg,8674593,820719,image/pjpeg,NaN,None
6359,locatiefotos.fid--9c481f8_19c09940889_-1618,14 juni 2008 005.jpg,8674594,820719,image/pjpeg,303591.0,"POLYGON ((5.9516 52.4388, 5.952 52.4381, 5.952..."

In [16]:
photos = photos.query("zwemplek_id.notnull()")
photodata = photos[['zwemplek_id', 'key_id', 'filename']].copy()
photodata['zwemplek_id'] = photodata['zwemplek_id'].astype(int)
photodata['key_id'] = "https://register.zwemwater.nl/zwr/api/files/" + photodata['key_id'].astype(str)
for item in photodata.query('zwemplek_id == 6187300').iterrows():
    print(item)

(3991, zwemplek_id                                              6187300
key_id         https://register.zwemwater.nl/zwr/api/files/61...
filename                            WP_20170413_12_40_27_Pro.jpg
Name: 3991, dtype: object)
(3992, zwemplek_id                                              6187300
key_id         https://register.zwemwater.nl/zwr/api/files/61...
filename                         2019 IMG_20190629_101301032.jpg
Name: 3992, dtype: object)
(3993, zwemplek_id                                              6187300
key_id         https://register.zwemwater.nl/zwr/api/files/61...
filename        2017 Overzichtsfoto WP_20170413_12_42_21_Pro.jpg
Name: 3993, dtype: object)

In [17]:
base_data = zwemplekken_details.copy()
base_data = base_data[["zwemwaterlocatie_id", "naam", "korte_naam", "address", "adr_woonplaats", "status", "tekst", "info_filename", "website"]]
base_data

,zwemwaterlocatie_id,naam,korte_naam,address,adr_woonplaats,status,tekst,info_filename,website
0,955,De Heide,Heide,"De Dreef, Heerenveen",Heerenveen,goed,"Het recreatiegebied “De Heide”, ligt aan de zu...",FR-043-001 De Heide.jpg,NaN
1,956,Spoekeplas,Spoekeplas,"Spokedam, Noordwolde",Noordwolde,goed,Het zwemwater Spoekeplas ligt ten zuidwesten v...,FR-046-001 Spoekeplas.jpg,NaN
2,957,Canadameer,Canadameer,"Canada, Appelscha",Appelscha,goed,Het Canadameer (ook wel Aekingermeer genoemd) ...,Canadameer Appelscha.png,NaN
3,959,Smeliester Sân,Smeliester Sân,"Kleasterkampen, Smalle Ee",Smalle Ee,goed,Het zwemwater ligt aan de zuidzijde van het ge...,FR-028-001 Smeliester SaÌ‚n.jpg,NaN
4,960,De Leien,De Leien,"Bildreed, Rottevalle",Rottevalle,goed,Het zwemwater ligt enkele kilometers ten noord...,FR-027-001 De Leien.jpg,NaN
...,...,...,...,...,...,...,...,...,...
938,8449690,Center Parcs Het Heijderbos,Het Heijderbos,"Hommersumseweg 43, Heijen",Heijen,goed,"De zwemlocatie is onderdeel van Center Parcs ""...",NaN,https://www.centerparcs.nl/nl-nl/nederland/fp_...
939,8452780,Camperduin Lagune,Camperduin Lagune,Bergen (NH),Bergen (NH),goed,De Lagune Camperduin is een waterlichaam dat g...,NH-004-004.PNG,NaN
940,8455040,Surfvijver Waalwijk,Surfvijver Waalwijk,"Vijverlaan, Waalwijk",Waalwijk,goed,De Surfvijver in Waalwijk is gelegen in de pro...,NaN,NaN
941,8550510,Springervijver Stadspark Groningen,stadspark,"Springerlaan, Groningen",Groningen,goed,Springervijver Stadspark Groningen,NaN,NaN
942,1619,"Aakvlaai, Badstrand",NaN,"Aakvlaaiweg, Altena",Altena,goed,De Aakvlaai is een 150 hectare groot waterspor...,NaN,NaN

In [18]:
zwemplekdata = base_data.merge(zwemplekken, left_on="zwemwaterlocatie_id", right_on="zwemwaterlocatie_id", how="left")
zwemplekdata['lat'] = zwemplekdata['geometry'].apply(lambda geom: geom.y if geom else None)
zwemplekdata['lon'] = zwemplekdata['geometry'].apply(lambda geom: geom.x if geom else None)
zwemplekdata = zwemplekdata.drop(columns=["korte_naam_x", "naam_x", "status_x", "geometry"])
zwemplekdata = zwemplekdata.rename(columns={
    "naam_y": "naam",
    "korte_naam_y": "korte_naam",
    "status_y": "status"
})
zwemplekdata.sort_values(by=["naam"], inplace=True)
zwemplekdata

,zwemwaterlocatie_id,address,adr_woonplaats,tekst,info_filename,website,korte_naam,naam,status,lat,lon
569,1259,"Hoefsvenlaan, Waalwijk",Waalwijk,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,NaN,'T Hoefsven,'T Hoefsven,goed,51.6761,5.0942
275,1341,"Bosweg, Gasselte",Gasselte,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,NaN,'T Nije Hemelriek,'T Nije Hemelriek,goed,52.9725,6.7556
597,1315,"Holthesedijk, Overloon",Overloon,"‘t Schaartven is een voormalige zandwinplas, g...",NaN,NaN,'T Schaartven,'T Schaartven,goed,51.5735,5.9749
278,1344,"Paralelleweg, Tynaarlo",Tynaarlo,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,NaN,'T Veenmeer,'T Veenmeer,goed,53.0829,6.6303
257,1291,"Witvenseweg, Veldhoven",Veldhoven,De zwemlocatie ligt ten zuiden van de gemeente...,NB-059-001 't Witven.jpg,http://www.witven.nl,Witven,'T Witven,goed,51.3979,5.4108
...,...,...,...,...,...,...,...,...,...,...,...
719,7941840,Kortgene,Kortgene,Door camping de Paardekreek aangelegd zandstra...,NaN,NaN,Paardekreek,strand Kortgene Paardekreek,goed,51.5496,3.8096
702,7356682,,,strand zoutkamp in onderzoek,NaN,NaN,NaN,strand zoutkamp,goed,53.3388,6.2973
682,6837320,"Elfenbank 1, Blauwe stad",Blauwe stad,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,NaN,strand zuid,strand zuid Oldambtmeer,goed,53.1651,7.0372
681,6997562,Brouwershaven,Brouwershaven,Strandje naast jachthaven van Brouwershaven,NaN,NaN,Brouwershaven,strandje Brouwershaven,goed,51.7315,3.9154
231,1240,"Oude Raadhuislaan 154, Rotterdam",Rotterdam,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,NaN,'t Zwarte Plasje,t Zwarte Plasje,goed,51.9593,4.4913

### EU statussen

In [19]:
eu_designations = load_wfs_layer("zwr_public:eustatussen")
eu_designations = eu_designations[eu_designations['jaar'] == 2024].drop(columns=['type_eu_status_id', 'geometry', 'omschrijving', 'id'])
eu_designations

     code   key_id  jaar  zwemwaterlocatie_id
7337    1  8421618  2024                 1383
7598    1  8419237  2024                 1221
7638    7  8413417  2024                 1372
7644    2  8383240  2024                 1267
7645    1  8383241  2024                 1268
...   ...      ...   ...                  ...
8595    1  8419233  2024                 1217
8596    1  8419236  2024                 1220
8597    1  8419247  2024              5911121
8598    1  8419246  2024              5911120
8639    1  8413440  2024                 1157

[730 rows x 4 columns]

In [20]:
eu_current_designations = eu_designations.drop(columns=["key_id", "jaar"])
eu_current_designations
data = zwemplekdata.merge(eu_current_designations, left_on="zwemwaterlocatie_id", right_on="zwemwaterlocatie_id", how="left")
data.fillna({'code': 0}, inplace=True)
data

,zwemwaterlocatie_id,address,adr_woonplaats,tekst,info_filename,website,korte_naam,naam,status,lat,lon,code
0,1259,"Hoefsvenlaan, Waalwijk",Waalwijk,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,NaN,'T Hoefsven,'T Hoefsven,goed,51.6761,5.0942,1
1,1341,"Bosweg, Gasselte",Gasselte,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,NaN,'T Nije Hemelriek,'T Nije Hemelriek,goed,52.9725,6.7556,1
2,1315,"Holthesedijk, Overloon",Overloon,"‘t Schaartven is een voormalige zandwinplas, g...",NaN,NaN,'T Schaartven,'T Schaartven,goed,51.5735,5.9749,1
3,1344,"Paralelleweg, Tynaarlo",Tynaarlo,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,NaN,'T Veenmeer,'T Veenmeer,goed,53.0829,6.6303,1
4,1291,"Witvenseweg, Veldhoven",Veldhoven,De zwemlocatie ligt ten zuiden van de gemeente...,NB-059-001 't Witven.jpg,http://www.witven.nl,Witven,'T Witven,goed,51.3979,5.4108,1
...,...,...,...,...,...,...,...,...,...,...,...,...
744,7941840,Kortgene,Kortgene,Door camping de Paardekreek aangelegd zandstra...,NaN,NaN,Paardekreek,strand Kortgene Paardekreek,goed,51.5496,3.8096,2
745,7356682,,,strand zoutkamp in onderzoek,NaN,NaN,NaN,strand zoutkamp,goed,53.3388,6.2973,1
746,6837320,"Elfenbank 1, Blauwe stad",Blauwe stad,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,NaN,strand zuid,strand zuid Oldambtmeer,goed,53.1651,7.0372,3
747,6997562,Brouwershaven,Brouwershaven,Strandje naast jachthaven van Brouwershaven,NaN,NaN,Brouwershaven,strandje Brouwershaven,goed,51.7315,3.9154,1
748,1240,"Oude Raadhuislaan 154, Rotterdam",Rotterdam,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,NaN,'t Zwarte Plasje,t Zwarte Plasje,goed,51.9593,4.4913,1

### Metingen

In [21]:
measurements = load_wfs_layer("zwr_public:resultaatsen")
measurements = measurements.drop(columns=['id', 'datum_geplande_monstername', 'monitoring_datum_id', 'monitoring_plan_id', 'monster_id', 'type_object_id', 'geometry'])
measurements = measurements.sort_values(["zwemwaterlocatie_id", "object_begin_tijd", "type_object_code"])
measurements = measurements.drop_duplicates(subset=["zwemwaterlocatie_id", "type_object_code"], keep="last")
measurements

,numerieke_waarde,object_begin_tijd,key_id,type_object_code,zwemwaterlocatie_id
6546,40,2025-09-15 09:15:00+00:00,8651611,E_COLI,955
13545,50,2025-09-15 09:15:00+00:00,8651612,INTTNLETRCCN,955
6177,1100,2025-09-08 08:12:00+00:00,8642068,E_COLI,956
13177,30,2025-09-08 08:12:00+00:00,8642069,INTTNLETRCCN,956
6178,15,2025-09-08 08:48:00+00:00,8642110,E_COLI,957
...,...,...,...,...,...
13713,30,2025-09-15 09:15:00+00:00,8655937,INTTNLETRCCN,8449690
6783,465,2025-09-22 09:05:00+00:00,8659921,E_COLI,8452780
13778,46,2025-09-22 09:05:00+00:00,8659920,INTTNLETRCCN,8452780
6946,15,2025-09-29 07:08:34+00:00,8664039,E_COLI,8455040
13938,30,2025-09-29 07:08:34+00:00,8664050,INTTNLETRCCN,8455040

In [22]:
measure = measurements.pivot_table(values='numerieke_waarde', index='zwemwaterlocatie_id', columns='type_object_code')
measure

type_object_code     E_COLI  INTTNLETRCCN
zwemwaterlocatie_id
955                    40.0          50.0
956                  1100.0          30.0
957                    15.0          15.0
959                   250.0          50.0
960                   140.0          20.0
...                     ...           ...
8435070                15.0          15.0
8439110               210.0          15.0
8449690               210.0          30.0
8452780               465.0          46.0
8455040                15.0          30.0

[755 rows x 2 columns]

In [23]:
data = data.merge(measure, on="zwemwaterlocatie_id", how="left")
data

,zwemwaterlocatie_id,address,adr_woonplaats,tekst,info_filename,website,korte_naam,naam,status,lat,lon,code,E_COLI,INTTNLETRCCN
0,1259,"Hoefsvenlaan, Waalwijk",Waalwijk,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,NaN,'T Hoefsven,'T Hoefsven,goed,51.6761,5.0942,1,15.0,15.0
1,1341,"Bosweg, Gasselte",Gasselte,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,NaN,'T Nije Hemelriek,'T Nije Hemelriek,goed,52.9725,6.7556,1,30.0,15.0
2,1315,"Holthesedijk, Overloon",Overloon,"‘t Schaartven is een voormalige zandwinplas, g...",NaN,NaN,'T Schaartven,'T Schaartven,goed,51.5735,5.9749,1,61.0,15.0
3,1344,"Paralelleweg, Tynaarlo",Tynaarlo,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,NaN,'T Veenmeer,'T Veenmeer,goed,53.0829,6.6303,1,61.0,15.0
4,1291,"Witvenseweg, Veldhoven",Veldhoven,De zwemlocatie ligt ten zuiden van de gemeente...,NB-059-001 't Witven.jpg,http://www.witven.nl,Witven,'T Witven,goed,51.3979,5.4108,1,30.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,7941840,Kortgene,Kortgene,Door camping de Paardekreek aangelegd zandstra...,NaN,NaN,Paardekreek,strand Kortgene Paardekreek,goed,51.5496,3.8096,2,15.0,15.0
745,7356682,,,strand zoutkamp in onderzoek,NaN,NaN,NaN,strand zoutkamp,goed,53.3388,6.2973,1,15.0,92.0
746,6837320,"Elfenbank 1, Blauwe stad",Blauwe stad,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,NaN,strand zuid,strand zuid Oldambtmeer,goed,53.1651,7.0372,3,77.0,30.0
747,6997562,Brouwershaven,Brouwershaven,Strandje naast jachthaven van Brouwershaven,NaN,NaN,Brouwershaven,strandje Brouwershaven,goed,51.7315,3.9154,1,77.0,15.0
748,1240,"Oude Raadhuislaan 154, Rotterdam",Rotterdam,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,NaN,'t Zwarte Plasje,t Zwarte Plasje,goed,51.9593,4.4913,1,30.0,15.0

### Voorzieningen

In [24]:
zwemplek_voorziening = load_wfs_layer("zwr_public:zwemplek_voorziening")
zwemplek_voorziening

,id,aanvulling,code,groep,omschrijving,taal,key_id,voorziening_type_id,zwemplek_id,zwemwaterlocatie_id,geometry
0,zwemplek_voorziening.fid--9c481f8_19c09a0d3a1_...,EHBO post,5943900,ONBEPERKT,EHBO,nl,594394,5943900,1712,991,"POLYGON ((6.128 52.5405, 6.1282 52.5406, 6.129..."
1,zwemplek_voorziening.fid--9c481f8_19c09a0d3a1_...,NaN,5943900,ONBEPERKT,EHBO,NaN,594395,5943900,1834,1113,"POLYGON ((4.9111 52.8895, 4.9122 52.8892, 4.91..."
2,zwemplek_voorziening.fid--9c481f8_19c09a0d3a1_...,NaN,5943913,ONBEPERKT,Parkeergelegenheid,NaN,594396,5943913,1834,1113,"POLYGON ((4.9111 52.8895, 4.9122 52.8892, 4.91..."
3,zwemplek_voorziening.fid--9c481f8_19c09a0d3a1_...,NaN,5943906,ONBEPERKT,Horeca,NaN,594399,5943906,1834,1113,"POLYGON ((4.9111 52.8895, 4.9122 52.8892, 4.91..."
4,zwemplek_voorziening.fid--9c481f8_19c09a0d3a1_...,Blauwe Vlag,5943894,ONBEPERKT,Blauwe vlag,nl,594402,5943894,304213,29530,"POLYGON ((5.0644 51.6126, 5.0641 51.6123, 5.06..."
...,...,...,...,...,...,...,...,...,...,...,...
10773,zwemplek_voorziening.fid--9c481f8_19c09a0d3a1_...,NaN,5943913,ONBEPERKT,Parkeergelegenheid,NaN,8428236,5943913,8428220,8428190,"POLYGON ((5.1715 52.6311, 5.1715 52.631, 5.171..."
10774,zwemplek_voorziening.fid--9c481f8_19c09a0d3a1_...,NaN,5943898,VEILIGHEID,Drijflijn,NaN,8428239,5943898,8428220,8428190,"POLYGON ((5.1715 52.6311, 5.1715 52.631, 5.171..."
10775,zwemplek_voorziening.fid--9c481f8_19c09a0d3a1_...,NaN,5943902,GENERIEK,Fietsenstalling,NaN,8428240,5943902,8428220,8428190,"POLYGON ((5.1715 52.6311, 5.1715 52.631, 5.171..."
10776,zwemplek_voorziening.fid--9c481f8_19c09a0d3a1_...,NaN,5943932,VEILIGHEID,Zwemzone afgebakend,NaN,8428241,5943932,8428220,8428190,"POLYGON ((5.1715 52.6311, 5.1715 52.631, 5.171..."
10777,zwemplek_voorziening.fid--9c481f8_19c09a0d3a1_...,NaN,5943914,ONBEPERKT,Reddingsbrigade,NaN,8435060,5943914,7715190,1674,"POLYGON ((4.53 52.383, 4.5293 52.3832, 4.5298 ..."

In [25]:
voorzieningen = zwemplek_voorziening.groupby('zwemwaterlocatie_id')['voorziening_type_id'].agg(list).reset_index()
voorzieningen

     zwemwaterlocatie_id                                voorziening_type_id
0                    955  [5943905, 5943906, 5943913, 5943913, 5943902, ...
1                    956  [5943905, 5943906, 5943913, 5943913, 5943902, ...
2                    957  [5943913, 5943930, 5943929, 5943907, 5943911, ...
3                    959  [5943913, 5943913, 5943902, 5943930, 5943929, ...
4                    960  [5943906, 5943913, 5943913, 5943902, 5943930, ...
..                   ...                                                ...
721              8428190  [5943916, 5943915, 5943929, 5943911, 5943927, ...
722              8435070  [5943892, 5943897, 5943915, 5943913, 5943907, ...
723              8439110  [5943913, 5943895, 5943929, 5943906, 5943921, ...
724              8452780  [5943892, 5943915, 5943913, 5943900, 5943907, ...
725              8550510  [5943892, 5943907, 5943895, 5943911, 5943930, ...

[726 rows x 2 columns]

In [ ]:
data = data.merge(voorzieningen, on="zwemwaterlocatie_id", how="left")

,address,placename,description,photos,website,alternate_name,name,current_status,lat,lon,eu_designation,e_coli,int_ent,voorzieningen
zwemwaterlocatie_id,,,,,,,,,,,,,,
1259,"Hoefsvenlaan, Waalwijk",Waalwijk,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,NaN,'t Hoefsven,'t Hoefsven,goed,51.6761,5.0942,1,15.0,15.0,"[5943930, 5943929, 5943892, 5943907, 5943911, ..."
1341,"Bosweg, Gasselte",Gasselte,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,NaN,'t Nije Hemelriek,'t Nije Hemelriek,goed,52.9725,6.7556,1,30.0,15.0,"[5943906, 5943913, 5943902, 5943930, 5943929, ..."
1315,"Holthesedijk, Overloon",Overloon,"‘t Schaartven is een voormalige zandwinplas, g...",NaN,NaN,'t Schaartven,'t Schaartven,goed,51.5735,5.9749,1,61.0,15.0,"[5943892, 5943916, 5943897, 5943900, 5943929, ..."
1344,"Paralelleweg, Tynaarlo",Tynaarlo,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,NaN,'t Veenmeer,'t Veenmeer,goed,53.0829,6.6303,1,61.0,15.0,"[5943901, 5943913, 5943906, 5943900, 5943895, ..."
1291,"Witvenseweg, Veldhoven",Veldhoven,De zwemlocatie ligt ten zuiden van de gemeente...,NB-059-001 't Witven.jpg,http://www.witven.nl,Witven,'t Witven,goed,51.3979,5.4108,1,30.0,15.0,"[5943902, 5943930, 5943929, 5943892, 5943927, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7941840,Kortgene,Kortgene,Door camping de Paardekreek aangelegd zandstra...,NaN,NaN,Paardekreek,Strand Kortgene Paardekreek,goed,51.5496,3.8096,2,15.0,15.0,NaN
7356682,,,strand zoutkamp in onderzoek,NaN,NaN,NaN,Strand Zoutkamp,goed,53.3388,6.2973,1,15.0,92.0,NaN
6837320,"Elfenbank 1, Blauwe stad",Blauwe stad,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,NaN,Strand Zuid,Strand Zuid Oldambtmeer,goed,53.1651,7.0372,3,77.0,30.0,"[5943927, 5943897, 5943892, 5943929, 5943916, ..."
6997562,Brouwershaven,Brouwershaven,Strandje naast jachthaven van Brouwershaven,NaN,NaN,Brouwershaven,Strandje Brouwershaven,goed,51.7315,3.9154,1,77.0,15.0,NaN
1240,"Oude Raadhuislaan 154, Rotterdam",Rotterdam,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,NaN,'t Zwarte Plasje,'t Zwarte Plasje,goed,51.9593,4.4913,1,30.0,15.0,"[5943929, 5943902, 5943930, 5943892, 5943927, ..."

### Waarschuwingen

In [27]:
preventative_measures = load_wfs_layer("zwr_public:zwemplek_maatregel")
preventative_measures = preventative_measures.drop(columns=['id', 'bw_code', 'object_type', 'toelichtingstandaardextended', 'type', 'geometry', 'zwemplek_naam'])
active_warnings = preventative_measures[(preventative_measures['objectbegintijd'] <= '2025-06-13')]
active_warnings = active_warnings.drop(columns=['redeningetrokken', 'objectbegintijd', 'objecteindtijd', 'omschrijving', 'key_id'])
active_warnings = active_warnings[[
    'zwemwaterlocatie_id', 'toelichtingstandaard', 'toelichtingpubliek']
]
active_warnings.set_index('zwemwaterlocatie_id', inplace=True)
active_warnings.rename(columns={
    'toelichtingstandaard': 'warning_type',
    'toelichtingpubliek': 'warning_description'
}, inplace=True)
active_warnings

,warning_type,warning_description
zwemwaterlocatie_id,,
1358,ONTRADEN_KWALITEIT,Dit zwemseizoen (1 mei – 1 oktober) geldt voor...
1595,ONTRADEN_KWALITEIT,Deze zwemwaterlocatie is ingedeeld in de 4-jaa...
1233,ONTRADEN_BIJZONDERE_OMSTANDIGHEID,Het negatieve zwemadvies vanwege de PFAS-veron...
1241,ONTRADEN_BIJZONDERE_OMSTANDIGHEID,Negatief zwemadvies vanwege PFAS-verontreinigi...
302622,NORMOVERSCHRIJDING_GECONSTATEERD_WATERKWALITEIT,In verband met een te hoge waarde PFAS is zwem...
1623,ONTRADEN_KWALITEIT,Deze zwemwaterlocatie is ingedeeld in de 4-jaa...
6669260,VERBOD_KWALITEIT,Verboden te zwemmen in verband met een slechte...
1112,ONTRADEN_KWALITEIT,Deze zwemwaterlocatie is ingedeeld in de 4-jaa...
1219,WAARSCHUWING_ONVEILIGE_SITUATIE,Uit veiligheidsonderzoek is gebleken dat de wa...

In [28]:
warnings = active_warnings.groupby(['zwemwaterlocatie_id'])[['warning_type','warning_description']].apply(lambda x: x.to_dict('records')).reset_index(name='warnings')
warnings

   zwemwaterlocatie_id                                           warnings
0                 1112  [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
1                 1219  [{'warning_type': 'WAARSCHUWING_ONVEILIGE_SITU...
2                 1233  [{'warning_type': 'ONTRADEN_BIJZONDERE_OMSTAND...
3                 1241  [{'warning_type': 'ONTRADEN_BIJZONDERE_OMSTAND...
4                 1358  [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
5                 1595  [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
6                 1623  [{'warning_type': 'ONTRADEN_KWALITEIT', 'warni...
7               302622  [{'warning_type': 'NORMOVERSCHRIJDING_GECONSTA...
8              6669260  [{'warning_type': 'VERBOD_KWALITEIT', 'warning...

In [29]:
data = data.merge(warnings, on="zwemwaterlocatie_id", how="left")
data.rename(columns={
    "zwemwaterlocatie_id": "id",
    "voorzieningen": "amenities"
}, inplace=True)
data

,id,address,placename,description,photos,website,alternate_name,name,current_status,lat,lon,eu_designation,e_coli,int_ent,amenities,warnings
0,1259,"Hoefsvenlaan, Waalwijk",Waalwijk,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,NaN,'t Hoefsven,'t Hoefsven,goed,51.6761,5.0942,1,15.0,15.0,"[5943930, 5943929, 5943892, 5943907, 5943911, ...",NaN
1,1341,"Bosweg, Gasselte",Gasselte,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,NaN,'t Nije Hemelriek,'t Nije Hemelriek,goed,52.9725,6.7556,1,30.0,15.0,"[5943906, 5943913, 5943902, 5943930, 5943929, ...",NaN
2,1315,"Holthesedijk, Overloon",Overloon,"‘t Schaartven is een voormalige zandwinplas, g...",NaN,NaN,'t Schaartven,'t Schaartven,goed,51.5735,5.9749,1,61.0,15.0,"[5943892, 5943916, 5943897, 5943900, 5943929, ...",NaN
3,1344,"Paralelleweg, Tynaarlo",Tynaarlo,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,NaN,'t Veenmeer,'t Veenmeer,goed,53.0829,6.6303,1,61.0,15.0,"[5943901, 5943913, 5943906, 5943900, 5943895, ...",NaN
4,1291,"Witvenseweg, Veldhoven",Veldhoven,De zwemlocatie ligt ten zuiden van de gemeente...,NB-059-001 't Witven.jpg,http://www.witven.nl,Witven,'t Witven,goed,51.3979,5.4108,1,30.0,15.0,"[5943902, 5943930, 5943929, 5943892, 5943927, ...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,7941840,Kortgene,Kortgene,Door camping de Paardekreek aangelegd zandstra...,NaN,NaN,Paardekreek,Strand Kortgene Paardekreek,goed,51.5496,3.8096,2,15.0,15.0,NaN,NaN
745,7356682,,,strand zoutkamp in onderzoek,NaN,NaN,NaN,Strand Zoutkamp,goed,53.3388,6.2973,1,15.0,92.0,NaN,NaN
746,6837320,"Elfenbank 1, Blauwe stad",Blauwe stad,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,NaN,Strand Zuid,Strand Zuid Oldambtmeer,goed,53.1651,7.0372,3,77.0,30.0,"[5943927, 5943897, 5943892, 5943929, 5943916, ...",NaN
747,6997562,Brouwershaven,Brouwershaven,Strandje naast jachthaven van Brouwershaven,NaN,NaN,Brouwershaven,Strandje Brouwershaven,goed,51.7315,3.9154,1,77.0,15.0,NaN,NaN
748,1240,"Oude Raadhuislaan 154, Rotterdam",Rotterdam,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,NaN,'t Zwarte Plasje,'t Zwarte Plasje,goed,51.9593,4.4913,1,30.0,15.0,"[5943929, 5943902, 5943930, 5943892, 5943927, ...",NaN

In [30]:
data

,id,address,placename,description,photos,website,alternate_name,name,current_status,lat,lon,eu_designation,e_coli,int_ent,amenities,warnings
0,1259,"Hoefsvenlaan, Waalwijk",Waalwijk,De locatie ligt ten zuidoosten van Waalwijk. E...,NB-063-001 't Hoefsven.jpg,NaN,'t Hoefsven,'t Hoefsven,goed,51.6761,5.0942,1,15.0,15.0,"[5943930, 5943929, 5943892, 5943907, 5943911, ...",NaN
1,1341,"Bosweg, Gasselte",Gasselte,De zwemlocatie “’t Nije Hemelriek” is gelegen ...,Recreatiezone_'t_Nije_Hemelriek.jpg,NaN,'t Nije Hemelriek,'t Nije Hemelriek,goed,52.9725,6.7556,1,30.0,15.0,"[5943906, 5943913, 5943902, 5943930, 5943929, ...",NaN
2,1315,"Holthesedijk, Overloon",Overloon,"‘t Schaartven is een voormalige zandwinplas, g...",NaN,NaN,'t Schaartven,'t Schaartven,goed,51.5735,5.9749,1,61.0,15.0,"[5943892, 5943916, 5943897, 5943900, 5943929, ...",NaN
3,1344,"Paralelleweg, Tynaarlo",Tynaarlo,De zwemlocatie ‟t Veenmeer is gelegen in Tynaa...,Recreatiezone_'t_Veenmeer.jpg,NaN,'t Veenmeer,'t Veenmeer,goed,53.0829,6.6303,1,61.0,15.0,"[5943901, 5943913, 5943906, 5943900, 5943895, ...",NaN
4,1291,"Witvenseweg, Veldhoven",Veldhoven,De zwemlocatie ligt ten zuiden van de gemeente...,NB-059-001 't Witven.jpg,http://www.witven.nl,Witven,'t Witven,goed,51.3979,5.4108,1,30.0,15.0,"[5943902, 5943930, 5943929, 5943892, 5943927, ...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,7941840,Kortgene,Kortgene,Door camping de Paardekreek aangelegd zandstra...,NaN,NaN,Paardekreek,Strand Kortgene Paardekreek,goed,51.5496,3.8096,2,15.0,15.0,NaN,NaN
745,7356682,,,strand zoutkamp in onderzoek,NaN,NaN,NaN,Strand Zoutkamp,goed,53.3388,6.2973,1,15.0,92.0,NaN,NaN
746,6837320,"Elfenbank 1, Blauwe stad",Blauwe stad,strand zuid oldambtmeer,Recreatiezone Zuid Blauwe Stad kopie-1.jpg,NaN,Strand Zuid,Strand Zuid Oldambtmeer,goed,53.1651,7.0372,3,77.0,30.0,"[5943927, 5943897, 5943892, 5943929, 5943916, ...",NaN
747,6997562,Brouwershaven,Brouwershaven,Strandje naast jachthaven van Brouwershaven,NaN,NaN,Brouwershaven,Strandje Brouwershaven,goed,51.7315,3.9154,1,77.0,15.0,NaN,NaN
748,1240,"Oude Raadhuislaan 154, Rotterdam",Rotterdam,t Zwarte Plasje,42__t_Zwarte_Plasje.jpg,NaN,'t Zwarte Plasje,'t Zwarte Plasje,goed,51.9593,4.4913,1,30.0,15.0,"[5943929, 5943902, 5943930, 5943892, 5943927, ...",NaN

In [31]:
data['amenities'] = data['amenities'].apply(lambda x: list(set(x)) if isinstance(x, (list, set, tuple)) else list())
data['warnings'] = data['warnings'].apply(lambda x: x if isinstance(x, (list, set, tuple)) else list())
data['e_coli'].fillna(0, inplace=True)
data['int_ent'].fillna(0, inplace=True)

/var/folders/c4/2j8ddht53cb4c_40b6_x0kq00000gn/T/ipykernel_54029/1236967452.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['e_coli'].fillna(0, inplace=True)
/var/folders/c4/2j8ddht53cb4c_40b6_x0kq00000gn/T/ipykernel_54029/1236967452.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['int_ent'].fillna(0, inplace=True)

0      15.0
1      15.0
2      15.0
3      15.0
4      15.0
       ...
744    15.0
745    92.0
746    30.0
747    15.0
748    15.0
Name: int_ent, Length: 749, dtype: float64

In [32]:
data.to_json('../../api/nl/locations.json', orient="records")

In [33]:
import json

for idx, row in data.iterrows():
    row_dict = row.to_dict()
    print(row_dict)
    filename = f'../../api/nl/locations/{row['id']}.json'
    with open(filename, 'w+') as f:
        json.dump(row_dict, f, indent=2)

{'id': 1259, 'address': 'Hoefsvenlaan, Waalwijk', 'placename': 'Waalwijk', 'description': 'De locatie ligt ten zuidoosten van Waalwijk. Er is geen actief toezicht.', 'photos': "NB-063-001 't Hoefsven.jpg", 'website': nan, 'alternate_name': "'t Hoefsven", 'name': "'t Hoefsven", 'current_status': 'goed', 'lat': 51.6761, 'lon': 5.0942, 'eu_designation': '1', 'e_coli': 15.0, 'int_ent': 15.0, 'amenities': [5943907, 5943911, 5943913, 5943916, 5943891, 5943892, 5943929, 5943930], 'warnings': []}
{'id': 1341, 'address': 'Bosweg, Gasselte', 'placename': 'Gasselte', 'description': 'De zwemlocatie “’t Nije Hemelriek” is gelegen in Gasselte. Het gehele oppervlak van de plas wordt gebruikt als zwemzone. Het strand gelegen rondom de plas heeft een omtrek van ca. 630m en heeft een breedte variërend van ca. 15-40m. De diepte van de plas is ca. 2,00 m', 'photos': "Recreatiezone_'t_Nije_Hemelriek.jpg", 'website': nan, 'alternate_name': "'t Nije Hemelriek", 'name': "'t Nije Hemelriek", 'current_status': 'goed', 'lat': 52.9725, 'lon': 6.7556, 'eu_designation': '1', 'e_coli': 30.0, 'int_ent': 15.0, 'amenities': [5943906, 5943907, 5943895, 5943911, 5943913, 5943916, 5943891, 5943892, 5943927, 5943896, 5943929, 5943930, 5943902], 'warnings': []}
{'id': 1315, 'address': 'Holthesedijk, Overloon', 'placename': 'Overloon', 'description': '‘t Schaartven is een voormalige zandwinplas, gelegen in de bossen tussen Overloon en de A73. De noordkant van de \r\nplas is ingericht voor zwemmen en de zuidkant van de plas is bestemd voor natuur. De plas is \r\nomgeven door bos.', 'photos': nan, 'website': nan, 'alternate_name': "'t Schaartven", 'name': "'t Schaartven", 'current_status': 'goed', 'lat': 51.5735, 'lon': 5.9749, 'eu_designation': '1', 'e_coli': 61.0, 'int_ent': 15.0, 'amenities': [5943911, 5943916, 5943929, 5943892, 5943898, 5943927, 5943897, 5943930, 5943900], 'warnings': []}
{'id': 1344, 'address': 'Paralelleweg, Tynaarlo', 'placename': 'Tynaarlo', 'description': 'De zwemlocatie ‟t Veenmeer is gelegen in Tynaarlo. De zwemlocatie ‟t Veenmeer is een geïsoleerde plas en heeft een  omvang van 100 bij 300 meter en een diepte van max. 18 meter', 'photos': "Recreatiezone_'t_Veenmeer.jpg", 'website': nan, 'alternate_name': "'t Veenmeer", 'name': "'t Veenmeer", 'current_status': 'goed', 'lat': 53.0829, 'lon': 6.6303, 'eu_designation': '1', 'e_coli': 61.0, 'int_ent': 15.0, 'amenities': [5943906, 5943907, 5943911, 5943927, 5943913, 5943916, 5943897, 5943891, 5943892, 5943893, 5943898, 5943895, 5943896, 5943929, 5943930, 5943900, 5943901, 5943902], 'warnings': []}
{'id': 1291, 'address': 'Witvenseweg, Veldhoven', 'placename': 'Veldhoven', 'description': 'De zwemlocatie ligt ten zuiden van de gemeente Veldhoven en is alleen voor de camping. De plas is 3,3 hectare groot, heeft een maximale diepte van zeven à acht meter en heeft een lemige zandbodem.', 'photos': "NB-059-001 't Witven.jpg", 'website': 'http://www.witven.nl', 'alternate_name': 'Witven', 'name': "'t Witven", 'current_status': 'goed', 'lat': 51.3979, 'lon': 5.4108, 'eu_designation': '1', 'e_coli': 30.0, 'int_ent': 15.0, 'amenities': [5943907, 5943911, 5943915, 5943916, 5943917, 5943897, 5943892, 5943898, 5943927, 5943929, 5943930, 5943902], 'warnings': []}
{'id': 7350900, 'address': "Slag Vlugtenburg, 's-Gravenzande", 'placename': "'s-Gravenzande", 'description': "Het badstrand van 's-Gravenzande", 'photos': '01i_1_s-Gravenzande_slag_Vlugtenburg.jpg', 'website': nan, 'alternate_name': "'s-Gravenzande", 'name': "'s-Gravenzande", 'current_status': 'goed', 'lat': 52.0126, 'lon': 4.1392, 'eu_designation': '1', 'e_coli': 94.0, 'int_ent': 30.0, 'amenities': [], 'warnings': []}
{'id': 6841460, 'address': 'Bosweg, Gasselte', 'placename': 'Gasselte', 'description': 'De zwemlocatie “’t Gasselterveld” is gelegen in Gasselte. Het noordoostelijk deel van de plas is verondiept en gelegen rond een eilandje. Dit deel wordt gebruikt als zwemzone. Het strand gelegen rondom het eiland heeft een omtrek van ca. 500m en heeft een breedte van ca. 100m. De diepte van de plas in de zwemzone is ca. 2,00 m. \r\n\r\nBuiten de zwemzone zeer diepe plas. Pas op! Verdrinkingsgevaar door onderkoeling door koude waterstromen.', 'photos': nan, 'website': nan, 'alternate_name': "'t Gasselterveld", 'name': "'t Gasselterveld", 'current_status': 'goed', 'lat': 52.9722, 'lon': 6.7498, 'eu_designation': '1', 'e_coli': 176.0, 'int_ent': 77.0, 'amenities': [5943906, 5943907, 5943895, 5943911, 5943913, 5943916, 5943891, 5943892, 5943898, 5943927, 5943896, 5943929, 5943930, 5943902], 'warnings': []}
{'id': 1029, 'address': 'Hilgeloweg, Winterswijk', 'placename': 'Winterswijk', 'description': 'Recreatiegebied ‟t Hilgelo ligt aan de noordzijde van Winterswijk. Het zwemwater ligt in een kleinschalig landschap, met voornamelijk graslanden en bosjes.', 'photos': 'GLD-019-001_HILGELO_BORD 2024.jpg', 'website': 'http://www.leisurelands.nl/', 'alternate_name': "'t Hilgelo Naaktstrand", 'name': "'t Hilgelo Naaktstrand", 'current_status': 'goed', 'lat': 51.9918, 'lon': 6.7242, 'eu_designation': '1', 'e_coli': 30.0, 'int_ent': 15.0, 'amenities': [5943904, 5943906, 5943907, 5943911, 5943912, 5943913, 5943915, 5943916, 5943919, 5943929, 5943892, 5943927, 5943897, 5943898, 5943902], 'warnings': []}
{'id': 1118, 'address': 'Havenstraat, Zijdewind', 'placename': 'Zijdewind', 'description': "'t Petje is een kleine waterplas tegen de dorpskern  van het dorpje Zijdewind aan. De plas  is privé-eigendom. 't Petje staat in directe verbinding met het boezemwater..", 'photos': "'t Petje.PNG", 'website': nan, 'alternate_name': "'t Petje", 'name': "'t Petje", 'current_status': 'goed', 'lat': 52.7392, 'lon': 4.8396, 'eu_designation': '4', 'e_coli': 312.0, 'int_ent': 110.0, 'amenities': [5943932, 5943906, 5943910, 5943913, 5943915, 5943897, 5943891, 5943923, 5943892, 5943930, 5943927, 5943929, 5943898, 5943900, 5943901], 'warnings': []}
{'id': 1114, 'address': 'Skarpetweg, Oude Niedorp', 'placename': 'Oude Niedorp', 'description': "'t Skarpet  is  een  relatief  kleine  zwemplas  van  ongeveer  één  hectare  groot, die ligt  aan  de  rand  de gemeente Niedorp. Het zwemwater, een inham van het kanaal Westerlangereis, is ontstaan door een zandafgraving. Er is een  strandje  aangelegd. De plas wordt  gebruikt  als  openluchtzwembad. Voor het zwembad gelden openingstijden.", 'photos': "'t Skarpet.PNG", 'website': nan, 'alternate_name': "'t Skarpet", 'name': "'t Skarpet", 'current_status': 'goed', 'lat': 52.7175, 'lon': 4.8725, 'eu_designation': '4', 'e_coli': 234.0, 'int_ent': 15.0, 'amenities': [5943932, 5943906, 5943907, 5943910, 5943911, 5943913, 5943915, 5943897, 5943891, 5943923, 5943892, 5943930, 5943927, 5943929, 5943898, 5943900, 5943901], 'warnings': []}
{'id': 1143, 'address': 'Zeeweg, Overveen', 'placename': 'Overveen', 'description': "'t Wed ligt in het nationale park Zuid-Kennemerland. Het meer is maximaal ongeveer 8 meter diep.", 'photos': 'tWed.PNG', 'website': nan, 'alternate_name': "'t Wed", 'name': "'t Wed", 'current_status': 'goed', 'lat': 52.3996, 'lon': 4.5898, 'eu_designation': '1', 'e_coli': 15.0, 'int_ent': 310.0, 'amenities': [5943907, 5943891, 5943892, 5943930, 5943927, 5943929, 5943898, 5943902], 'warnings': []}
{'id': 299241, 'address': 'Maastrichtsebaan 1, Alphen', 'placename': 'Alphen', 'description': "Zwemplas 't Zand wordt omgeven door bosgebied. De zwemlocatie heeft een langgerekt strand aan de noordoostzijde, waarlangs een ligweide is gelegen. Aan de zuidoostzijde is een smallere ligweide gelegen. Aan de zuidzijde is een strand gelegen dat gebruikt wordt door campinggasten van Recreatiepark 't Zand.", 'photos': "NB-002-001 't Zand.jpg", 'website': nan, 'alternate_name': "'t Zand", 'name': "'t Zand", 'current_status': 'goed', 'lat': 51.4993, 'lon': 4.9497, 'eu_designation': '1', 'e_coli': 15.0, 'int_ent': 15.0, 'amenities': [5943907, 5943911, 5943915, 5943916, 5943892, 5943927, 5943929, 5943930, 5943902], 'warnings': []}
{'id': 1249, 'address': "Fransebaan, 't Zand", 'placename': "'t Zand", 'description': 'nog in te vullen', 'photos': "NB-002-001 't Zand.jpg", 'website': nan, 'alternate_name': "'t Zand", 'name': "'t Zand Middenstrand", 'current_status': 'goed', 'lat': 51.4997, 'lon': 4.9532, 'eu_designation': '1', 'e_coli': 30.0, 'int_ent': 15.0, 'amenities': [5943907, 5943911, 5943913, 5943919, 5943891, 5943892, 5943927, 5943930, 5943902], 'warnings': []}
{'id': 1619, 'address': 'Aakvlaaiweg, Altena', 'placename': 'Altena', 'description': 'De Aakvlaai is een 150 hectare groot watersportgebied aan de zuidoostkant van de Biesbosch.', 'photos': nan, 'website': nan, 'alternate_name': nan, 'name': 'Aakvlaai, Badstrand', 'current_status': 'goed', 'lat': 51.7234, 'lon': 4.8646, 'eu_designation': '1', 'e_coli': 15.0, 'int_ent': 61.0, 'amenities': [5943907, 5943911, 5943891, 5943892, 5943929], 'warnings': []}
{'id': 1550, 'address': 'Drontermeerdijk, Dronten', 'placename': 'Dronten', 'description': 'Het Abbertstrand ligt aan het Drontermeer tussen de Roggebotsluis en de brug naar Elburg. Het strand ligt aan het Drontermeer en de Drontermeerdijk aan de westzijde van het meer. Bij het strand is het strandpaviljoen At Sea.', 'photos': 'DOCUVITP-#1332258-v1-12_067_Abbertstrand-1_pdf.jpg', 'website': 'https://www.atsea-restaurant.nl/', 'alternate_name': 'Abbertstrand', 'name': 'Abbertstrand', 'current_status': 'goed', 'lat': 52.5127, 'lon': 5.8547, 'eu_designation': '3', 'e_coli': 15.0, 'int_ent': 15.0, 'amenities': [5943907, 5943895, 5943911, 5943917, 5943921, 5943892, 5943927, 5943929, 5943930, 5943902], 'warnings': []}
{'id': 990, 'address': 'Agnietenbergweg, Zwolle', 'placename': 'Zwolle', 'description': 'Aan de rand van Zwolle, aan de Haersterveerweg ligt de Agnietenplas. Aan de westzijde is de \r\nplas omgeven door bosgebied en grenst de plas aan camping de Agnietenberg. Aan de oostzijde stroomt de Overijsselse Vecht.', 'photos': 'Informatiebord Agnietenplas Oost.png', 'website': 'https://www.zwolle.nl/vrije-tijd/sport/zwemplassen', 'alternate_name': 'Agnietenplas Oost', 'name': 'Agnietenplas Oost', 'current_status': 'goed', 'lat': 52.5407, 'lon': 6.1316, 'eu_designation': '3', 'e_coli': 179.0, 'int_ent': 15.0, 'amenities': [5943907, 5943911, 5943891, 5943892, 5943930, 5943927, 5943896, 5943929, 5943898, 5943902], 'warnings': []}
{'id': 991, 'address': 'Agnietenbergweg, Zwolle', 'placename': 'Zwolle', 'description': 'Aan de rand van Zwolle, aan de Haersterveerweg ligt de Agnietenplas. Aan de westzijde is de \r\nplas omgeven door bosgebied en grenst de plas aan camping de Agnietenberg. Aan de oostzij-\r\nde stroomt de Overijsselse Vecht', 'photos': 'Informatiebord Agnietenplas West.png', 'website': 'https://www.zwolle.nl/vrije-tijd/sport/zwemplassen', 'alternate_name': 'Agnietenplas West', 'name': 'Agnietenplas West', 'current_status': 'goed', 'lat': 52.5405, 'lon': 6.1291, 'eu_designation': '2', 'e_coli': 110.0, 'int_ent': 15.0, 'amenities': [5943907, 5943911, 5943891, 5943892, 5943930, 5943927, 5943929, 5943898, 5943900, 5943902], 'warnings': []}
{'id': 1051, 'address': 'Klaas Hoornlaan, Akersloot', 'placename': 'Akersloot', 'description': 'Even ten zuiden van Alkmaar ligt het Alkmaardermeer, het noordelijke deel van een plas waarvan het Uitgeestermeer het zuidelijke deel uitmaakt. Rondom het meer liggen verschillende recreatieterreinen (Dorregeest, De Hoorne, Uiterdam, De Woudhaven, Zwaansmeer en eiland Pannekoek).', 'photos': 'NH-043-001.PNG', 'website': nan, 'alternate_name': 'Akersloot', 'name': 'Akersloot', 'current_status': 'goed', 'lat': 52.5593, 'lon': 4.7437, 'eu_designation': '2', 'e_coli': 15.0, 'int_ent': 15.0, 'amenities': [5943907, 5943911, 5943913, 5943916, 5943892, 5943927, 5943930], 'warnings': []}
{'id': 978, 'address': 'Stasjonsleane, Oudega', 'placename': 'Oudega', 'description': 'Het zwemwater ligt vlak bij het dorpje Oudega aan de oostkant van het meer de Aldegeaster Brekken.', 'photos': 'bord Aldegeaster Brekken.png', 'website': nan, 'alternate_name': 'Aldegeaster Brekken', 'name': 'Aldegeaster Brekken', 'current_status': 'goed', 'lat': 52.9969, 'lon': 5.5443, 'eu_designation': '2', 'e_coli': 1100.0, 'int_ent': 390.0, 'amenities': [5943907, 5943910, 5943911, 5943913, 5943915, 5943916, 5943897, 5943891, 5943892, 5943898, 5943927, 5943929, 5943930, 5943932], 'warnings': []}
{'id': 1581, 'address': 'Ijmeerdijk, Almere', 'placename': 'Almere', 'description': 'Het Almeerderstrand is een groot strand met aan de zuidkant het evenementenstrand en het deel Hondenstrand. Dit deel van het Almeerderstrand ligt langs de A6 en de spoorlijn. Het overige deel van Almeerderstrand is vrij toegankelijk. Het Almeerderstrand is gelegen aan het IJmeer bij Almere,ten noorden van de Hollandse brug; Aan de noordzijde ligt de jachthaven Marina Muiderzand.', 'photos': 'Almeerderstrand[1] 2010.jpg', 'website': 'http://www.almere.nl/', 'alternate_name': 'Almeerderstrand', 'name': 'Almeerderstrand', 'current_status': 'goed', 'lat': 52.3346, 'lon': 5.14, 'eu_designation': '1', 'e_coli': 30.0, 'int_ent': 15.0, 'amenities': [5943907, 5943895, 5943917, 5943897, 5943921, 5943891, 5943892, 5943898, 5943927, 5943929, 5943930, 5943932, 5943902], 'warnings': []}
{'id': 304872, 'address': 'De Duizendmeterweg, Amstelveen', 'placename': 'Amstelveen', 'description': 'De Grote Speelweide ligt in het Amsterdamse Bos. De waterdiepte van de vijver varieert van 1 tot 1,5 meter.', 'photos': 'NH-089-001 Amsterdamse Bos.png', 'website': nan, 'alternate_name': 'Amsterdamse Bos', 'name': 'Amsterdamse Bos', 'current_status': 'goed', 'lat': 52.3197, 'lon': 4.8282, 'eu_designation': '2', 'e_coli': 15.0, 'int_ent': 61.0, 'amenities': [5943907, 5943911, 5943913, 5943892, 5943893, 5943898, 5943927, 5943930], 'warnings': []}
{'id': 6843230, 'address': 'Koopmanspolder, Andijk', 'placename': 'Andijk', 'description': 'Zwemstrand', 'photos': 'Andijk zwemstrand.PNG', 'website': nan, 'alternate_name': 'Andijk', 'name': 'Andijk', 'current_status': 'NEGATIEF_ZWEMADVIES', 'lat': 52.7397, 'lon': 5.1755, 'eu_designation': '3', 'e_coli': 230.0, 'int_ent': 45.0, 'amenities': [], 'warnings': []}
{'id': 1290, 'address': 'Ekkersweijer, Best', 'placename': 'Best', 'description': ' Aquabest is een recreatieterrein van circa 32 hectare groot. De zwemplas is daar een onderdeel van en beslaat circa 25 hectare. ', 'photos': 'NB-007-001 Aquabest.jpg', 'website': 'http://www.aquabest.nl/', 'alternate_name': 'Aquabest', 'name': 'Aquabest', 'current_status': 'goed', 'lat': 51.4967, 'lon': 5.4336, 'eu_designation': '1', 'e_coli': 77.0, 'int_ent': 30.0, 'amenities': [5943911, 5943892, 5943927, 5943898, 5943932, 5943902], 'warnings': []}
{'id': 1252, 'address': 'Rietdijk, Breda', 'placename': 'Breda', 'description': 'De Asterdplas bevat een zandstrand met daarachter een grote lig- en speelweide. De Asterdplas heeft een lokale recreatiefunctie.', 'photos': 'NB-011-001 De Asterdplas.jpg', 'website': 'http://www.vvvbreda.nl/nl/ontdek-breda/natuur-water/zwemmen-surfen-in-breda/asterdplas/452', 'alternate_name': 'Asterdplas', 'name': 'Asterdplas', 'current_status': 'goed', 'lat': 51.6273, 'lon': 4.7515, 'eu_designation': '2', 'e_coli': 61.0, 'int_ent': 46.0, 'amenities': [5943907, 5943911, 5943916, 5943892, 5943893, 5943898, 5943927, 5943929, 5943930, 5943902], 'warnings': []}
{'id': 1463, 'address': 'Zeedijk, Baarland', 'placename': 'Baarland', 'description': 'Baarland Badstrand is gelegen aan de noordelijke oever van de Westerschelde. De zwemlocatie is gelegen tegen de zeedijk', 'photos': 'Baarland badstrand (2).JPG', 'website': nan, 'alternate_name': 'Baarland Badstrand', 'name': 'Baarland Badstrand', 'current_status': 'goed', 'lat': 51.3939, 'lon': 3.8983, 'eu_designation': '2', 'e_coli': 15.0, 'int_ent': 46.0, 'amenities': [5943905, 5943906, 5943907, 5943913, 5943890, 5943891, 5943892, 5943927, 5943929, 5943931, 5943902, 5943903], 'warnings': []}
{'id': 1563, 'address': 'Westerdijk, Hindeloopen', 'placename': 'Hindeloopen', 'description': 'Zwemlocatie Badpaviljoen IJsselmeer te Hindeloopen ligt aan het IJsselmeer in de gemeente Súdwest Fryslân. Het zwemstrand strekt zich uit over een totale lengte van ongeveer 750 meter. Het strand bestaat uit zand en de ligweide bestaat uit gras. Het strand is direct gelegen aan de voet van de dijk en is maximaal slechts vijf meter breed.Bezoekers van de zwemlocatie kunnen op de binnendijks gelegen camping van sanitaire voorzieningen gebruik maken.', 'photos': 'Badpaviljoen IJsselmeer Hindeloopen.png', 'website': nan, 'alternate_name': 'Badpaviljoen Ijsselmeer', 'name': 'Badpaviljoen IJsselmeer', 'current_status': 'goed', 'lat': 52.9359, 'lon': 5.4021, 'eu_designation': '1', 'e_coli': 420.0, 'int_ent': 77.0, 'amenities': [5943907, 5943909, 5943911, 5943913, 5943892, 5943895, 5943929, 5943930, 5943932, 5943902], 'warnings': []}
{'id': 1462, 'address': 'Badweg 6, Oost-Vlieland', 'placename': 'Oost-Vlieland', 'description': 'Vlieland grenst aan de noordkant aan de Noordzee en aan de Waddenzee in het zuiden. De zwemlocatie is gelegen aan het Noordzeekust van Vlieland. Ten zuiden van de locatie, aan de Waddenzee, ligt het enige dorp: Oost-Vlieland.', 'photos': 'FR-001-001 Badstrand Badhuis.jpg', 'website': nan, 'alternate_name': 'Badstrand Badhuis', 'name': 'Badstrand Badhuis', 'current_status': 'goed', 'lat': 53.3051, 'lon': 5.0511, 'eu_designation': '1', 'e_coli': 30.0, 'int_ent': 20.0, 'amenities': [5943906, 5943907, 5943913, 5943914, 5943890, 5943892, 5943927, 5943929, 5943931, 5943900, 5943902, 5943903], 'warnings': []}
{'id': 8194200, 'address': 'Ballum', 'placename': 'Ballum', 'description': 'Zwemlocatie Badstrand Ballum is een zwemlocatie gelegen aan de noordzijde van Ameland. Het is gelegen aan de Noordzee op ca. 5 km ten noordwesten van Nes.\r\nHet is een open strand, met aan de zuidzijde duinen met duinvegetatie. Achter de duinen liggen landbouwgrond en een vakantiepark. Ten westen ligt het Groene Strand. \r\n\r\nDe lengte van het strand betreft ca. 250 m aan beide kanten van het paviljoen met uitkijktoren. Op de zwemlocatie is toezicht door het KNRM, tussen de 3e week van juni tot en met de 2e week van september. Voor het strand geldt een  paardenverbod tussen 07:00 en 19:00 uur. Honden aangelijnd toegestaan.', 'photos': nan, 'website': nan, 'alternate_name': 'Badstrand Ballum', 'name': 'Badstrand Ballum, Ameland', 'current_status': 'goed', 'lat': 53.4642, 'lon': 5.6959, 'eu_designation': 0, 'e_coli': 15.0, 'int_ent': 15.0, 'amenities': [5943906, 5943907, 5943913, 5943914, 5943929, 5943890, 5943891, 5943892, 5943925, 5943927, 5943897, 5943931, 5943900, 5943902, 5943903], 'warnings': []}
{'id': 1453, 'address': 'Strandweg, Buren', 'placename': 'Buren', 'description': 'De zwemlocatie Buren badstrand is gelegen aan de Noordzee op circa 1,5 km afstand ten noordoosten van het dorp Buren. Het strand is onbegroeid, alleen in de duinen komen duinvegetaties voor. Ten zuiden van zwemlocatie Buren badstrand zijn een aantal recreatieparken aanwezig. Achter de duinen liggen tevens een aantal landbouwgebieden.', 'photos': 'FR-006-001 Badstrand Buren.jpg', 'website': nan, 'alternate_name': 'Badstrand Buren', 'name': 'Badstrand Buren', 'current_status': 'goed', 'lat': 53.4626, 'lon': 5.8073, 'eu_designation': '1', 'e_coli': 15.0, 'int_ent': 15.0, 'amenities': [5943905, 5943906, 5943907, 5943913, 5943914, 5943897, 5943921, 5943890, 5943892, 5943926, 5943927, 5943929, 5943931, 5943900, 5943902, 5943903], 'warnings': []}

In [34]:
import sqlite3

sql_data = data.copy()
sql_data["amenities"] = sql_data["amenities"].astype(str)
sql_data["warnings"] = sql_data["warnings"].astype(str)
db = sqlite3.connect('../dataset.sqlite3')
sql_data.to_sql('locations', db, index=False, if_exists='append')

749

In [35]:
data.columns

Index(['id', 'address', 'placename', 'description', 'photos', 'website',
       'alternate_name', 'name', 'current_status', 'lat', 'lon',
       'eu_designation', 'e_coli', 'int_ent', 'amenities', 'warnings'],
      dtype='str')

# GeoJSON

In [36]:
from geojson import Feature, Point, FeatureCollection, dumps

ModuleNotFoundError: No module named 'geojson'

In [ ]:
collection = []

In [ ]:
for index, row in data.iterrows():
    print(row)
    feature = Feature(id=row['id'],
                      geometry=Point((row['lon'], row['lat'])),
                      properties={
        "name": row['name'],
        "alternate_name": row['alternate_name']
    })
    collection.append(feature)

In [ ]:
geojson = FeatureCollection(collection)

In [ ]:
with open("../../api/nl/map.geojson", "w") as outputGeoJson:
    outputGeoJson.write(dumps(geojson))

In [ ]:
from ipyleaflet import Map, Marker, GeoJSON
import random

center = (52.204793, 360.121558)

m = Map(center=center, zoom=15)

geo_json = GeoJSON(
    data=geojson,
    style={
        'color': 'black'
    }
)
m.layers = [m.layers[0], geo_json]
m

In [ ]:
unique_amenities = zwemplek_voorziening.copy()
unique_amenities = unique_amenities.drop_duplicates("code").drop(columns=['id', 'taal', 'zwemplek_id', 'zwemwaterlocatie_id', 'geometry'])
unique_amenities = unique_amenities[['voorziening_type_id', 'omschrijving', 'groep']].set_index('voorziening_type_id')
unique_amenities.to_csv('../../api/nl/amenities.csv')