In [21]:
import requests
from bs4 import BeautifulSoup
import re

In [22]:
url = 'https://sk.gis.gov.pl/kapieliska/mapa'

In [23]:
headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
        "Cookie": "visid_incap_3067075=1Md4PMHTRB21CSsHHqPe1aXZjGkAAAAAQUIPAAAAAAAmk/UrSsAD2Qb+bNg+MKrw; visid_incap_3067059=0ydXZ0VSTzyK5Skzd2yiHY/ZjGkAAAAAQkIPAAAAAACAClnCAVRX97ama6s29CcVxu8n9ud8rvar; incap_ses_431_3067075=EkxOV8sHGW36FQxgWjj7BXjejGkAAAAAq5n7HTzifxErP9D6DAgMsQ==; incap_ses_1686_3067059=mWIsHZERgwgk2/dHmOBlF3bhjGkAAAAAGhWYCkYfjTHpFzDOr3JhxQ==; csrf_sk_cookie=56107dec39188fa3a5b3bda3f876a4e5; sk_sess=1vl9ou6kkt85ubufao9sj6ivmeo5d9pd; incap_ses_431_3067059=1Nc4CBEzUWwIvyBgWjj7BffqjGkAAAAAJq3ETUC9WwMqmf23DOnTAg==; incap_ses_1229_3067059=00vAH7MfJBJjogCsFkkOEQvrjGkAAAAA11DJekuvpeK/QG1CAp6EiA==; incap_ses_1229_3067075=y7yOaoJztF0gIgGsFkkOEbXrjGkAAAAAjQS49vAqyWm+YKDhLaItYw=="
}
website = requests.get(url, headers=headers)

In [24]:
website.text

'<!DOCTYPE html>\n<html lang="pl">\n<head>\n    <meta charset="utf-8">\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    <meta property="og:title" content="Serwis Kąpieliskowy"/>\n    <meta property="og:image" content="pic/kolo.jpg"/>\n    <meta property="og:site_name" content="Serwis Kąpieliskowy - Główny Inspektorat Sanitarny"/>\n    <meta property="og:description"\n          content="Aktualny stan jakości wody w kąpieliskach publicznych. Serwis prowadzony przez Główny Inspektorat Sanitarny."/>\n    <META NAME="ROBOTS" CONTENT="INDEX,FOLLOW,ALL">\n    <META NAME="revisit-after" CONTENT="1 days">\n    <META NAME="description"\n          CONTENT="Aktualny stan jakości wody w kąpieliskach publicznych. Serwis prowadzony przez Główny Inspektorat Sanitarny.">\n    <META NAME="keywords" CONTENT="sanepid, woda, kąpielisko, plaża, zanieczyszczenie, jakość wody">\n    <meta name="deklaracja-dostępności" content="https://sk.gis.gov.pl/deklaracja_dostepnosci">\n    <title>Serwis Kąpieliskowy - Główny Inspektorat Sanitarny</title>\n    <link href="https://sk.gis.gov.pl/assets/uikit/css/uikit.min.css" rel="stylesheet" type="text/css" />\n    <script src="https://sk.gis.gov.pl/assets/uikit/js/uikit.min.js"></script>\n\n    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />\n    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>\n\n\n    <link href="https://sk.gis.gov.pl/public/style.css" rel="stylesheet" type="text/css" />\n    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n    <!-- WARNING: Respond.js doesn\'t work if you view the page via file:// -->\n    <!--[if lt IE 9]>\n    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>\n    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>\n    <![endif]-->\n    <script src="https://sk.gis.gov.pl/assets/jquery-3.7.1.min.js"></script>\n    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>\n    <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">\n    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">\n    <script>\n        $(function () {\n            $("#tabs").tabs();\n        });\n    </script>\n\n            <link rel="icon" href="favicon.ico" type="image/x-icon"/>\n        <link rel="shortcut icon" href="https://sk.gis.gov.pl/pic/favicon.ico" type="image/x-icon"/>\n        <link rel="image_src" href="https://sk.gis.gov.pl/pic/kolo.jpg"/>\n\n\n        <script>\n            (function (i, s, o, g, r, a, m) {\n                i[\'GoogleAnalyticsObject\'] = r;\n                i[r] = i[r] || function () {\n                    (i[r].q = i[r].q || []).push(arguments)\n                }, i[r].l = 1 * new Date();\n                a = s.createElement(o),\n                    m = s.getElementsByTagName(o)[0];\n                a.async = 1;\n                a.src = g;\n                m.parentNode.insertBefore(a, m)\n            })(window, document, \'script\', \'https://www.google-analytics.com/analytics.js\', \'ga\');\n\n            ga(\'create\', \'UA-102013406-1\', \'auto\');\n            ga(\'send\', \'pageview\');\n        </script>\n        </head>\n<body onLoad="javascript:init();">\n<div class="uk-grid uk-flex-center head" data-uk-grid>\n    <div class="uk-width-1-1@s uk-width-3-4@m uk-width-2-3@l uk-width-2-3@xl">\n        <div class="uk-grid uk-flex-middle uk-margin" data-uk-grid>\n            <div class="uk-width-expand">\n                <a href="https://sk.gis.gov.pl/"><img src="https://sk.gis.gov.pl/img/sk.svg" width="400" style="margin-top: 10px; margin-bottom: 5px;" alt="" /></a>            </div>\n            <div class="uk-width-auto uk-flex-middle uk-visible@m">\n                <img src="https://sk.gis.gov.pl/img/gis.png" alt="" />            </div>\n        </div>\n    </div>\n</div>\n\n<div class="uk-grid uk-flex-center uk-margin-remove" data-uk-grid style="background-color: #2980b9;">\n    <div class="uk-width-1-1@s uk-width-3-4@m uk-width-2-3@l uk-width-2-3@xl uk-padding-remove"\n         style="background-color: #2980b9; margin: 10px;">\n        <nav class="uk-navbar-container" data-uk-navbar style="background-color: #2980b9">\n            <div class="uk-navbar-left">\n                <ul class="uk-navbar-nav">\n                    <li class="uk-active">\n                        <a href="https://sk.gis.gov.pl/kapieliska" style="min-height: 40px; height: auto; padding: 15px;">Kąpieliska</a>                    </li>\n                    <li>\n                        <a href="https://sk.gis.gov.pl/informacje" style="min-height: 40px; height: auto; padding: 15px;">Informacje</a>                    </li>\n                    <li class="uk-hidden@m">\n                        <a href="#modal_szukaj" data-uk-toggle style="min-height: 40px; height: auto; padding: 15px;\n">Szukaj</a>\n                    </li>\n                </ul>\n            </div>\n            <div class="uk-navbar-right uk-visible@m">\n                <ul class="uk-navbar-nav">\n                    <li>\n                        <button type="button" class="uk-button uk-button-default"\n                                style="height: auto; color: #fff; line-height: 30px;"\n                                data-uk-toggle="target: #modal_szukaj"><span\n                                    class="uk-visible@m">SZUKAJ KĄPIELISKA </span><span\n                                    data-uk-icon="icon: search"></span></button>\n                    </li>\n                </ul>\n            </div>\n        </nav>\n    </div>\n</div>\n\n<div id="modal_szukaj" data-uk-modal>\n    <div class="uk-modal-dialog uk-modal-body">\n        <form action="https://sk.gis.gov.pl/kapieliska" method="post" accept-charset="utf-8">\n<input type="hidden" name="csrf_sk_token" value="56107dec39188fa3a5b3bda3f876a4e5" />                              \n        <button class="uk-modal-close-outside" type="button" data-uk-close></button>\n        <h2 class="uk-modal-title">Szukaj kąpielisk</h2>\n        <div class="uk-margin"><div class="uk-form-controls"><input class="uk-input" type="text" id="szukaj" name="szukaj" placeholder="Wpisz szukaną frazę..." value=""></div></div>        <p class="uk-text-right uk-margin-remove-bottom">\n            <button class="uk-button uk-button-default uk-button-small uk-modal-close" type="button">Zamknij</button>\n            <button class="uk-button uk-button-primary uk-button-small" type="submit">Szukaj</button>\n        </p>\n        </form>    </div>\n</div>\n<div class="uk-grid uk-flex-center uk-margin-small-top" data-uk-grid>\n    <div class="uk-width-1-1@s uk-width-3-4@m uk-width-2-3@l uk-width-2-3@xl">\n        <div class="uk-panel uk-panel-box uk-panel-box-secondary">\n            <div class="uk-grid" data-uk-grid>\n                <div class="uk-width-expand uk-margin-small-left">\n                    <h1 class="uk-margin-small-bottom">Kąpieliska</h1>\n                    <p class="uk-margin-remove-bottom">Znalezionych kąpielisk dla frazy "<b>gdansk</b>": 709</p><form action="https://sk.gis.gov.pl/kapieliska/mapa" method="post" accept-charset="utf-8">\n<input type="hidden" name="szukaj" value="" />\n                                    <input type="hidden" name="csrf_sk_token" value="56107dec39188fa3a5b3bda3f876a4e5" />\n                        <button type="submit" class="uk-button uk-button-link"><span data-uk-icon="close"></span> Anuluj\n                            wyszukiwanie\n                        </button>\n                                        </div>\n                <div class="uk-width-auto uk-hidden@m uk-text-right uk-margin-small-right">\n                    <a href="https://sk.gis.gov.pl/kapieliska/lista" class="uk-text-small">Pokaż<br>jako listę</a>                </div>\n                <div class="uk-width-auto uk-visible@m">\n                    <a href="https://sk.gis.gov.pl/kapieliska/lista" class="uk-button uk-button-default" title="Wyświetl listę kąpielisk"><span data-uk-icon="icon: list"></span><span class="uk-visible@m"> Lista</span></a><a href="https://sk.gis.gov.pl/kapieliska/mapa" class="uk-button uk-button-primary" title="Wyświetl mapę kąpielisk"><span data-uk-icon="icon: world"></span><span class="uk-visible@m"> Mapa</span></a>                </div>\n            </div>\n            <div class="uk-margin-small-top" id="map_osm" style="height:800px;max-height: 70vw;" data-uk-observe></div>                            </div>\n    </div>\n</div>\n\n\n\n\n    <script>\n\n        // START OSM\n\n        function init() {\n            var map = new L.Map(\'map_osm\');\n            L.tileLayer(\'https://osm.gis.gov.pl/hot/{z}/{x}/{y}.png\', {\n                attribution: \'Główny Inspektorat Sanitarny &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors\',\n                maxZoom: 18\n            }).addTo(map);\n            map.attributionControl.setPrefix(\'\');\n\n            \n            var center = new L.LatLng(52.10894511, 19.0467275);\n            map.setView(center, 7);\n\n            var markers = [\n                [ 20.746390, 50.593610, "<div><b>Andrzejówka</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Andrzejówka, pow. kielecki, woj. świętokrzyskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 29/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/890\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 23.5229, 51.4954, "<div><b>Astur</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Okuninka, pow. włodawski, woj. lubelskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 22/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/691\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 17.861111, 50.771667, "<div><b>Balaton</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Dobrzeń Wielki, pow. opolski, woj. opolskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 26/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/746\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 21.786360, 53.971390, "<div><b>&#x1F6A9; Baza Harcerska Hufca ZHP w Bielsku Podlaskim</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Rydzewo, pow. giżycki, woj. warmińsko-mazurskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 04/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/920\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 21.9436, 54.1305, "<div><b>Baza Obozowa Hufca ZHP Otwock w Przerwankach</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Przerwanki, pow. węgorzewski, woj. warmińsko-mazurskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 31/07/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/692\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 19.071835, 50.810451, "<div><b>Bałtyk - Adriatyk</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Częstochowa, pow. Częstochowa, woj. śląskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 22/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/721\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 23.3003, 51.0877, "<div><b>Biały Rów</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Rejowiec, pow. chełmski, woj. lubelskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 20/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/537\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 16.590070, 50.681440, "<div><b>Bielawa - Camping Sudety</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Bielawa, pow. dzierżoniowski, woj. dolnośląskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 26/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/907\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 16.594439, 50.678641, "<div><b>Bielawa - Kąpielisko Sudecka Plaża</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Bielawa, pow. dzierżoniowski, woj. dolnośląskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 29/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/328\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 16.3342, 54.3997, "<div><b>&#x1F6A9; Bobolin Wschód</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Bobolin, pow. sławieński, woj. zachodniopomorskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 14/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div 

In [25]:
soup = BeautifulSoup(website.text, "html.parser")
scripts = soup.find_all("script")
map = scripts[-2].text

In [26]:
map

'\n\n        // START OSM\n\n        function init() {\n            var map = new L.Map(\'map_osm\');\n            L.tileLayer(\'https://osm.gis.gov.pl/hot/{z}/{x}/{y}.png\', {\n                attribution: \'Główny Inspektorat Sanitarny &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors\',\n                maxZoom: 18\n            }).addTo(map);\n            map.attributionControl.setPrefix(\'\');\n\n            \n            var center = new L.LatLng(52.10894511, 19.0467275);\n            map.setView(center, 7);\n\n            var markers = [\n                [ 20.746390, 50.593610, "<div><b>Andrzejówka</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Andrzejówka, pow. kielecki, woj. świętokrzyskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 29/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/890\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 23.5229, 51.4954, "<div><b>Astur</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Okuninka, pow. włodawski, woj. lubelskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 22/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/691\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 17.861111, 50.771667, "<div><b>Balaton</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Dobrzeń Wielki, pow. opolski, woj. opolskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 26/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/746\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 21.786360, 53.971390, "<div><b>&#x1F6A9; Baza Harcerska Hufca ZHP w Bielsku Podlaskim</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Rydzewo, pow. giżycki, woj. warmińsko-mazurskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 04/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/920\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 21.9436, 54.1305, "<div><b>Baza Obozowa Hufca ZHP Otwock w Przerwankach</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Przerwanki, pow. węgorzewski, woj. warmińsko-mazurskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 31/07/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/692\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 19.071835, 50.810451, "<div><b>Bałtyk - Adriatyk</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Częstochowa, pow. Częstochowa, woj. śląskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 22/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/721\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 23.3003, 51.0877, "<div><b>Biały Rów</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Rejowiec, pow. chełmski, woj. lubelskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 20/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/537\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 16.590070, 50.681440, "<div><b>Bielawa - Camping Sudety</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Bielawa, pow. dzierżoniowski, woj. dolnośląskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 26/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/907\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 16.594439, 50.678641, "<div><b>Bielawa - Kąpielisko Sudecka Plaża</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Bielawa, pow. dzierżoniowski, woj. dolnośląskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 29/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/328\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 16.3342, 54.3997, "<div><b>&#x1F6A9; Bobolin Wschód</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Bobolin, pow. sławieński, woj. zachodniopomorskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 14/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/414\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 16.3256, 54.3926, "<div><b>&#x1F6A9; Bobolin Zachód</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Bobolin, pow. sławieński, woj. zachodniopomorskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 14/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/415\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 20.329255, 50.052753, "<div><b>&#x1F6A9; Bobrowe Rozlewisko</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Zabierzów Bocheński, pow. wielicki, woj. małopolskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 21/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/729\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 17.938333, 50.644444, "<div><b>Bolko</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Opole, pow. Opole, woj. opolskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 22/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/591\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 20.7576, 50.7695, "<div><b>Borków</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Borków, pow. kielecki, woj. świętokrzyskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 22/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/717\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 16.3702, 50.5025, "<div><b>Botanica Active Park w Radkowie</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Radków, pow. kłodzki, woj. dolnośląskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 11/09/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/12\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 19.4522, 52.4236, "<div><b>Bratoszewo</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Gostynin, pow. gostyniński, woj. mazowieckie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 14/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/731\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 17.9897, 53.5077, "<div><b>Bysław</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Bysław, pow. tucholski, woj. kujawsko-pomorskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 22/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/23\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 20.524970, 50.031420, "<div><b>C.A.W. Borek</b></div><div style=\\"margin-top: 5px;\\"><b>Adres:</b><br>Borek, pow. bocheński, woj. małopolskie</div><div style=\\"margin-top: 5px;\\"></div><div style=\\"margin-top: 5px;\\"></div><div class=\\"uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom\\" data-uk-alert style=\\"padding: 5px !important;\\"><div class=\\"uk-grid uk-margin-small\\" data-uk-grid><div class=\\"uk-width-auto\\"><img src=\\"https://sk.gis.gov.pl/img/plywanie_dozwolone.png\\" alt=\\"\\" /></div><div class=\\"uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle\\">Woda przydatna do kąpieli<br>Ocena z dnia 27/08/2025</div></div></div><hr style=\\"margin: 10px 0 10px 0;\\"><div class=\\"uk-grid\\" data-uk-grid><div class=\\"uk-width-expand uk-flex uk-flex-middle uk-text-bold\\"></div><div class=\\"uk-width-auto uk-flex uk-flex-middle\\"><a href=\\"https://sk.gis.gov.pl/kapielisko/932\\" class=\\"uk-button uk-button-default uk-button-small\\">Pełny raport</a></div></div>", "gray" ],\n[ 16.2154, 53.6096, "<div><b>Camp Drawa na je

In [27]:
regex = r"var markers = (\[\n.*\],\n.\s\s\s\s\s\s\s\s\s\s\s\s\])"
test = re.search(regex, map, re.DOTALL)
if test:
    scraped_data = test.group(1)
else:
    print("No match")

In [28]:
import json5

In [43]:
scraped_dataset = json5.loads(scraped_data)

In [44]:
scraped_dataset

[[20.74639,
  50.59361,
  '<div><b>Andrzejówka</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Andrzejówka, pow. kielecki, woj. świętokrzyskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 29/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/890" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [23.5229,
  51.4954,
  '<div><b>Astur</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Okuninka, pow. włodawski, woj. lubelskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 22/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/691" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [17.861111,
  50.771667,
  '<div><b>Balaton</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Dobrzeń Wielki, pow. opolski, woj. opolskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 26/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/746" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [21.78636,
  53.97139,
  '<div><b>&#x1F6A9; Baza Harcerska Hufca ZHP w Bielsku Podlaskim</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Rydzewo, pow. giżycki, woj. warmińsko-mazurskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 04/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/920" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [21.9436,
  54.1305,
  '<div><b>Baza Obozowa Hufca ZHP Otwock w Przerwankach</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Przerwanki, pow. węgorzewski, woj. warmińsko-mazurskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 31/07/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/692" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [19.071835,
  50.810451,
  '<div><b>Bałtyk - Adriatyk</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Częstochowa, pow. Częstochowa, woj. śląskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 22/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/721" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [23.3003,
  51.0877,
  '<div><b>Biały Rów</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Rejowiec, pow. chełmski, woj. lubelskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 20/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/537" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [16.59007,
  50.68144,
  '<div><b>Bielawa - Camping Sudety</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Bielawa, pow. dzierżoniowski, woj. dolnośląskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 26/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/907" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [16.594439,
  50.678641,
  '<div><b>Bielawa - Kąpielisko Sudecka Plaża</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Bielawa, pow. dzierżoniowski, woj. dolnośląskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 29/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/328" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [16.3342,
  54.3997,
  '<div><b>&#x1F6A9; Bobolin Wschód</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Bobolin, pow. sławieński, woj. zachodniopomorskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 14/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/414" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [16.3256,
  54.3926,
  '<div><b>&#x1F6A9; Bobolin Zachód</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Bobolin, pow. sławieński, woj. zachodniopomorskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 14/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/415" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [20.329255,
  50.052753,
  '<div><b>&#x1F6A9; Bobrowe Rozlewisko</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Zabierzów Bocheński, pow. wielicki, woj. małopolskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 21/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/729" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [17.938333,
  50.644444,
  '<div><b>Bolko</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Opole, pow. Opole, woj. opolskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 22/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/591" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [20.7576,
  50.7695,
  '<div><b>Borków</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Borków, pow. kielecki, woj. świętokrzyskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 22/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/717" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [16.3702,
  50.5025,
  '<div><b>Botanica Active Park w Radkowie</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Radków, pow. kłodzki, woj. dolnośląskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 11/09/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/12" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [19.4522,
  52.4236,
  '<div><b>Bratoszewo</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Gostynin, pow. gostyniński, woj. mazowieckie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 14/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/731" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [17.9897,
  53.5077,
  '<div><b>Bysław</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Bysław, pow. tucholski, woj. kujawsko-pomorskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 22/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/23" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [20.52497,
  50.03142,
  '<div><b>C.A.W. Borek</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Borek, pow. bocheński, woj. małopolskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 27/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/932" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [16.2154,
  53.6096,
  '<div><b>Camp Drawa na jeziorze Żerdno</b></div><div style="margin-top: 5px;"><b>Adres:</b><br>Stare Drawsko, pow. drawski, woj. zachodniopomorskie</div><div style="margin-top: 5px;"></div><div style="margin-top: 5px;"></div><div class="uk-alert-success uk-padding-remove uk-margin-small-top uk-margin-small-bottom" data-uk-alert style="padding: 5px !important;"><div class="uk-grid uk-margin-small" data-uk-grid><div class="uk-width-auto"><img src="https://sk.gis.gov.pl/img/plywanie_dozwolone.png" alt="" /></div><div class="uk-width-expand uk-padding-remove uk-margin-small-left uk-flex uk-flex-middle">Woda przydatna do kąpieli<br>Ocena z dnia 08/08/2025</div></div></div><hr style="margin: 10px 0 10px 0;"><div class="uk-grid" data-uk-grid><div class="uk-width-expand uk-flex uk-flex-middle uk-text-bold"></div><div class="uk-width-auto uk-flex uk-flex-middle"><a href="https://sk.gis.gov.pl/kapielisko/377" class="uk-button uk-button-default uk-button-small">Pełny raport</a></div></div>',
  'gray'],
 [23.2061,
  53.9119,

In [45]:
import pandas as pd

In [46]:
df = pd.DataFrame(
    scraped_dataset,
    columns=["lon", "lat", "html", "color"]
)

In [47]:
df

,lon,lat,html,color
0,20.746390,50.593610,"<div><b>Andrzejówka</b></div><div style=""margi...",gray
1,23.522900,51.495400,"<div><b>Astur</b></div><div style=""margin-top:...",gray
2,17.861111,50.771667,"<div><b>Balaton</b></div><div style=""margin-to...",gray
3,21.786360,53.971390,<div><b>&#x1F6A9; Baza Harcerska Hufca ZHP w B...,gray
4,21.943600,54.130500,<div><b>Baza Obozowa Hufca ZHP Otwock w Przerw...,gray
...,...,...,...,...
704,15.899100,51.121800,<div><b>Złotoryja - Kąpielisko Zalew Złotoryja...,gray
705,16.249200,52.513300,"<div><b>Łazienki</b></div><div style=""margin-t...",gray
706,16.200778,54.312667,"<div><b>Łazy 223B</b></div><div style=""margin-...",gray
707,16.205500,54.315600,"<div><b>Łazy 224</b></div><div style=""margin-t...",gray
708,16.189934,54.307902,"<div><b>Łazy 225B</b></div><div style=""margin-...",gray

In [39]:
def collect_name(row):
    name_pattern = r"<div><b>(.*)</b></div>"
    flag_pattern = r"&#x1F6A9;"

    name = re.findall(name_pattern, row['html'])
    name = name[0].strip()
    name = re.sub(flag_pattern, '', name)
    name = re.sub('\"', '', name)

    return name

def collect_url(row):
    url_pattern = r"https:\/\/sk.gis.gov.pl\/kapielisko\/\d+"
    url = re.findall(url_pattern, row['html'])
    
    return url[0]

def collect_id(row):
    id = ""
    url = collect_url(row)
    if len(url) > 0:
        return url.split('/')[4]
    else:
        return None

def collect_status(row):
    status = True
    unsuitable = "nieprzydatna"

    if row['html'].find(unsuitable) > 0:
        status = False
    return status

In [48]:
df['name'] = df.apply(collect_name, axis=1)
df['alternate_name'] = df.apply(lambda x: x['name'], axis=1)
df['id'] = df.apply(collect_id, axis=1)
df['url'] = df.apply(collect_url, axis=1)
df = df[["id", "name", "alternate_name", "lat", "lon"]]
df

,id,name,alternate_name,lat,lon
0,890,Andrzejówka,Andrzejówka,50.593610,20.746390
1,691,Astur,Astur,51.495400,23.522900
2,746,Balaton,Balaton,50.771667,17.861111
3,920,Baza Harcerska Hufca ZHP w Bielsku Podlaskim,Baza Harcerska Hufca ZHP w Bielsku Podlaskim,53.971390,21.786360
4,692,Baza Obozowa Hufca ZHP Otwock w Przerwankach,Baza Obozowa Hufca ZHP Otwock w Przerwankach,54.130500,21.943600
...,...,...,...,...,...
704,776,Złotoryja - Kąpielisko Zalew Złotoryja,Złotoryja - Kąpielisko Zalew Złotoryja,51.121800,15.899100
705,225,Łazienki,Łazienki,52.513300,16.249200
706,756,Łazy 223B,Łazy 223B,54.312667,16.200778
707,399,Łazy 224,Łazy 224,54.315600,16.205500
708,807,Łazy 225B,Łazy 225B,54.307902,16.189934