In [18]:
import requests
import pandas as pd

In [19]:
url = "https://vrtlac.izor.hr/ords/kakvoca/kakvoce_sve_json?p_jezik=en"

In [20]:
data = requests.get(url)

In [21]:
data = pd.json_normalize(data.json()['markers'])
data = data[[
    'lat', 'lng', 'lsta', 'lpla'
]]
data

            lat        lng   lsta                             lpla
0     44.860680  13.804455   7281  Valovine-ispred Golubove špilje
1     44.786122  13.916915   7280         Premantura-Uvala Školjić
2     44.785738  13.905359   7279           Premantura-Uvala Polje
3     44.920000  14.028889   7277                  Punta kod sidra
4     44.901670  13.809440   7276                        Hidrobaza
...         ...        ...    ...                              ...
1139  45.615022  15.479858  11031                       Kupa Ozalj
1140  45.228333  15.225556  11021                  jezero Sabljaci
1141  45.484200  15.559600  11011        Korana Foginovo kupalište
1142  45.420278  15.482222  11002          Mrežnica Mrežnički Brig
1143  45.445097  15.504646  11001               Mrežnica Duga Resa

[1144 rows x 4 columns]

In [22]:
data.rename(mapper={
    "lsta": "id",
    "lpla": "name",
    "lng": "lon"
}, axis=1, inplace=True)

In [23]:
data = data[[
    "id", "name", "lat", "lon"
]]
data

         id                             name        lat        lon
0      7281  Valovine-ispred Golubove špilje  44.860680  13.804455
1      7280         Premantura-Uvala Školjić  44.786122  13.916915
2      7279           Premantura-Uvala Polje  44.785738  13.905359
3      7277                  Punta kod sidra  44.920000  14.028889
4      7276                        Hidrobaza  44.901670  13.809440
...     ...                              ...        ...        ...
1139  11031                       Kupa Ozalj  45.615022  15.479858
1140  11021                  jezero Sabljaci  45.228333  15.225556
1141  11011        Korana Foginovo kupalište  45.484200  15.559600
1142  11002          Mrežnica Mrežnički Brig  45.420278  15.482222
1143  11001               Mrežnica Duga Resa  45.445097  15.504646

[1144 rows x 4 columns]