In [1]:
import requests
import pandas
from io import StringIO
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

In [2]:
url = "https://vtiav.sm.ee/index.php/opendata/supluskohad.xml"

In [3]:
data = requests.get(url).text

In [4]:
df = pandas.read_xml(
    StringIO(data),
    xpath=".//supluskoht"  # assumes each bathing site is under <supluskoht>
)

coords = pandas.read_xml(
    StringIO(data),
    xpath=".//supluskoht/koordinaadid/koordinaat"
)

# If multiple coordinates per site exist, take the first
coords = coords.groupby(coords.index).first().reset_index(drop=True)

# Combine and clean
result = pandas.DataFrame({
    "id": df["id"],
    "name": df["nimetus"],
    "x": coords["x"],
    "y": coords["y"],
    "address": df["aadress"]
})
result

,id,name,x,y,address
0,328,Aablahe rand,6605088.70,586304.150,"Mardi, 74717 Kolga-Aabla küla, Kuusalu vald, H..."
1,124,Aafrika rand,6533928.61,472585.550,"Haapsalu linn, Haapsalu linn"
2,461,Aa rand,6513518.06,630068.432,"Aa küla, Lüganuse vald, Ida-Viru maakond"
3,464,Aidu karjääri supluskoht,6545887.55,696748.430,"Paadi, 42305 Aidu küla, Lüganuse vald, Ida-Vir..."
4,86,Aidu tehisjärve supluskoht,6568002.82,575962.930,"Aidu küla, Põltsamaa vald, Jõgeva maakond"
...,...,...,...,...,...
208,376,Viitna Pikkjärv,NaN,NaN,"Loobu metskond 71, 45202 Viitna küla, Kadrina ..."
209,74,Viljandi järve supluskoht,NaN,NaN,Viljandi linn
210,499,Võnnu paisjärv,NaN,NaN,"Võnnu alevik, Kastre vald, Tartu maakond"
211,340,"Võrtsjärve, Trepimäe supluskoht",NaN,NaN,"Trepimäe puhkeala, 61117 Vehendi küla, Elva va..."
212,104,Võsu supluskoht,NaN,NaN,"Võsu alevik, Haljala vald, Lääne-Viru maakond"

In [5]:
locator = Nominatim(user_agent='zwemwater', timeout=10)
geocode = RateLimiter(locator.geocode, min_delay_seconds=1)

In [6]:
from tqdm.notebook import tqdm

tqdm.pandas()
geocodeDF = result[result['x'].isna()]
geocodeDF['location'] = geocodeDF['address'].progress_apply(geocode)
geocodeDF

  0%|          | 0/51 [00:00<?, ?it/s]

,id,name,x,y,address,location
162,232,Roosna-Alliku tehisjärv,NaN,NaN,"Järve, 73203 Allikjärve küla, Paide linn","(Järve, Kaltenbrunni matkarada, Allikjärve kül..."
163,155,Roosta rand,NaN,NaN,"Elbiku küla / Ölbäck, Lääne-Nigula vald, Lääne...","(Elbiku küla / Ölbäck, Lääne-Nigula vald, Lään..."
164,249,Ropka järv,NaN,NaN,"Külitse alevik, Kambja vald, Tartu maakond","(Külitse alevik, Kambja vald, Tartu maakond, 6..."
165,178,Rõuge Suurjärve supluskoht,NaN,NaN,"Suurjärv, Rõuge alevik, Rõuge vald, Võru maakond","(Suurjärv, Rõuge alevik, Rõuge, Rõuge vald, Võ..."
166,82,Saadjärve Kukulinna,NaN,NaN,"Kukulinna küla, Tartu vald, Tartu maakond","(Kukulinna küla, Tartu vald, Tartu maakond, 60..."
167,85,Saadjärve Tabivere supluskoht,NaN,NaN,"Tabivere alevik, Tartu vald, Tartu maakond","(Tabivere alevik, Tartu vald, Tartu maakond, 4..."
168,226,Salmistu ranna parempoolne ala,NaN,NaN,"Salmistu küla, Kuusalu vald, Harju maakond","(Salmistu küla, Kuusalu vald, Harju maakond, 7..."
169,128,Sillamäe supluskoht,NaN,NaN,Sillamäe linn,"(Sillamäe linn, Ida-Viru maakond, Eesti, (59.3..."
170,148,Sindi väliujula (Pärnu jõgi),NaN,NaN,"Sindi linn, Tori vald, Pärnu maakond","(Sindi linn, Tori vald, Pärnu maakond, Eesti, ..."
171,210,Suure-Jaani paisjärv,NaN,NaN,"Suure-Jaani linn, Põhja-Sakala vald, Viljandi ...","(Suure-Jaani linn, Põhja-Sakala vald, Viljandi..."
172,331,Tambre paisjärve supluskoht,NaN,NaN,"Tambre tee, Valga linn, Valga vald, Valga maakond","(Tambre tee, Tambre, Valga linn, Valga vald, V..."
173,76,Tamula järve rand,NaN,NaN,"Tamula rand, Võru linn","(Tamula supelrand, Kesklinn, Võru linn, Võru m..."
174,102,Tarbja tehisjärv,NaN,NaN,"Tarbja tehisjärv, 72759 Tarbja küla, Paide linn",None
175,466,TEST Kooraste Pikkjärv,NaN,NaN,"Maidla küla, Märjamaa vald, Rapla maakond","(Maidla küla, Märjamaa vald, Rapla maakond, Ee..."
176,125,Toila rand,NaN,NaN,"Toila alevik, Jõhvi vald, Ida-Viru maakond","(Toila alevik, Toila, Jõhvi vald, Ida-Viru maa..."
177,207,Tõravere keskmine tiik,NaN,NaN,"Tõravere alevik, Nõo vald, Tartu maakond","(Tõravere alevik, Nõo vald, Tartu maakond, 616..."
178,206,Tõravere suur tiik,NaN,NaN,"Observatooriumi tn 5, Tõravere alevik, Nõo val...",None
179,290,Torma järv,NaN,NaN,"Torma alevik, Jõgeva vald, Jõgeva maakond","(Torma alevik, Jõgeva vald, Jõgeva maakond, 48..."
180,145,Tõrvanina supluskoht,NaN,NaN,"Tareste küla, Hiiumaa vald, Hiiu maakond","(Tareste küla, Hiiumaa vald, Hiiu maakond, Ees..."
181,228,Tsitre rand,NaN,NaN,"Tsitre küla, Kuusalu vald, Harju maakond","(Tsitre küla, Kuusalu vald, Harju maakond, 746..."
182,167,Tuhkana supluskoht,NaN,NaN,"Saaremaa vald, Saare maakond","(Saaremaa vald, Saare maakond, Eesti, (58.2738..."
183,95,Türi tehisjärv,NaN,NaN,"Tehisjärve, 72213 Türi linn, Türi vald, Järva ...",None
184,198,Ujumiskoht Üügu panga juures,NaN,NaN,"Kallaste küla, Muhu vald, Saare maakond","(Kallaste küla, Muhu vald, Saare maakond, 9474..."
185,418,Uueveski bassein,NaN,NaN,"Musta, 71073 Peetrimõisa küla, Viljandi vald, ...","(Musta tee, Uueveski, Peetrimõisa küla, Viljan..."
186,109,Vääna-Jõesuu rand,NaN,NaN,"Vääna-Jõesuu küla, Harku vald, Harju maakond","(Vääna-Jõesuu küla, Harku vald, Harju maakond,..."
187,231,Väätsa paisjärv,NaN,NaN,"Väätsa alevik, Türi vald, Järva maakond","(Väätsa alevik, Türi vald, Järva maakond, 7280..."
188,188,Vaibla supluskoht Võrtsjärve ääres,NaN,NaN,"Vaibla küla, Viljandi vald, Viljandi maakond","(Vaibla küla, Viljandi vald, Viljandi maakond,..."
189,165,Väike-Viik,NaN,NaN,"Haapsalu linn, Haapsalu linn","(Haapsalu linn, Lääne maakond, Eesti, (58.9399..."
190,324,Vaikne järve supluskoht,NaN,NaN,"Uderna küla, Elva vald, Tartu maakond","(Uderna küla, Elva vald, Tartu maakond, 61016,..."
191,96,Väinjärv,NaN,NaN,"Väinjärv, 73021 Väinjärve küla, Järva vald, Jä...",None
192,220,Valdeku karjäär,NaN,NaN,"Männiku küla, Saku vald, Harju maakond","(Männiku küla, Saku vald, Harju maakond, 75511..."
193,73,Valgerand,NaN,NaN,"Valgeranna küla, Pärnu linn","(Valgeranna küla, Pärnu linn, Pärnu maakond, 8..."
194,225,Valkla rand,NaN,NaN,"Valkla küla, Kuusalu vald, Harju maakond","(Valkla küla, Kuusalu vald, Harju maakond, 746..."
195,244,Vana-Koiola järv,NaN,NaN,"Vana-Koiola küla, Põlva vald, Põlva maakond","(Vana-Koiola küla, Põlva vald, Põlva maakond, ..."
196,61,Vanamõisa järve supluskoht,NaN,NaN,"Tõrva linn, Tõrva vald, Valga maakond","(Tõrva linn, Tõrva vald, Valga maakond, Eesti,..."
197,137,Vana-Pärnu rand,NaN,NaN,"Pärnu linn, Pärnu linn","(Pärnu linn, Pärnu maakond, Eesti, (58.3870833..."
198,238,Varnja aleviku Pardiranna supluskoht,NaN,NaN,"Pardiranna, Varnja alevik, Peipsiääre vald, Ta...",None
199,71,Värska Sanatooriumi supluskoht,NaN,NaN,"Väike-Rõsna küla, Setomaa vald, Võru maakond","(Väike-Rõsna küla, Setomaa vald, Võru maakond,..."
200,213,Vasalemma karjääri veekogu,NaN,NaN,"Vasalemma alevik, Lääne-Harju vald, Harju maakond","(Vasalemma alevik, Lääne-Harju vald, Harju maa..."
201,123,Vasikaholmi supluskoht,NaN,NaN,"Haapsalu linn, Haapsalu linn","(Haapsalu linn, Lääne maakond, Eesti, (58.9399..."
202,243,Vaskjala veehoidla,NaN,NaN,"Vaskjala küla, Rae vald, Harju maakond","(Vaskjala küla, Rae vald, Harju maakond, Eesti..."
203,242,Vastemõisa küla supluskoht,NaN,NaN,"Vastemõisa küla, Põhja-Sakala vald, Viljandi m...","(Vastemõisa küla, Põhja-Sakala vald, Viljandi ..."
204,456,Veisjärv,NaN,NaN,"Veisjärve küla, Viljandi vald, Viljandi maakond","(Veisjärve küla, Viljandi vald, Viljandi maako..."
205,59,Verevi järve supluskoht,NaN,NaN,"Tartu mnt, Elva linn, Elva vald, Tartu maakond","(Tartu mnt, Verevi, Elva linn, Elva vald, Tart..."
206,161,Vesiroosi tervisepark,NaN,NaN,"Vesiroosi tervisepark, Rapla linn, Rapla vald,...",None
207,216,Viitina järv,NaN,NaN,"Viitina järv, Viitina küla, Rõuge vald, Võru m...","(Viitina järv, Viitina, Viitina küla, Rõuge va..."
208,376,Viitna Pikkjärv,NaN,NaN,"Loobu metskond 71, 45202 Viitna küla, Kadrina ...",None
209,74,Viljandi järve supluskoht,NaN,NaN,Viljandi linn,"(Viljandi linn, Viljandi maakond, Eesti, (58.3..."
210,499,Võnnu paisjärv,NaN,NaN,"Võnnu alevik, Kastre vald, Tartu maakond","(Võnnu alevik, Kastre vald, Tartu maakond, 624..."
211,340,"Võrtsjärve, Trepimäe supluskoht",NaN,NaN,"Trepimäe puhkeala, 61117 Vehendi küla, Elva va...","(Trepimäe puhkeala, Trepimäe tee, Vehendi, Veh..."
212,104,Võsu supluskoht,NaN,NaN,"Võsu alevik, Haljala vald, Lääne-Viru maakond","(Võsu alevik, Haljala vald, Lääne-Viru maakond..."

In [7]:
geocodeDF['x'] = geocodeDF['location'].apply(lambda loc: loc.latitude if loc else None)
geocodeDF['y'] = geocodeDF['location'].apply(lambda loc: loc.longitude if loc else None)
geocodeDF

,id,name,x,y,address,location
162,232,Roosna-Alliku tehisjärv,59.020029,25.698037,"Järve, 73203 Allikjärve küla, Paide linn","(Järve, Kaltenbrunni matkarada, Allikjärve kül..."
163,155,Roosta rand,59.155928,23.549833,"Elbiku küla / Ölbäck, Lääne-Nigula vald, Lääne...","(Elbiku küla / Ölbäck, Lääne-Nigula vald, Lään..."
164,249,Ropka järv,58.317802,26.611083,"Külitse alevik, Kambja vald, Tartu maakond","(Külitse alevik, Kambja vald, Tartu maakond, 6..."
165,178,Rõuge Suurjärve supluskoht,57.727904,26.921792,"Suurjärv, Rõuge alevik, Rõuge vald, Võru maakond","(Suurjärv, Rõuge alevik, Rõuge, Rõuge vald, Võ..."
166,82,Saadjärve Kukulinna,58.516296,26.715720,"Kukulinna küla, Tartu vald, Tartu maakond","(Kukulinna küla, Tartu vald, Tartu maakond, 60..."
167,85,Saadjärve Tabivere supluskoht,58.555453,26.588104,"Tabivere alevik, Tartu vald, Tartu maakond","(Tabivere alevik, Tartu vald, Tartu maakond, 4..."
168,226,Salmistu ranna parempoolne ala,59.486353,25.380737,"Salmistu küla, Kuusalu vald, Harju maakond","(Salmistu küla, Kuusalu vald, Harju maakond, 7..."
169,128,Sillamäe supluskoht,59.396265,27.762556,Sillamäe linn,"(Sillamäe linn, Ida-Viru maakond, Eesti, (59.3..."
170,148,Sindi väliujula (Pärnu jõgi),58.407513,24.658316,"Sindi linn, Tori vald, Pärnu maakond","(Sindi linn, Tori vald, Pärnu maakond, Eesti, ..."
171,210,Suure-Jaani paisjärv,58.537376,25.464948,"Suure-Jaani linn, Põhja-Sakala vald, Viljandi ...","(Suure-Jaani linn, Põhja-Sakala vald, Viljandi..."
172,331,Tambre paisjärve supluskoht,57.786577,26.086759,"Tambre tee, Valga linn, Valga vald, Valga maakond","(Tambre tee, Tambre, Valga linn, Valga vald, V..."
173,76,Tamula järve rand,57.843568,26.991596,"Tamula rand, Võru linn","(Tamula supelrand, Kesklinn, Võru linn, Võru m..."
174,102,Tarbja tehisjärv,NaN,NaN,"Tarbja tehisjärv, 72759 Tarbja küla, Paide linn",None
175,466,TEST Kooraste Pikkjärv,58.970405,24.125170,"Maidla küla, Märjamaa vald, Rapla maakond","(Maidla küla, Märjamaa vald, Rapla maakond, Ee..."
176,125,Toila rand,59.420903,27.513252,"Toila alevik, Jõhvi vald, Ida-Viru maakond","(Toila alevik, Toila, Jõhvi vald, Ida-Viru maa..."
177,207,Tõravere keskmine tiik,58.265516,26.466266,"Tõravere alevik, Nõo vald, Tartu maakond","(Tõravere alevik, Nõo vald, Tartu maakond, 616..."
178,206,Tõravere suur tiik,NaN,NaN,"Observatooriumi tn 5, Tõravere alevik, Nõo val...",None
179,290,Torma järv,58.819881,26.739404,"Torma alevik, Jõgeva vald, Jõgeva maakond","(Torma alevik, Jõgeva vald, Jõgeva maakond, 48..."
180,145,Tõrvanina supluskoht,59.016514,22.677556,"Tareste küla, Hiiumaa vald, Hiiu maakond","(Tareste küla, Hiiumaa vald, Hiiu maakond, Ees..."
181,228,Tsitre rand,59.515595,25.516859,"Tsitre küla, Kuusalu vald, Harju maakond","(Tsitre küla, Kuusalu vald, Harju maakond, 746..."
182,167,Tuhkana supluskoht,58.273820,22.277106,"Saaremaa vald, Saare maakond","(Saaremaa vald, Saare maakond, Eesti, (58.2738..."
183,95,Türi tehisjärv,NaN,NaN,"Tehisjärve, 72213 Türi linn, Türi vald, Järva ...",None
184,198,Ujumiskoht Üügu panga juures,58.661909,23.242361,"Kallaste küla, Muhu vald, Saare maakond","(Kallaste küla, Muhu vald, Saare maakond, 9474..."
185,418,Uueveski bassein,58.378622,25.602270,"Musta, 71073 Peetrimõisa küla, Viljandi vald, ...","(Musta tee, Uueveski, Peetrimõisa küla, Viljan..."
186,109,Vääna-Jõesuu rand,59.433236,24.365514,"Vääna-Jõesuu küla, Harku vald, Harju maakond","(Vääna-Jõesuu küla, Harku vald, Harju maakond,..."
187,231,Väätsa paisjärv,58.895140,25.455712,"Väätsa alevik, Türi vald, Järva maakond","(Väätsa alevik, Türi vald, Järva maakond, 7280..."
188,188,Vaibla supluskoht Võrtsjärve ääres,58.414595,26.135707,"Vaibla küla, Viljandi vald, Viljandi maakond","(Vaibla küla, Viljandi vald, Viljandi maakond,..."
189,165,Väike-Viik,58.939902,23.541480,"Haapsalu linn, Haapsalu linn","(Haapsalu linn, Lääne maakond, Eesti, (58.9399..."
190,324,Vaikne järve supluskoht,58.190745,26.405234,"Uderna küla, Elva vald, Tartu maakond","(Uderna küla, Elva vald, Tartu maakond, 61016,..."
191,96,Väinjärv,NaN,NaN,"Väinjärv, 73021 Väinjärve küla, Järva vald, Jä...",None
192,220,Valdeku karjäär,59.329097,24.716409,"Männiku küla, Saku vald, Harju maakond","(Männiku küla, Saku vald, Harju maakond, 75511..."
193,73,Valgerand,58.393349,24.364001,"Valgeranna küla, Pärnu linn","(Valgeranna küla, Pärnu linn, Pärnu maakond, 8..."
194,225,Valkla rand,59.469201,25.340611,"Valkla küla, Kuusalu vald, Harju maakond","(Valkla küla, Kuusalu vald, Harju maakond, 746..."
195,244,Vana-Koiola järv,57.954423,27.073445,"Vana-Koiola küla, Põlva vald, Põlva maakond","(Vana-Koiola küla, Põlva vald, Põlva maakond, ..."
196,61,Vanamõisa järve supluskoht,58.002820,25.925361,"Tõrva linn, Tõrva vald, Valga maakond","(Tõrva linn, Tõrva vald, Valga maakond, Eesti,..."
197,137,Vana-Pärnu rand,58.387083,24.502831,"Pärnu linn, Pärnu linn","(Pärnu linn, Pärnu maakond, Eesti, (58.3870833..."
198,238,Varnja aleviku Pardiranna supluskoht,NaN,NaN,"Pardiranna, Varnja alevik, Peipsiääre vald, Ta...",None
199,71,Värska Sanatooriumi supluskoht,57.979462,27.621451,"Väike-Rõsna küla, Setomaa vald, Võru maakond","(Väike-Rõsna küla, Setomaa vald, Võru maakond,..."
200,213,Vasalemma karjääri veekogu,59.238352,24.286528,"Vasalemma alevik, Lääne-Harju vald, Harju maakond","(Vasalemma alevik, Lääne-Harju vald, Harju maa..."
201,123,Vasikaholmi supluskoht,58.939902,23.541480,"Haapsalu linn, Haapsalu linn","(Haapsalu linn, Lääne maakond, Eesti, (58.9399..."
202,243,Vaskjala veehoidla,59.366555,24.949979,"Vaskjala küla, Rae vald, Harju maakond","(Vaskjala küla, Rae vald, Harju maakond, Eesti..."
203,242,Vastemõisa küla supluskoht,58.434790,25.442840,"Vastemõisa küla, Põhja-Sakala vald, Viljandi m...","(Vastemõisa küla, Põhja-Sakala vald, Viljandi ..."
204,456,Veisjärv,58.097019,25.776704,"Veisjärve küla, Viljandi vald, Viljandi maakond","(Veisjärve küla, Viljandi vald, Viljandi maako..."
205,59,Verevi järve supluskoht,58.231440,26.407717,"Tartu mnt, Elva linn, Elva vald, Tartu maakond","(Tartu mnt, Verevi, Elva linn, Elva vald, Tart..."
206,161,Vesiroosi tervisepark,NaN,NaN,"Vesiroosi tervisepark, Rapla linn, Rapla vald,...",None
207,216,Viitina järv,57.690466,26.948503,"Viitina järv, Viitina küla, Rõuge vald, Võru m...","(Viitina järv, Viitina, Viitina küla, Rõuge va..."
208,376,Viitna Pikkjärv,NaN,NaN,"Loobu metskond 71, 45202 Viitna küla, Kadrina ...",None
209,74,Viljandi järve supluskoht,58.364540,25.587807,Viljandi linn,"(Viljandi linn, Viljandi maakond, Eesti, (58.3..."
210,499,Võnnu paisjärv,58.286801,27.052091,"Võnnu alevik, Kastre vald, Tartu maakond","(Võnnu alevik, Kastre vald, Tartu maakond, 624..."
211,340,"Võrtsjärve, Trepimäe supluskoht",58.230536,26.131721,"Trepimäe puhkeala, 61117 Vehendi küla, Elva va...","(Trepimäe puhkeala, Trepimäe tee, Vehendi, Veh..."
212,104,Võsu supluskoht,59.576518,25.955366,"Võsu alevik, Haljala vald, Lääne-Viru maakond","(Võsu alevik, Haljala vald, Lääne-Viru maakond..."